### ISSUE TITLE
Error while running npx promptfoo@latest init --no-interactive my-redteam-project on Mac M1

### ISSUE THREAD

**Issue by rrbanda** [promptfoo/promptfoo#1001]
```
npx promptfoo@latest generate redteam -w                     
(node:18610) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Cache is disabled.
Synthesizing test cases for 2 prompts...
Plugins: contracts, excessive-agency, hallucination, harmful, hijacking, jailbreak, overreliance, pii, politics, prompt-injection, harmful:violent-crime, harmful:non-violent-crime, harmful:sex-crime, harmful:
 █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 2% | ETA: 1s | 2/100/Users/me/.npm/_npx/81bbc6515d992ace/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14
    throw new Error(value);
          ^

Error: Invariant failed: Expected purpose to be a string
    at invariant (/Users/me/.npm/_npx/81bbc6515d992ace/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14:11)
    at getPurpose (/Users/me/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/redteam/index.js:145:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async synthesize (/Users/me/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/redteam/index.js:83:41)
    at async Command.<anonymous> (/Users/me/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/main.js:413:30)
```

**Comment by mldangelo** [comment]
Hi @rrbanda,

Thanks for reporting this issue. You can override the inferred purpose by setting the flag `--purpose 'your purpose'`. See [src/main.ts#L505](https://github.com/promptfoo/promptfoo/blob/main/src/main.ts#L505) for the CLI args, [src/redteam/index.ts#L120](https://github.com/promptfoo/promptfoo/blob/main/src/redteam/index.ts#L120) for where the override is applied, and [src/redteam/index.ts#L181](https://github.com/promptfoo/promptfoo/blob/main/src/redteam/index.ts#L181) for how the purpose is inferred from your prompts (and example purposes - consider inserting a debug log here). 

If you can share more of your config or would like to jump on a call to debug together, I would be happy to look at this with you.

**Comment by typpo** [comment]
Also you may have to set OPENAI_API_KEY as an environment variable.

**Comment by rrbanda** [comment]
@typpo basicall I would like to be able to generate using ollama/mistral

**Comment by typpo** [comment]
Got it. @mldangelo is working on this in #1002

**Comment by rrbanda** [comment]
Thanks @typpo looks this is about to be merged @mldangelo

**Comment by mldangelo** [comment]
@rrbanda We just released the ability to configure custom providers in `0.66.0`. You can try it out with 
```sh
npx promptfoo@latest generate redteam -w --provider ollama:llama2-uncensored
```
I also added better debug logging for when `purpose` is not a string. Please give it a try and let me know if you run into any issues.

**Comment by rrbanda** [comment]
Thanks @mldangelo i m working on evaluating this . will keep posted if something comes up
