### ISSUE TITLE
Use @googleapis/* packages instead of googleapis

### ISSUE THREAD

**Issue by benasher44** [promptfoo/promptfoo#1008]
The googleapis package is over 100MB, installed. You can instead use @googleapis/* packages to pull in the exact packages you need (and google-auth-library where needed for auth). They're the same code as what's in googleapis.

**Comment by typpo** [comment]
Thanks for flagging, done in https://github.com/promptfoo/promptfoo/pull/1009

**Comment by typpo** [comment]
This is included in the latest release!
