### ISSUE TITLE
Proxy Support for Azure with Client credentials

### ISSUE THREAD

**Issue by chittamitgit** [promptfoo/promptfoo#1012]
Hello Team,

Please add proxy support with authentication (proxy with optional user name and password) to your code to consider it from either ENV variable or from YAML file as a parameter.

Our azure onenAI is inside our company and promptfoo unable to connect. It comes back with connection error ETIMEDOUT.

I am able to connect from postman or Java code with proxy. But from command prompt it is not connecting. Please note I am running with "promptfoo eval" command from windows cmd. I tried to give proxy in ENV User variable but not working.
Appreciate your help in this as I am stuck due to this.

Thank you
Chitta

**Comment by chittamitgit** [comment]
I see an article if it helps to add to your code base as I guess the code using node fetch for the api.

https://stackoverflow.com/questions/60162485/how-to-configure-node-fetch-to-use-the-company-proxy

**Comment by typpo** [comment]
The requests to Azure are made with [proxy-agent](https://www.npmjs.com/package/proxy-agent), which respects `HTTP_PROXY` and `HTTPS_PROXY` [environment variables](https://www.npmjs.com/package/proxy-from-env#environment-variables).  You should be able to set them accordingly to `[protocol://]<host>[:port]` of your proxy!
