### ISSUE TITLE
How to compare two separate eval runs in the Web UI

### ISSUE THREAD

**Issue by efung** [promptfoo/promptfoo#1025]
In the config, if I've defined two prompts, or two providers, I see the side-by-side results in the Web UI.

What about the situation if I or someone else have run an eval on a single prompt or provider, and want to combine our two results and see them in the promptfoo Web UI?  Can that be done?

**Comment by typpo** [comment]
Two thoughts on how to solve this:
- Purely on the UI side, have a way to select existing evals to include in the view, or
- Add a 'promptfoo eval merge` CLI command or similar that lets you select evals to combine together.  This will enable better first-class support for share, export, etc.

**Comment by efung** [comment]
> Purely on the UI side, have a way to select existing evals to include in the view, or

I like this UI solution for the use case of multiple collaborators running their own evals, then wanting to do comparisons among the eval runs.

Merging evals together might have its own use cases, but I think would be cumbersome for browsing.

**Comment by typpo** [comment]
"Compare evals" functionality landed in the UI under `Table Settings`
