### ISSUE TITLE
Allow filtering pre-defined providers (like --filter-pattern but for providers)

### ISSUE THREAD

**Issue by aantn** [promptfoo/promptfoo#1048]
I have a promptfooconfig.yaml which defines multiple custom providers. I want to pass cli flag to `promptfoo eval` which will select providers which a regex on the labels field.

I tried using the `-r` flag for this, but it seems to define a new provider to use, not filter on existing providers defined in the config.

**Comment by typpo** [comment]
Implemented in #1089!

**Comment by aantn** [comment]
Thanks!
