### ISSUE TITLE
Chaining Prompts

### ISSUE THREAD

**Issue by CameronTofer** [promptfoo/promptfoo#1067]
Hi, I like promptfoo.  It feels natural that I should be able to:

prompts:
  - [ "Tell me a story", "Summarize the following: {{outputs[-1]}}", "Translate the following to Spanish {{outputs[1]}}\n{{outputs[0]}}]

Is there a way to accomplish this already?  would this be difficult to implement?

**Comment by typpo** [comment]
You may be interested in [`_conversation`](https://promptfoo.dev/docs/configuration/chat/#using-the-conversation-variable) or [`storeOutputAs`](https://promptfoo.dev/docs/configuration/chat/#using-storeoutputas), which lets you more or less do this.

**Comment by CameronTofer** [comment]
hmm, not quite. Unless I can storeOutputAs on the prompt itself. but thanks anyway.

**Comment by typpo** [comment]
With `_conversation`, you can access previous outputs like `_conversation[0].output` and `_conversation[1].output`.  The last output is `_conversation[_conversation.length - 1].output`.  As far as I can see from your original example, this covers all the variables you need and you can use them in the prompt.

**Comment by typpo** [comment]
LMK if you have any more questions about this!
