### ISSUE TITLE
how to save a session in custom python provider

### ISSUE THREAD

**Issue by landhu** [promptfoo/promptfoo#1070]
Our LLM does not support API_KEY
So, I write a custom python(python requests) to login.
But I don't login again and again in eval. I just want to log in once, save the session, and have this session behind it.
How can I do.

Here is my simple yaml:
`providers:
  - id: "python:my_chat.py"
    label: "my_chat"
    config:
`

my_chat.py:

`def call_api(prompt, options, context):
    config = options.get("config", None)
    additional_option = config.get('additionalOption', None)
    user_variable = context['vars'].get('userVariable', 'user_a')
    login(user_variable)
`

**Comment by mldangelo** [comment]
Hi @landhu, can you share more about your integration? Which LLM are you using? Have you tried to persist your session in your custom python provider?

**Comment by landhu** [comment]
@mldangelo I am a QA, LLM was secondary encapsulation by Dev, we just access it by login(user/password). 
**Have you tried to persist your session in your custom python provider?**
  --  I don't know how to persist. do you have demo? I tried put session in enviroment. like: os.environ['OWNER_A_AUTH']. But it's not working.

**Comment by mldangelo** [comment]
Hi @landhu, I'm sorry you're having trouble. `os.environ['OWNER_A_AUTH']` is unlikely to work unless you have something that is specifically checking for that env var. Here are a few general tips:

1. Try searching online for how to persist sessions in Python.
2. Check if there's a header in your request that you can reuse. 
3. Consider converting your username and password into an auth token programmatically.
4. You can also ask a language model like ChatGPT or Claude for help with this. I did and got many code examples. 

Good luck! Please let us know if you have any other issues specific to promptfoo.
