### ISSUE TITLE
Error: Please support "Similarity" on the fly with library instead of making a call with AZURE_OPENAI_API_KEY

### ISSUE THREAD

**Issue by chittamitgit** [promptfoo/promptfoo#1074]
Team, Our company does not allow us to use AZURE_OPENAI_API_KEY.

When I try it comes back with - Key based authentication is disabled.

If you can do something like what Spacy does it would be great to do from the library itself.

Or I am also fine if you could support something like custom API with JS you do to make calls. E.g.   - id: customApiProvider.js.

Waiting for your response. Your help is highly appreciated as this is needed for our high priority project with a tight deadline.

**Comment by mldangelo** [comment]
Hi @chittamitgit, thanks for reaching out. I'm not entirely sure how you want to authenticate without an API key. Could you please provide an example of what you mean with Spacy? 

For custom providers, please check out our [custom provider example](https://github.com/promptfoo/promptfoo/tree/main/examples/custom-provider). Additionally, you can set an API key in the provider config. More details can be found [here](https://www.promptfoo.dev/docs/providers/openai#configuring-parameters). I hope this helps! Please feel free to re-open if this doesn't resolve your issue.

**Comment by chittamitgit** [comment]
I mean to have required similarity check library available as part of the npm promtfoo install.  And we need not got to Open AI or Azure to help us in making similarity check.

Sharing a Sample code of "spacy".

import spacy_universal_sentence_encoder

nlp = spacy_universal_sentence_encoder.load_model('en_use_lg')

String promptOneTextOutput= nlp ("My Actual Output")

String promptTwoTextOutput= nlp ("My Expected output")

print (promptOneTextOutput.similarity(promptTwoTextOutput))

**Comment by chittamitgit** [comment]
if text-embedding-3-large model of openAI or Azure can be supported by custom API is also fine where I can use the azure client secret and client ID. Can you please guide if it is possible to use this way?

**Comment by chittamitgit** [comment]
I am expecting something like this below where in assert we can inject a provider as custom API to support above grant-type as client credential way.
prompts:
  - prompt.txt

providers:
  - id: customApiProvider.js
    label: 'My custom provider'

tests:
  - description: 'Test if output is equal to the expected value'
    vars:
      example: 'Hello'
    assert:
      - type: similar
        value: 'Hola'
        **_provider: customApiProviderForSimilityCheck.js_**
        threshold: 0.8
