### ISSUE TITLE
Is there a way to run 1 eval N times?

### ISSUE THREAD

**Issue by wongstein** [promptfoo/promptfoo#1075]
There are some evals that I'd like to benchmark at N == 100 on the same prompt.  Is there a cleaner way to do that without having to write an eval file that repeats the eval 100 times?

**Comment by typpo** [comment]
If you pass `--repeat 100` to `promptfoo eval` it will repeat the eval for you so you don't have to copy it 100x. The output is not exactly the "cleanest" (it's still the same test over and over), but at least your config will be clean.
