### ISSUE TITLE
assert type similar should consider custom provider js file

### ISSUE THREAD

**Issue by chittamitgit** [promptfoo/promptfoo#1078]
Hi Team, I see there is a example where similar can use file like customprovider.js but when I try to use it comes back with a error OpenAI API key must be set for similarity comparison.

Please advise how to use custom js file.

I basically wants to use client credentials like client ID and secret to get a access token and inject to make a call to end point https://the-***.openai.azure.com/openai/deployments/**textembedding/embeddings?api-version=2024-**

Please guide how to use. 

I see sample example in GIT site is below:

prompts:
  - 'Translate this to French: {{message}}'

providers:
  - openai:chat:gpt-3.5-turbo

tests:
  - vars:
      message: Hello world
    assert:
      - type: similar
        threshold: 0.25
        value: 'Greetings earth'
        provider: ./customProvider.js

My use would be:

prompts:
  - 'Translate this to French: {{message}}'

providers:
  **_- id: customApiProvider.js_**

tests:
  - vars:
      message: Hello world
    assert:
      - type: similar
        threshold: 0.25
        value: 'Greetings earth'
        **_provider: customEmbeddedApiProvider.js_**

Your help is highly appreciated.

**Comment by typpo** [comment]
Hi @chittamitgit, you can use Azure OpenAI embedding models for the similarity grader by overriding the `embedding` grader.  There's an example [here](https://promptfoo.dev/docs/configuration/expected-outputs/model-graded/#multiple-graders) with details on how to configure the provider with client credentials [here](https://promptfoo.dev/docs/providers/azure/#using-client-credentials).

On the other hand, if you implement a custom provider yourself, you will have to import the appropriate azure packages or logic to handle client credentials in your implementation.

**Comment by chittamitgit** [comment]
Thank you @typpo . I am able to use custom api to get the response with azure client credentials with below example where customApiProvider has the logic with client credentials.
prompts:
  - 'Translate this to French: {{message}}'

providers:
  - id: customApiProvider.js.

But if I want to use assert type "similar", how to make config file to make it run from custom api js file like above config I do?

Please guide if below config is correct.
assert:
type: similar
threshold: 0.25
value: 'Greetings earth'
**provider: customEmbeddedApiProvider.js**

**Comment by chittamitgit** [comment]
Team: feel free to close. I am able to use with custom API now. Thank you for your time and help!
