### ISSUE TITLE
ReDoS Vulnerability in Async Dependency in promptfoo Library

### ISSUE THREAD

**Issue by oksanagorbachenko** [promptfoo/promptfoo#1111]
I ran tests using a Docker container, and the vulnerability scanner for images gave me this message. Is there a possibility to update the Async library to a stable version?

The promptfoo library uses the Async <= 2.6.4 and <= 3.2.5 dependencies, which are vulnerable to ReDoS (Regular Expression Denial of Service) when parsing the function in autoinject.

**1TH**
Name - async
Installed version / Fixed version
0:3.2.5 / Not available
Package manager
NODEPKG
File paths
usr/local/lib/node_modules/promptfoo/node_modules/async/package.json

**2ND**
Name - async
Installed version / Fixed version
0:3.2.3 / Not available
Package manager
NODEPKG
File paths
usr/local/lib/node_modules/promptfoo/node_modules/cache-manager/node_modules/async/package.json

**Comment by typpo** [comment]
The maintainers of async consider this to be a false positive CVE, so it is unlikely to be fixed.  https://github.com/caolan/async/issues/1975

**Comment by mldangelo** [comment]
Thanks for reporting this @oksanagorbachenko. As you pointed out, this is an issue in async. See https://github.com/caolan/async/issues/1975 for a discussion about it. We will fix it as soon as they publish a fix.

**Comment by mldangelo** [comment]
One more note on this. The maintainers of async requested a retraction of the CVE. I am going to close this issue as a WONTFIX. We'll update async if the maintainers choose to update it. Thanks @oksanagorbachenko If you want to discuss this further (or explain why this is important to you please feel free to reach out via email - michael@promptfoo.dev)
