### ISSUE TITLE
Is there a way to assert only a part of the LLMresponse ?

### ISSUE THREAD

**Issue by SysOverdrive** [promptfoo/promptfoo#1119]
Imagine a scenario where you have an SQL LLM Agent that also prefixes each answer with the target app in which to be used:

Example LLM Response:

CoalContext
SELECT *
FROM
..

FarmContext
SELECT *
FROM
..

Is there any way to use  - type: contains-sql or is-sql specifically on the sql portion without the prefix ?

**Comment by mldangelo** [comment]
@SysOverdrive check out https://www.promptfoo.dev/docs/configuration/guide/#transforming-outputs 

You should be able to write something like 

```yaml
tests:
  - vars:
      ...
    options:
      transform: |
        const selectIndex = output.indexOf('SELECT');
        if (selectIndex !== -1) {
          return output.substring(selectIndex);
        }
        return output;
 ```
 or in an external file 
 
 ### transform.js
 ```js
 module.exports = (output, context) => {
  const selectIndex = output.indexOf('SELECT');
  // Extract the substring starting from "SELECT"
  if (selectIndex !== -1) {
    return output.substring(selectIndex);
  }
  // Return the original output if "SELECT" is not found
  return output;
};
```
with 

```yaml
defaultTest:
  options:
    transform: file://./transform.js
```

**Comment by SysOverdrive** [comment]
Thanks very useful will try this and come back to you on this thread.
