### ISSUE TITLE
Does promptfoo accept multimodal input

### ISSUE THREAD

**Issue by ujjwalm29** [promptfoo/promptfoo#1164]
Hello, my LLM workflow is heavily dependent on images being used along with each text prompts. Does promptfoo support this kind of workflow? I couldn't find any mentions of this in documents so my assumption is NO, but just wanted to check.

TIA!

**Comment by mldangelo** [comment]
Yes, it does, and we have several examples:

- [Claude via AWS and Anthropic with a JSON prompt](https://github.com/promptfoo/promptfoo/tree/main/examples/claude-vision)
- [Claude vs GPT-4 with JavaScript and Python prompts](https://github.com/promptfoo/promptfoo/tree/main/examples/claude-vs-gpt-image)
- [Local Gemma via LM Studio](https://github.com/promptfoo/promptfoo/tree/main/examples/image-classification)
- [DALL·E image generation](https://github.com/promptfoo/promptfoo/tree/main/examples/openai-dalle-images)

Let us know if you get stuck or have any more questions! Thanks!

**Comment by ujjwalm29** [comment]
That's fantastic, Michael! Apologies for not reading the docs more thoroughly. Might be better to highlight this as a "feature" in the docs, for n00bs like me.

**Comment by mldangelo** [comment]
No problem at all! I'll update the docs. Thanks for the callout. Please let us know if you run into any other issues.

**Comment by soerenbrockmann** [comment]
Hi, does it also work with the Jest integration?
