### ISSUE TITLE
Bug - model-graded-closedqa shows as failed if the reason have some extra explanation 

### ISSUE THREAD

**Issue by shahriardn** [promptfoo/promptfoo#1166]
In some cases, the output of the model-graded-closedqa has additional information. So, the test is detected as a failure. Below is a sample of it. 
![image](https://github.com/user-attachments/assets/4eb9c48a-ad92-48e3-ac34-b6b11f899b9b)

**Comment by shahriardn** [comment]
Hi @typpo 
No, it's GPT 4

**Comment by typpo** [comment]
Closing as this is an issue with OpenAI's prompt.  Because `model-graded-closedqa` is an exact replica of their prompt, nothing we can do here.  I recommend that you use `llm-rubric` instead for your use case.
