### ISSUE TITLE
Can't run promptfoo when Langgraph is getting system-prompts from config.yaml

### ISSUE THREAD

**Issue by beschmitt** [promptfoo/promptfoo#1205]
I'm trying to evaluate my langgraph-model with promptfoo. However every time I'm trying to run the eval-command it tells me, that it can't find the config.yaml file where my system prompts are located.
I have written the different system prompts for my different nodes in this config.yaml and I'm importing them when needed.

**Comment by mldangelo** [comment]
@beschmitt I'm sorry you're running into an issue. Can you share more about your configuration including your promptfoo config and the directory structure surrounding it? Feel free to put time on my calendar if you would like to review this together: https://cal.com/michael-dangelo/30min

**Comment by beschmitt** [comment]
@mldangelo my directory structure looks something like this:
- root
    - promptfooconfig.yaml
    - project folder
        - subdirectory 1
            - subdirectory 2
                - config.yaml
                - subdirectory 3
                    - executable python file

The executable python is my chatbot that reads in the system prompts from my config.yaml
The executable python file has the following code:
```
import sys

from langgraph_constructor import app

question = sys.argv[1]

app.invoke({"question":question})
```

Where app is my compiled langgraph workflow.

The promptfooconfig.yaml has 
prompts: prompt.txt

providers:
    - "exec:python path/to/executable_python_file.py"

tests:
    - vars:
        question: Example question

My prompt.txt consists of {{question}} since all the system prompts are already in the graph.
