### ISSUE TITLE
Docs bug: broken link on Gemini safety settings

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#1206]
Fyi https://www.promptfoo.dev/docs/providers/vertex/#safety-settings links https://ai.google.dev/api/rest/v1/SafetySetting, which is giving me a 404 error

**Comment by jamesbraza** [comment]
Maybe there is a link checker for Docusaurus that can be added to CI or build process

**Comment by typpo** [comment]
Looks like this is the new link, which looks suspiciously un-futureproof as well: https://ai.google.dev/api/generate-content#safetysetting
