### ISSUE TITLE
Feature Request: Delay api calls (GPT-4 requirement)

### ISSUE THREAD

**Issue by sarons** [promptfoo/promptfoo#121]
Promptfoo has been great so far. But we are running into problems with GPT-4.
Since it has lower rate & token limits, most api calls fail after around 20 calls.

Would be good to have an option to delay the calls, maybe after X number of calls or X number of tokens

I tried adding a delay in the __expected column of the csv but that didn't work either.
If you could add a guide on how to run the repo locally, I can also try adding it.

Thanks

**Comment by typpo** [comment]
Hi @sarons,

There are a few things you can do here:

1. **Reduce concurrency to 1** by setting `--max-concurrency 1` in the CLI, or by setting `evaluateOptions.maxConcurrency` in the config.
2. **Set a delay between requests** by setting `--delay 3000` in the CLI, or by setting `evaluateOptions.delay` in the config, or with the environment variable `PROMPTFOO_DELAY_MS` (all values are in milliseconds).
3. **Adjust the exponential backoff for failed requests** by setting the environment variable `PROMPTFOO_REQUEST_BACKOFF_MS`.  This defaults to 5000 milliseconds and retries exponential up to 4 times.  You can increase this value if requests are still failing, but note that this can significantly increase end-to-end test time.

Note that 2 and 3 were added in #122 (version 0.21.3), so you will have to update to get this functionality.

Hope this helps!

**Comment by sarons** [comment]
Oh awesome! Will give it a try.
I actually came up with another crazy solution in the meantime btw: I split my csv into mini csvs with 10 rows then ran promptfoo on each one to get mini output csv and then merged all the csvs into one csv [😅](https://emojipedia.org/grinning-face-with-sweat)

**Comment by typpo** [comment]
Now _that's_ a workaround... feel free to reopen this issue if the delay feature doesn't solve your problem!
