### ISSUE TITLE
Pipe Character Splitting Prompt 

### ISSUE THREAD

**Issue by aliasghar98** [promptfoo/promptfoo#1281]
I am using a prompt which has multiple `|` symbols used in it. Somehow, promptfoo splits the prompt into multiple prompts. Is there a fix or workaround for this without removing the pipe character?

**Comment by typpo** [comment]
Example config?

This is probably due to the behavior of pipe in YAML, which can be escaped.

**Comment by aliasghar98** [comment]
The config file is as follows:
prompts: 
  - ../../../../prompts/myPrompt.txt

providers: 
  - *insert provider data here, using openai:gpt-4o at the moment.*

tests:
  - assert:
    - type: icontains-all
      value: 
        - 'someValue'
        
 
 The myPrompt.txt looks like the following:
 Some very long text here blah blah blah | Something written here | Something written here too | Some more very long text here.
 
 
 This gets split up like this, which is not what I wanted: 
 
![image](https://github.com/user-attachments/assets/e1a075f5-081e-46c0-8f9c-2a58aacb8fcd)

**Comment by typpo** [comment]
Unfortunately I'm unable to repro with the following.  If you could share an exact example or a zip, that could help.

promptfooconfig.yaml:
```
prompts:
  - prompt.txt
providers:
  - openai:gpt-4o-mini

tests:
  - assert:
    - type: icontains-all
      value:
        - 'someValue'
```
prompt.txt:
```
Some very long text here blah blah blah | Something written here | Something written here too | Some more very long text here.
```

**Comment by aliasghar98** [comment]
Ah apologies, I just noticed that there was the `---` separator between the pipe characters, which is why it was being split. Didn't notice these before.

**Comment by typpo** [comment]
Got it.  One workaround here would be to override the separator to something that you're not using, with the `PROMPTFOO_PROMPT_SEPARATOR` environment variable.

For example
```
PROMPTFOO_PROMPT_SEPARATOR=xxxxxxxxxx promptfoo eval
```

**Comment by aliasghar98** [comment]
Thanks! Closing this.
