### ISSUE TITLE
Supporting PROMPTFOO_DELAY_MS for Gemini

### ISSUE THREAD

**Issue by aisonym** [promptfoo/promptfoo#1289]
Gemini has really strict quotas for Gemini 1.5 Pro (at least for those just signing up through normal flow - 60 requests per minute).

Can you support PROMPTFOO_DELAY_MS like you do for OpenAI? (In case it's supported and I'm just not doing it right - code below that doesn't throw and error but also seems to have no impact).

```
  - id: vertex:gemini-1.5-pro
    config:
      PROMPTFOO_DELAY_MS: 1000
```

P.S. Congrats on the funding.

**Comment by typpo** [comment]
Hmm, `PROMPTFOO_DELAY_MS` is actually implemented on the evaluator level, so it should work for everything.

However, it needs to be set as an environmental variable:
```
PROMPTFOO_DELAY_MS=1000 promptfoo eval
```

You can also use it as a CLI arg like this:
```
promptfoo eval --delay 1000
```

**Comment by aisonym** [comment]
Pardon my ignorance.

Thank you.

**Comment by mldangelo** [comment]
@aisonym don't worry! It was a good question. Let us know if you encounter any other issues.

**Comment by aisonym** [comment]
If I were to be nitpicky - I'd point out that it's only mentioned on the OpenAI page... (https://www.promptfoo.dev/docs/providers/openai/) although to be fair it is mentioned in the "supported environment variables" section.
