### ISSUE TITLE
The test progress when using nodejs package

### ISSUE THREAD

**Issue by zhlmmc** [promptfoo/promptfoo#129]
Is there a way to get the testing progress when using NodeJS package? When using CLI, I can see a progress bar and I can see how many cases are done of total cases. But when using NodeJS package, I can only see three functions to call:
![image](https://github.com/promptfoo/promptfoo/assets/1726527/731d2357-44f0-415d-a1e8-6964b3f80f86)

Not sure if the case is supported. Thanks!

**Comment by typpo** [comment]
There is!  The `evaluate` function takes a callback: 

```ts
promptfoo.evaluate(config, {
  progressCallback: (progress: number, total: number) {
    console.log(`${progress} of ${total} complete`);
  }
});
```
