### ISSUE TITLE
Selecting something on the ui for copy paste doesn't work

### ISSUE THREAD

**Issue by rishimalhotra2** [promptfoo/promptfoo#1290]
**Describe the bug**
On the UI, when you select some text in the output tab, the selection disappears and the state of the cell toggles.

**To Reproduce**
run an evaluation and then go to the table view on web.

**Expected behavior**
When you select the UI, the state of the output should not toggle.

**Screenshots**
![image](https://github.com/user-attachments/assets/29538c12-9537-4ba5-8075-5fd1e79e81bf)

When you select "The first question you asked", the selection disappears and the state of the output toggles. this makes it impossible to copy paste parts of the output.

**System information (please complete the following information):**

- Promptfoo version: 0.73.6

**Comment by typpo** [comment]
Thanks @rishimalhotra2.  #1295 should help with this.

**Comment by mldangelo** [comment]
@rishimalhotra2 this was recently deployed. You can test it out with `npx promptfoo@latest ...`. Thank you!
