### ISSUE TITLE
Improve Documentation regarding embedding providers

### ISSUE THREAD

**Issue by Luca-Hackl** [promptfoo/promptfoo#1294]
I needed to implement a custom embedding provider due to the API utilized by the company i work for, for specific embedding models. It took quite some time to discover that I required the method call EmbeddingApi instead of simply callApi in my custom JavaScript provider. I believe this should be noted in Providers -> Custom Javascript. If desired, I would be pleased to create a pull request with an example and the necessary documentation.

**Comment by typpo** [comment]
Sorry about that, @Luca-Hackl.  A PR would be much appreciated!

**Comment by mldangelo** [comment]
Thanks so much @Luca-Hackl for making the docs better!
