### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by Sbkubuii** [promptfoo/promptfoo#1318]
Hello,

As a fan of promptfoo, I'd appreciate if you could add a CITATION.cff file to the repository. This would help users like me properly credit your work.For guidance, see: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

Thank you for considering! 😁

**Comment by mldangelo** [comment]
Thanks for the suggestion @Sbkubuii! This just went into main. Please let us know if there's anything else we can do to accelerate your research!
