### ISSUE TITLE
cache when using Node.js package

### ISSUE THREAD

**Issue by zhlmmc** [promptfoo/promptfoo#132]
I'm wondering if there is cache mechanism when using Node.js package? From the documents, it seems that no cache when using Node.js package. But from my tests, I found the speed of the same tests varies a lot. If cache is supported in Node.js package, how do I disable it?

Also, I found some config options are not available in Node.js package:
![image](https://github.com/promptfoo/promptfoo/assets/1726527/20327d7b-2085-46d3-a938-66398e9bea4c)

**Comment by typpo** [comment]
To force-disable the cache, you can set the environment variable `PROMPTFOO_CACHE_ENABLED=0`

`evaluateOptions` are passed as a second argument to the `evaluate()` function in the node package.  Its function signature is:

```ts
function evaluate(testSuite: EvaluateTestSuite, options?: EvaluateOptions): Promise<EvaluateSummary>
```

So you can call it like so:

```ts
evaluate({
  // main config here...
}, {
  maxConcurrency: 2,
  repeat: 2,
  delay: 0,
})
```

I've updated the node-package example to show this and will also update the docs to be clearer on this point.  To your original question, I think that there should be a way to disable the cache in this function call besides using the environment variable.
