### ISSUE TITLE
Login page in the dashboard

### ISSUE THREAD

**Issue by dmockingbird551** [promptfoo/promptfoo#1328]
**Is your feature request related to a problem? Please describe.**
Basically if we host this as a service, then we need authentication and authorization feature

**Describe the solution you'd like**
A login page with authentication. Resource authorization based on groups/ldap etc

**Describe alternatives you've considered**

**Additional context**

**Comment by mldangelo** [comment]
Thanks for the suggestion, @dmockingbird551! We now have a managed version of Promptfoo that includes login pages, authentication, and private sharing. If you're interested in a trial or want more information, feel free to get in touch with us here: https://www.promptfoo.dev/contact/.

If you prefer to self-host, there are many options for securing your instance using OAuth2 Proxy, Authelia, Keycloak, or Nginx with basic auth.

Let me know if you have any other questions!
