### ISSUE TITLE
Missing deployment docs

### ISSUE THREAD

**Issue by rishimalhotra2** [promptfoo/promptfoo#1329]
are there any docs i can follow to deploy promptfoo to the cloud (specifically azure would be nice)? if not, is there a way i can get `promptfoo share` to work with my custom domain for security purposes? I couldn't find docs for this anywhere.

**Comment by typpo** [comment]
Hi Rishi, have you reviewed the self-hosting docs?  They'll probably be
helpful here https://www.promptfoo.dev/docs/usage/self-hosting/
