### ISSUE TITLE
Req: Allow specifying typescript functions that return prompts

### ISSUE THREAD

**Issue by IanCal** [promptfoo/promptfoo#134]
The templating works nicely up until prompts get more complicated. Currently I'm constructing the prompt and history of messages in code, where there's stages of extracting data from objects and encoding them in various ways. This doesn't play so nicely with (e.g. put a json encoded string inside  a). Even long multi-line prompts are awkward in a json file with no newlines.

If prompts could (as well as being a file or list of files) include functions that take as an argument the named variables and return a string, I think that could more neatly integrate with existing typescript projects.

This could probably fit in the yaml and be callable from the cli, but a first pass could be to add this functionality to evaluate - so it's available within the node package. Prompts could have a renderer on them which defaults to renderPrompt if not defined.

Would you be interested in this being added? I think the change could be relatively small for the node package change, I'm less sure of dynamic imports for adding it to the yaml. Perhaps it would work more easily for js config.

**Comment by typpo** [comment]
Hi @IanCal,

I see what you're saying.  Something similar is supported by [custom providers](https://github.com/promptfoo/promptfoo/blob/main/examples/node-package/index.js#L6-L14), but this functionality doesn't extend to the prompts themselves.

I'm definitely open to adding this support for prompts as well.
