### ISSUE TITLE
Possible to reuse test assertions from the __expected column of a Google Sheet?

### ISSUE THREAD

**Issue by kad3nce** [promptfoo/promptfoo#1377]
I'm trying to re-use a complex `is-json` assertion from a Google Sheets-supplied test list. Re-using the assertion works properly when directly referencing it from the yaml config, but when I put the same string in the Google Sheets __expected column, it appears to be evaluated as an `equals` against the literal string. Is reusing assertions from external test files just not supported? I imagine as an alternative approach I could make it work with the `defaultTest` feature instead in this particular case…

<img width="1500" alt="image" src="https://github.com/user-attachments/assets/47a1b6c1-3914-4069-b031-4f0aa2d1c11b">
<img width="283" alt="image" src="https://github.com/user-attachments/assets/aea9b210-985a-4659-983a-fec02883f97d">

**Comment by typpo** [comment]
Unfortunately not - `$ref` is a feature of json schema, so it's not supported in Google Sheets which is a non-json/non-yaml format.

**Comment by kad3nce** [comment]
Got it. Thanks for the quick reply. I'll go with the `defaultTest` approach for now.

p.s. Promptfoo is a great project—it'll have a big impact on our ability to ship reliable prompts. Thanks for making and sharing and supporting it! 🙏🏻
