### ISSUE TITLE
Allow disabling Nunjucks

### ISSUE THREAD

**Issue by MatanYadaev** [promptfoo/promptfoo#1405]

**Comment by typpo** [comment]
Good news! This is already possible by setting the environment
variable PROMPTFOO_DISABLE_TEMPLATING=1

**Comment by MatanYadaev** [comment]
@typpo brilliant, thanks!

**Comment by MatanYadaev** [comment]
@typpo Disabling Nunjucks causes `llm-rubric` to fail. I'm not using templating in my assertion. Is that a bug?
![CleanShot 2024-08-10 at 12 42 40](https://github.com/user-attachments/assets/a4876161-1fb6-4f3a-8c8c-c106319ed7a6)

**Comment by typpo** [comment]
llm-rubric itself is a nunjucks template. May I ask why you want to disable
templating? That could help for suggesting alternatives.

**Comment by MatanYadaev** [comment]
I run an evaluation against tens of websites content (HTML), there are plenty of websites that probably using Angular.js and have `{{variable}}` in their HTML, and it causes the evaluation to crash because it doesn't find the variable in the context, obviously.
Currently I fixed by removing these brackets from the HTML(`html.replaceAll(/({{|}}/g, '')`), but ideally, I wouldn't like to run Nunjucks at all as I'm using Promptfoo in Node.js and I can run expressions in the code instead.

**Comment by mldangelo** [comment]
Hi @MatanYadaev, We’ve just released [0.85.0](https://github.com/promptfoo/promptfoo/releases/tag/0.85.0), which includes changes to how Nunjucks templating is handled only in the grader context (overriding the disable option just for those cases).  Please give it a try and let us know if this resolves the issue you're facing. If you encounter any further problems, feel free to report back!
