### ISSUE TITLE
Document why OPENAI_API_KEY in getting started

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#141]
I am looking into adopting `promptfoo`, and in the getting started step 3, randomly it asks for an OpenAI API key.

https://promptfoo.dev/docs/getting-started

Why is the OpenAI API key needed?  Can we document this (or add a link to the explanation) into the Getting Started instructions?

---

Is there some way we can have the "getting started" instructions not require OpenAI being set up?

**Comment by typpo** [comment]
Yes, if you aren't using GPT then you don't need to set your OpenAI API key!  `promptfoo init` creates a config that uses GPT by default, hence its inclusion in Getting Started.

Also worth noting that if you use any model-graded assert, you will have to [override the LLM grader](https://promptfoo.dev/docs/configuration/expected-outputs#overriding-the-llm-grader) (and potentially the rubric prompt) to select a model other than GPT.

**Comment by jamesbraza** [comment]
Thanks, I can contribute a docs PR for this shortly

**Comment by typpo** [comment]
I was in the docs anyway so I made an edit - feel free to add further clarification if you see a need :)

**Comment by jamesbraza** [comment]
Just to confirm, is the default Getting Started supposed to use OpenAI's chat endpoint or completion endpoint?

**Comment by typpo** [comment]
It uses OpenAI's chat endpoint by default.

**Comment by jamesbraza** [comment]
Thanks, I opened https://github.com/promptfoo/promptfoo-docs/pull/6 to upstream my learnings, thank you!
