### ISSUE TITLE
Allow to configure Ajv

### ISSUE THREAD

**Issue by MatanYadaev** [promptfoo/promptfoo#1414]
AJV is used in the `is-json` assertion: https://github.com/promptfoo/promptfoo/blob/35a33c4a86f5bad01b1427d1fcae7e08762b1df8/src/assertions.ts#L69

AJV defaults are strict, and because no config is passed to it, the created instance is strict.

The issue I face is with passing an `example` property to the JSON schema. The `example` property isn't mentioned in the JSON Schema spec, and therefore, when AJV sees it, it throws an error on strict mode.

It can be resolved by making AJV not strict (`new Ajv({strict: false})`) or by setting allowed keywords (`new Ajv({keywords: ['example']})`).

Being able to set a default Ajv configuration, or using an instance that I set, could help me resolve this issue.

![CleanShot 2024-08-12 at 00 30 19@2x](https://github.com/user-attachments/assets/a4808ecd-bad0-42b3-a6ae-3457b93be380)

**Comment by mldangelo** [comment]
@MatanYadaev https://github.com/promptfoo/promptfoo/pull/1415 should solve your issue. Let me know if it looks good to you.

**Comment by MatanYadaev** [comment]
@mldangelo Thanks, it works well!
Although the ideal solution IMO would be to being able to pass my own instance of AJV, because there are tons of configurations and plugins, but your PR solves my issue so it's great. :)
