### ISSUE TITLE
Question: difference between localai:chat and localai:completion

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#142]
What is the difference between `localai:chat` and `localai:completion`?  Coming from the `--providers` table here: https://promptfoo.dev/docs/usage/command-line

Also, how do I use the [Llama.cpp](https://promptfoo.dev/docs/providers/llama.cpp) provider?  `promptfoo eval --providers llama:chat` isn't triggering properly, what is the desired format?

I will gladly contribute the answers to the docs.

**Comment by typpo** [comment]
`localai:chat` will invoke models on the [LocalAI chat completion endpoint](https://localai.io/features/text-generation/#chat-completions), whereas `localai:completion` will invoke models on the [LocalAI completion endpoint](https://localai.io/features/text-generation/#completions)

`llama` doesn't make a distinct between chat and completion, so you should be able to just specify `llama` (I don't think llama.cpp serves different models at the same time)

Let me know if you have any other questions!

**Comment by jamesbraza** [comment]
Running `promptfoo eval --providers llama` I am getting:

```
API call error: Error: Request failed after 4 retries: request to http://localhost:8080/completion failed, reason: connect ECONNREFUSED ::1:8080
```

So it looks like it falls back to `completion` endpoint when you say `--providers llama`.  Going to `http://localhost:8080/docs`:

![image](https://github.com/promptfoo/promptfoo/assets/8990777/78a4f21b-4481-41db-8e64-1e8bcacc26fd)

How can I connect the final dot here?  How do I pass my model path to `promptfoo`?

**Comment by typpo** [comment]
The llama.cpp is built for the server that is part of the original llama.cpp project: https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md

It looks like the llama.cpp python API you're using more or less conforms with the OpenAI/LocalAI APIs - I would try using one of those providers instead.

**Comment by jamesbraza** [comment]
Appreciate your support and answering, I successfully adopted `promptfoo` via Ollama yesterday! 🥳 

I am still trying to get `llama-cpp-python` working, and if I do I will contribute an example to `examples/`.  As this is outside the scope of this issue, I will close it out.  Thanks again!
