### ISSUE TITLE
Request: example for Llama.cpp

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#143]
I am having a tough time figuring out how to use the [Llama.cpp provider](https://promptfoo.dev/docs/providers/llama.cpp) with [`llama-cpp-python[server]`](https://github.com/abetlen/llama-cpp-python).  It looks like none of the examples in https://github.com/promptfoo/promptfoo/tree/main/examples are for the Llama.cpp provider.

I am able to use `llama-cpp-python[server]` to run the server at port 8080, but I can't figure out how to set up the promptfoo provider for it.

It would be nice to provide a simple example for Llama.cpp that has a few configuration options provided (e.g. how to ultimately populate `config` of type `LlamaCompletionOptions`).

Bonus points: example with `llama-cpp-python[server]` too.

**Comment by mldangelo** [comment]
Deployed in [0.69.1](https://github.com/promptfoo/promptfoo/releases/tag/0.69.1). See https://github.com/promptfoo/promptfoo/tree/main/examples/llama-cpp

Thanks @jamesbraza!
