### ISSUE TITLE
Using params as part of a Python Provider

### ISSUE THREAD

**Issue by gibbster** [promptfoo/promptfoo#1492]
**Is your feature request related to a problem? Please describe.**
I'm using a python provider, and trying to reuse a library defined elsewhere in my code. The library signature includes the raw prompt template, the parameters, etc. I've gotten this to work by defining the "prompt" in my promptfooconfig.yaml as the raw template and also passing in the variables that I'm using in my test cases.

The issue is that the python provider is using the prompt as the cache key, and not the params. Since my "prompt" is actually my prompt template, it's not caching different parameters in different keys, which is causing incorrect cache hits.

**Describe the solution you'd like**
Add a hash of the params to be added to the cache key for the python provider

**Describe alternatives you've considered**
Another option is to expose the cache functionality directly and leave it to the implementation of the python provider to specify a cache key.

**Additional context**
None

**Comment by typpo** [comment]
Thanks for the report! #1493 should fix

As a temporary workaround, you can run `promptfoo eval` with `--no-cache`
