### ISSUE TITLE
Files Still Not Loaded for Scenarios and Tests

### ISSUE THREAD

**Issue by mrafnadeem-apimatic** [promptfoo/promptfoo#1501]
The issue that was logged in #1430 has still not been fixed. Even in v0.80.1.

@mldangelo I added a comment in that issue after the issue was closed.

**Comment by mldangelo** [comment]
Hey @mrafnadeem-apimatic,

I’m really sorry that this issue has been a persistent pain. I’ve pushed a fix in [PR #331](https://github.com/promptfoo/promptfoo/pull/331), and it’s now released!

When you have a moment, please give the latest version a spin and let me know if it does the trick. I really appreciate you bringing this up again—your feedback helps make the project better for everyone.

Thanks a ton for your patience and for being part of the community!

**Comment by mrafnadeem-apimatic** [comment]
Hi @mldangelo, thanks a bunch for putting in the time to fix these issues. Tests and scenarios are both loading fine from external files. 

I have just one comment based on my testing: The docs should contain examples of how external scenario or tests' files should be referenced. For example, I assumed it would load if I used `scenario.yaml` as a reference but actually I had to use `file://scenario.yaml'

**Comment by mldangelo** [comment]
Hi @mrafnadeem-apimatic,

Thank you for your patience and for testing the fix. I’m glad to hear that the tests and scenarios are now loading properly from external files!

I’ve also updated the documentation to clarify how external scenario or test files should be referenced—using file://—with this commit: [ddcc6e5](https://github.com/promptfoo/promptfoo/commit/ddcc6e59bc55e5ef9b9558ee1b0b01120cacc481). Your feedback was incredibly helpful in improving the project.

If you encounter any further issues or have suggestions, please don’t hesitate to reach out again. Thanks for being an active part of the community and helping us improve promptfoo for everyone!
