### ISSUE TITLE
Can you access promptfoo's database in terms of previous prompts and assertions ?

### ISSUE THREAD

**Issue by SysOverdrive** [promptfoo/promptfoo#1509]
This is just a curiosity :)

**Comment by typpo** [comment]
Yes!  It's a sqlite database located at `~/.promptfoo/promptfoo.db` by default.  You can use any sqlite client or explorer to interact with the database.

**Comment by mldangelo** [comment]
Hi @SysOverdrive,

Great question! You can check out more details on the database structure at [this link](https://www.promptfoo.dev/docs/contributing/#main-tables).

Additionally, from the promptfoo directory (cd promptfoo), you can run npx drizzle-kit studio to interact with the database using drizzle's built in interface.

Let us know if you have any more questions or if there's anything else you'd like to explore!
