### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'indexOf') appearing randomly when trying to generate test dataset

### ISSUE THREAD

**Issue by mpasternak** [promptfoo/promptfoo#1543]
**Describe the bug**
TypeError while trying to generate dataset. 

I have tried various different backends (Mistral-Large, GPT4-mini, Claude 3.5). The error appears randomly. Perhaps it has something to do with the way promptfoo handles empty responses -- perhaps it does not retry them when generating test datasets? No idea. 

If anybody is willing to assist me with this bug, I think I could try to work something out. I'm not a pro JS dev...

**To Reproduce**

```
[promptfoo-based-on-docs] npx promptfoo@latest generate dataset -w                                                                                                                          Cache is disabled.
 ██████████████████░░░░░░░░░░░░░░░░░░░░░░ 43% | ETA: 11s | 7/16/Users/mpasternak/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/util/index.js:893
    let openBracket = str.indexOf('{');
                          ^

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at extractJsonObjects (/Users/mpasternak/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/util/index.js:893:27)
    at synthesize (/Users/mpasternak/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/testCases.js:327:70)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doGenerateDataset (/Users/mpasternak/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/commands/generate/dataset.js:63:21)

Node.js v18.19.1
```

**Comment by mldangelo** [comment]
Hi @mpasternak,

Thank you for reporting this issue. For some reason (possibly related to your existing test cases or prompts) the models you tried are not outputting JSON. I just opened PR #1544 to attempt to address your problem. If you can, please try to check out and run the branch. And to help me investigate further, could you please provide

1. Your promptfoo configuration file (with sensitive information redacted)
2. The version of promptfoo you're using (`npx promptfoo --version`)
3. Any specific prompt or configuration that consistently reproduces the issue.

Thank you for your patience and for reporting an issue!

**Comment by mldangelo** [comment]
Hi @mpasternak,

I believe this issue has been addressed in the recent updates. I'll go ahead and close this for now. However, if the issue persists, please feel free to reopen it, and I'll look at it again. 

Thanks again for reporting it!
