### ISSUE TITLE
Use the api from the browser

### ISSUE THREAD

**Issue by synw** [promptfoo/promptfoo#157]
I would like to use the api from a browser frontend. I tried to use the node-package example in the browser and got an error: 

> ReferenceError: global is not defined

I guess this is because it is meant to be used in aNode env. Would it be possible to have a browser compatibility for this package?

**Comment by typpo** [comment]
promptfoo is not bundled for the browser and unfortunately relies on node primitives and the filesystem for things like custom functions and caching.  So this is unlikely to happen soon :(
