### ISSUE TITLE
Absence of AZURE_OPENAI_API_HOST in AZURE provider

### ISSUE THREAD

**Issue by AmineDjeghri** [promptfoo/promptfoo#1573]
**Is your feature request related to a problem? Please describe.**

When I try to use the AZURE_OPENAI_API_HOST environment variable, it doesn't seem to work.  Additionally, this environment variable isn't mentioned in the documentation,.

**Comment by mldangelo** [comment]
Hey @AmineDjeghri, thanks for flagging this! Our docs were missing some key info about the Azure environment variables - I just pushed an update to fix this. Check out [this](https://github.com/promptfoo/promptfoo/commit/535bc61d93408653a658451b5c9742984feb9ec0) commit. I added a new section on environment variables, including `AZURE_OPENAI_API_HOST`, `AZURE_OPENAI_API_BASE_URL`, and `AZURE_OPENAI_BASE_URL`. It should clear things up about which ones you need and in what order they're used.

You can see the updated docs [here](https://www.promptfoo.dev/docs/providers/azure/). Give it a look and let me know if it helps or if anything's still unclear. We're always looking to improve our docs, so any feedback is welcome.

If you're still having trouble after checking the new docs - we can hop on a call and figure it out together. Always happy to help! Thanks again for bringing this up. It's helpful feedback like this that makes promptfoo better for everyone.

**Comment by AmineDjeghri** [comment]
hello,
i just tested it and it works.

Thank you for your quick updates
