### ISSUE TITLE
Multilingual Redteam Strategy only uses OpenAI as a provider when generating translations 

### ISSUE THREAD

**Issue by Marsh61** [promptfoo/promptfoo#1584]
**Description**
The multilingual redteam strategy will never use a custom provided provider for generations and translations. 

**To Reproduce**
1. Run promptfoo init and choose a multilingual strategy 
2. Modify the promptfooconfig.yaml file to host your own redteam provider 
3. Run export PROMPTFOO_DISABLE_REDTEAM_REMOTE_GENERATION=true 
4. promptfoo redteam generate

**Expected behavior**
The multilingual strategy should use the red team provider to generate its translations

- Promptfoo version: 0.83.2

**Additional context**
The source of the bug is contained in `src/redteam/strategies/multilingual.ts` in the `translate` function.

```typescript
export async function translate(text: string, lang: string): Promise<string> {
  const redteamProvider = new OpenAiChatCompletionProvider(ATTACKER_MODEL, {
    config: {
      temperature: TEMPERATURE,
      response_format: { type: 'json_object' },
    },
  });

  const result = await redteamProvider.callApi(
    dedent`Translate the <Text> below to language '${lang}'. Respond with JSON object containing {translation: string}.
    
    <Text>
    ${text}
    </Text>`,
  );
  return (JSON.parse(result.output) as { translation: string }).translation;
}
```

**Comment by typpo** [comment]
Thanks for the report, @Marsh61.  #1586 should fix this, and will be included in the next release.
