### ISSUE TITLE
Question: Python prompt function returning object

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#159]
From the docs on custom prompt functions: https://promptfoo.dev/docs/configuration/parameters#prompt-functions

> The function should return a string or an object that represents the prompt.

Can you elaborate on what was meant by "object"?  Like what types or behaviors should be present in a non-`str` object?

**Comment by typpo** [comment]
Hi James!  Technically it will take any Javascript object and send it to whichever API you're using, assuming the provider supports this.

In practice, the main reason to use this is to return a chat-style object like:

```ts
[
    {
      role: 'system',
      content: `You're an angry pirate. Be concise and stay in character.`,
    },
    {
      role: 'user',
      content: `Tell me about ${vars.topic}`,
    },
  ]
```

**Comment by jamesbraza** [comment]
Okay I follow.  So the general signature for a Python prompt function would be this, correct?

```python
def generate_prompt(context: dict[str, str | dict]) -> str | list[dict[str, str]]:
    ...
```

**Comment by typpo** [comment]
Right now yes, but it's possible for provider endpoints to add support for new formats anytime.

**Comment by jamesbraza** [comment]
Thank you!  Closing this out as resolved, appreciated.
