### ISSUE TITLE
Fail Message for icontains-all Assertion Should Mark Which String is Missing

### ISSUE THREAD

**Issue by mrafnadeem-apimatic** [promptfoo/promptfoo#1595]
**Is your feature request related to a problem? Please describe.**
I'm currently using a lot of deterministic assertions in my tests. I mostly use `icontains-all` or `contains-all` and when I have a large number of tests which fail, I have to manually check and see which string was not found in the response from the LLM.

**Describe the solution you'd like**
I would like the test results to point out exactly which strings are missing when I use something like `icontains-all` so that I don't have to manually check all the failing tests.

**Describe alternatives you've considered**
The alternative is to check the assertion manually and see exactly what string makes it fail.

**Additional context**
Used v0.82.0

**Comment by typpo** [comment]
Good suggestion!  Added in #1596

**Comment by mldangelo** [comment]
Hi @mrafnadeem-apimatic, we’ve just released [0.85.0](https://github.com/promptfoo/promptfoo/releases/tag/0.85.0), which includes improvements for icontains-all and contains-all error messages, now pointing out exactly which string is missing in the test results. Let us know if you run into any issues or have further feedback. Thanks for the great suggestion!

**Comment by mrafnadeem-apimatic** [comment]
Hey @typpo and @mldangelo, thanks for this release. You guys are life savers. Keep up the great work.
