### ISSUE TITLE
feat: Vitest Integration ?

### ISSUE THREAD

**Issue by MentalGear** [promptfoo/promptfoo#16]
Since we have Jest and Mocha, it would be to consider to have a [Vitest](https://vitest.dev/) integration as well.

**Comment by typpo** [comment]
Going to treat this one as low priority, since we have instructions for jest and vitest has a jest-compatible api

**Comment by mldangelo** [comment]
Deployed in [0.69.1](https://github.com/promptfoo/promptfoo/releases/tag/0.69.1). See https://github.com/promptfoo/promptfoo/tree/main/examples/jest-integration 

Thanks @MentalGear!
