### ISSUE TITLE
Get "ERR_UNKNOWN_ENCODING" while import some modules in python script used as assertions

### ISSUE THREAD

**Issue by kevinyhl** [promptfoo/promptfoo#1604]
**Describe the bug**
When I use External.py as assertion and import the module below in my script:

> from evaluate import EvaluationModule

It will return the error message:
<img width="957" alt="image" src="https://github.com/user-attachments/assets/dcc3d4f0-4dd1-492a-9ef9-637f9f2168de">

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

1. Import the module in any External.py 
<img width="1090" alt="image" src="https://github.com/user-attachments/assets/48f22247-80e1-42d8-a424-ee6d04d6d286">

2. Run evaluation with command "npx promptfoo@latest eval"
<img width="981" alt="image" src="https://github.com/user-attachments/assets/aeedc7b9-8573-436d-b2f0-a4d0988d62e3">

**Expected behavior**
I expect it should return the evaluation without this error

**System information (please complete the following information):**
- evaluate module version:  <img width="254" alt="image" src="https://github.com/user-attachments/assets/d0e15e95-aa88-4293-b762-2e3ad602e11d">
- Promptfoo version: 0.81.3

**Additional context**
- I try to use some old versions of Promptfoo like 0.70.0 or 0.61.0 and they will return the error, neither.
- I try to follow the error message and edit the source code in the index.js, it could work without return the error. I'm not sure if the error occurs more than once in the loop in the source code L:66 so that it would return the error even though it has @ts-ignore in L:55.
- Original Code:
<img width="639" alt="image" src="https://github.com/user-attachments/assets/a7cb2364-5853-4892-909c-b6bea37ce442">

- After Editing the Code:
<img width="673" alt="image" src="https://github.com/user-attachments/assets/2e6cc9f8-e57e-46f4-b0a1-8a16135630e4">

**Comment by kevinyhl** [comment]
After I try to downgrade the node.js version from v22.7.0 to v21.0.0, the encoding error won't occur anymore.

**Comment by mldangelo** [comment]
Hey @kevinyhl, thanks for reporting this! I believe the issue should be resolved now. If you're still experiencing the problem, feel free to reflag the issue, and I'll take another look. Appreciate your patience and contributions!
