### ISSUE TITLE
Is it possible to delete public promptfoo result?

### ISSUE THREAD

**Issue by bohyunshin** [promptfoo/promptfoo#1607]
**Is your feature request related to a problem? Please describe.**
Hi, I want to delete associated data and shareable url showing my promptfoo result after running following command

```
promptfoo share -y
```

It seems that url is something like `https://app.promptfoo.dev/eval/f:{id}`. Is it possible to delete this promptfoo result by myself ? After seeing [official docs](https://www.promptfoo.dev/docs/usage/sharing/#privacy) related to this topic, I cannot find how to delete associated data with the url.

**Describe the solution you'd like**
It will be great if there is any feature that I can delete my promptfoo result by myself.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by mldangelo** [comment]
You can find more details here: https://www.promptfoo.dev/docs/usage/sharing/. Shared results are automatically deleted after 2 weeks. If you've shared something sensitive and need it removed sooner, feel free to reach out via DM in our discord, and we can manually delete it for you.

**Comment by typpo** [comment]
This has been handled

**Comment by bohyunshin** [comment]
@mldangelo @typpo 
thank you for handling this issue so quickly!
