### ISSUE TITLE
Allow markdown input for prompts

### ISSUE THREAD

**Issue by sinedied** [promptfoo/promptfoo#1609]
**Is your feature request related to a problem? Please describe.**
Markdown is popular format used for creating prompts. Currently, it's only possible to load markdown files when giving them a txt extensions, which defeats the proper syntax highlighting in IDEs and cause issues with default prompt splitter `---`.

**Describe the solution you'd like**
Allows to load `.md` files directly, without applying prompt delimiter when loading such files.

**Describe alternatives you've considered**
Using .txt files and overriding default prompt delimiter.

**Comment by mldangelo** [comment]
Hi @sinedied, I merged a PR implementing support for markdown prompts, and we’ll ship it in a release on Monday. Thanks again for the great suggestion. Please feel free to share any more feedback or ideas!

**Comment by sinedied** [comment]
Wow, thanks for the quick turnaround I'll right away!

**Comment by mldangelo** [comment]
Hi @sinedied, we’ve just released [0.85.1](https://github.com/promptfoo/promptfoo/releases/tag/0.85.1), which includes markdown support for prompts. Let me know if you run into any issues or have further feedback. Thanks for the great suggestion!
