### ISSUE TITLE
What is default for `--delay`?

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#161]
A request would be to document the default for `--delay`, and that it's an `int`. I think from [here](https://github.com/promptfoo/promptfoo/blob/da8c07643766e68dcc3744103c9225eb16ea3ee1/src/main.ts#L378) it's default is `0`.

I will gladly contribute this, just wanting to confirm the default delay is 0 ms.

**Comment by jamesbraza** [comment]
While I am at it, let's document `--max-concurrency`'s default, which I believe is an `int` with default of 4?  If you can also confirm this

**Comment by typpo** [comment]
Yes, both are correct!

**Comment by jamesbraza** [comment]
Would you rather:

- Just add the default to the string message (how it's done for `--config`)
- Update the default into the source for `option()` (how it's done for `--table-cell-max-length`)

**Comment by typpo** [comment]
Yeah, it is a bit inconsistent right now.  Let's go with the `option` when possible.  I've pushed 82d8f5f52ba7d86221bdacf3b081da098d40c846 to address max concurrency, delay, and repeat.

**Comment by jamesbraza** [comment]
Sounds good, thank you!
