### ISSUE TITLE
Please suport Mistral Nemo

### ISSUE THREAD

**Issue by mpasternak** [promptfoo/promptfoo#1610]
**Is your feature request related to a problem? Please describe.**
Cannot use open-mistral-nemo with promptfoo

**Describe the solution you'd like**
Id like  to be able to add open-mistral-nemo to my config file

**Describe alternatives you've considered**
No alternatives. Devs must help :-P

**Additional context**
https://docs.mistral.ai/getting-started/models/

**Comment by mldangelo** [comment]
Hi @mpasternak, Thanks for bringing this up! We’ve just released [0.85.0](https://github.com/promptfoo/promptfoo/releases/tag/0.85.0), which includes support for Mistral Nemo. You should now be able to add it to your promptfooconfig files. Feel free to check it out and let us know if you encounter any further issues. We really appreciate your feedback!

**Comment by mpasternak** [comment]
You guys are great. 

Do you realize, that I'm using promptfoo in a way that has probably not been thought of by the creators of it? Would you be interested in a short call?

**Comment by mldangelo** [comment]
@mpasternak Awesome! We'd love to hear more. Feel free to book a time on our calendar [here](https://cal.com/team/promptfoo/intro) and we can chat!
