### ISSUE TITLE
Errors when hitting rate limit when using Azure OpenAI

### ISSUE THREAD

**Issue by sinedied** [promptfoo/promptfoo#1612]
**Describe the bug**
When using model graded metrics such as `llm-rubric` with Azure OpenAI provider, when you hit the model rate limit all assertions fails with errors instead of waiting and retrying.

**To Reproduce**

1. Create a test case using Azure OpenAI provider for assertions
2. Add many assertions using `llm-rubric`
3. Run the test on multiple models or use high repeat like `--repeat 20`

**Expected behavior**
No error thrown, but model should wait until the end of rate limit and retry.

**Screenshots**
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/9acfed30-c910-4aae-9317-fcd30ff77ce2">

**System information (please complete the following information):**

- Promptfoo version: 0.84.1

**Additional context**
N/A

**Comment by mldangelo** [comment]
Hi @sinedied,

Thanks for reporting this, and I apologize for the inconvenience. I’ll look into:

1. Whether we’re respecting Azure's rate limit headers.
2. Adding support for caching on repeats.

In the meantime, I recommend rerunning the eval with lower concurrency (-j 1) or adding a delay (--delay) to avoid hitting the rate limit. Another option is to implement a custom provider as a JS or Python file that supports caching or custom retry logic for your use case.

Let me know if you have any further questions! I’ll tag you in related PRs, though implementing new features may take some time.

**Comment by sinedied** [comment]
Thanks! Let me know if you need help with the PR

**Comment by sinedied** [comment]
@typpo Looking into the code, I've found a few issues:
- https://github.com/promptfoo/promptfoo/blob/main/src/fetch.ts#L50 : Azure uses 2 different headers for rate limiting, `X-Ratelimit-Remaining-Requests` and `X-Ratelimit-Remaining-Tokens`
- https://github.com/promptfoo/promptfoo/blob/main/src/fetch.ts#L54 : When rate limited, the `X-Ratelimit-Reset-Tokens` is set, instead of the one here. Alternatively, the header `Retry-After` can be used.

I've open a PR to improve these behaviors, as custom headers may vary depending of the provider.

**Comment by sinedied** [comment]
PR sent 😉 

While adding unit tests, I also found out that the rate limiting logic was never called, so I fixed it.

**Comment by sinedied** [comment]
Resolved by #1633
