### ISSUE TITLE
Can web crawlers find `promptfoo share` results?

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#162]
I realized `promptfoo share` is creating a public URL.  Just two questions:
- Can web crawlers find the `promptfoo share` results?
- Per [here](https://promptfoo.dev/docs/usage/sharing/#privacy), it lasts for 2 weeks.  Can that be shortened/configured?

**Comment by typpo** [comment]
25081b04c60aef6d16a6460d77fed167bf44b91a adds `noindex` to all promptfoo eval pages.  Thanks for flagging!

There isn't a way to adjust the lifetime right now.
