### ISSUE TITLE
0.85.2 breaks output formatting in view with Together.ai provider, Llama 3.1 70B

### ISSUE THREAD

**Issue by kkarski** [promptfoo/promptfoo#1622]
**Describe the bug**
After upgrading to 0.85.2, prompt outupt in view changed to this:
```
{"role":"assistant","content":"<table id=\"3\">\n  <tr>\n    <td id=\"982\"></td>\n    <td id=\"117\">Total Revenue</td>\n    <td id=\"118\">Total Expenses</td>\n    <td id=\"119\">Net Income</td>\n  <td id=\"982\">New Acquisitions</td>\n    <td id=\"351\"></td>\n  </tr>\n  <tr>\n    <td id=\"117\">Ending Balance 12/31/2023</td>\n    <td id=\"493\"></td>\n  </tr>\n  <tr>\n    <td id=\"658\">Reserve Funds</td>\n    <td id=\"219\"></td>\n  </tr>\n  <tr>\n    <td id=\"421\">Beginning Balance 1/1/2023</td>\n    <td id=\"753\"></td>\n  </tr>\n  <tr>\n    <td id=\"936\">Impairment Provisions</td>\n    <td id=\"118\"></td>\n  </tr>\n  <tr>\n    <td id=\"275\">Ending Balance 12/31/2023</td>\n    <td id=\"982\"></td>\n  </tr>\n  <tr>\n    <td id=\"467\">Net Worth</td>\n    <td id=\"542\"></td>\n  </tr>\n  <tr>\n    <td id=\"624\">Ending Balance 12/31/2023</td>\n    <td id=\"819\"></td>\n  </tr>\n  <tr>\n    <td id=\"351\">Ending Balance 12/31/2022</td>\n    <td id=\"138\">528,524,535</td>\n  </tr>\n</table>","tool_calls":[]}
```

Instead of just the unescaped content like before.

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

1. Upgrade to 0.85.2
2. Run existing prompts against Llama 3.1 70B, together.ai
3. Open output in view
4. Inspect an individual response from LLM

**Expected behavior**
I should see unescaped content of the assistant's message

**System information (please complete the following information):**
- node 22.8.0
- promptfoo 0.85.2
- Llama 3.1 70B with Together.ai provider

- Promptfoo version:
-0.85.2

**Additional context**
Interesting, after downgrading back to 0.85.1 this problem persists. Tried with OpenAI provider and it formats correctly.

**Comment by mldangelo** [comment]
Hi @kkarski, I’m going to close this issue due to inactivity. If you’re still experiencing the problem, please feel free to reopen it with additional details or a reproducible config, and we’ll be happy to help investigate further. Thank you!
