### ISSUE TITLE
Request: adding `-y`/`--yes` option to `promptfoo view`

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#163]
When running `promptfoo view`, it prompts one with y/N to open the browser at the view's URL.

The request is to add `-y`/`--yes` kwarg to skip the confirmation and auto-open the URL.

A workaround for now is `yes | promptfoo view`.

**Comment by typpo** [comment]
Implemented in #166

**Comment by jamesbraza** [comment]
Wow quick turnaround, thanks for this! 👍 🚀
