### ISSUE TITLE
`export PROMPTFOO_CACHE_ENABLED=false` not disabling cache

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#164]
Running:

```bash
> export PROMPTFOO_CACHE_ENABLED=true
> promptfoo eval
...  # Takes < 1 sec
> export PROMPTFOO_CACHE_ENABLED=false
> promptfoo eval
...  # Takes < 1 sec
> rm -r ~/.promptfoo/cache
> promptfoo eval
...  # Takes >> 1 sec
```

I think this means `export PROMPTFOO_CACHE_ENABLED=false` doesn't get respected.

**Comment by typpo** [comment]
Should be fixed with 63eebeee45bcd1266c9d09ec7a78b670cd6c3be0

**Comment by jamesbraza** [comment]
The original `Boolean(process.env.PROMPTFOO_CACHE_ENABLED)`, what was the value for `PROMPTFOO_CACHE_ENABLED` supposed to be?  I guess just `1`?

And looks like your change will work, thanks

**Comment by typpo** [comment]
Any non-empty string is truthy, so it didn't behave correctly without parsing.  Thanks for catching this!
