### ISSUE TITLE
Python assertions - Improve debugging and logging

### ISSUE THREAD

**Issue by hci2** [promptfoo/promptfoo#1642]
**Is your feature request related to a problem? Please describe.**
I am trying to use Python assertions via an external file (see https://www.promptfoo.dev/docs/configuration/expected-outputs/python/#external-py) but it is a black box and there seems to be no way to `print` or `logger` statements for progress related stuff like it seems to work for Python providers (https://www.promptfoo.dev/docs/providers/python/#viewing-python-output).

When I try to use it the same way via setting env `LOG_LEVEL=debug`, I only see the Typescript debug log statements before and after (see https://github.com/promptfoo/promptfoo/blob/a852acdadab32cbd0b1fd63c684450cec0aef06b/src/python/wrapper.ts#L37-L39). 

**Describe the solution you'd like**
It would be great to have one of both solutions:
1. Better debugging capacities (I have tried similar things like those described here: https://github.com/promptfoo/promptfoo/issues/955)
2. Not erasing `print` or `log` statements

**Describe alternatives you've considered**
* Using a remote debugger like [remote-pdb](https://pypi.org/project/remote-pdb/) but that's a lot of extra effort and cumbersome

**Additional context**
* IDE: VSCode 1.92.2
* OS: MacBook (Sonoma, 14.6.1)
* Python 3.12.5
* Terminal: Integrated of IDE
* Promptfoo 0.86.1 (installed via [volta](https://volta.sh/))

![image](https://github.com/user-attachments/assets/d1577d1c-695c-40ae-b471-fed99322de63)

**Comment by hci2** [comment]
#955

**Comment by albertlieyingadrian** [comment]
Facing the same issue. Think its in progress https://github.com/promptfoo/promptfoo/issues/1705 @hci2

**Comment by albertlieyingadrian** [comment]
@hci2 I've never used remote-pdb and am interested in trying this out. Do you have a guideline on how to use that?

**Comment by mldangelo** [comment]
@albertlieyingadrian Sorry for the delay. You can npm link my branch https://github.com/promptfoo/promptfoo/compare/feat/python-logging?expand=1 

I am working on fixing the tests now and will issue a release when done.

You can also write to something other than stdout in your current python file (for example, a file, a websocket, etc.) if you want to do it on main

**Comment by hci2** [comment]
@albertlieyingadrian
No, I haven't looked into it but I just came across it through this comment https://github.com/promptfoo/promptfoo/issues/955#issuecomment-2289592449. It seems not so difficult to try out from what I see.

Awesome and thanks for your work guys. This tool is really promising and I like the YAML configuration approach compared to other toolings. 👏

**Comment by mldangelo** [comment]
Hey @hci2, thanks for your patience! We just released the fix in [0.91.2](https://github.com/promptfoo/promptfoo/releases/tag/0.91.2), which improves logging for Python assertions. You can now view the outputs by setting the --verbose flag or using LOG_LEVEL=debug. Please give it a try and let us know how it works for you. Feel free to comment or reopen the issue if you encounter any further issues.
