### ISSUE TITLE
Add Pricing Information for Azure OpenAI

### ISSUE THREAD

**Issue by AmineDjeghri** [promptfoo/promptfoo#1660]
**Is your feature request related to a problem? Please describe.**

The pricing information for Azure OpenAI is currently missing. Also, OpenAI and Azure OpenAI have the same pricing structure for the East US region. 

**Describe the solution you'd like**

Can you please add the pricing details for Azure OpenAI . Even if you include only the East US region. itwould be helpful. 

Here are the pricing pages : 
- [link to Azure OpenAI pricing](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service/) 
- [link to OpenAI pricing](https://openai.com/api/pricing/)

**Comment by mldangelo** [comment]
Hi @AmineDjeghri, we’ve just shipped [0.88.0](https://github.com/promptfoo/promptfoo/releases/tag/0.88.0), which includes the pricing information for Azure OpenAI models in East US. Thanks again for bringing this up - your feedback was really helpful! I'm going to work to automate price updates more in the near future.  Feel free to check it out and let us know if anything else comes up. Thanks again!
