### ISSUE TITLE
Referencing a function call from an external file to be reusable across prompts

### ISSUE THREAD

**Issue by albertlieyingadrian** [promptfoo/promptfoo#1663]
Is there a way to reference a tool or function call definition from an external json / yaml file for openAI?

https://github.com/promptfoo/promptfoo/blob/846993f7969a0c49926a01939835b08c44cdaf13/examples/openai-function-call/promptfooconfig.yaml#L8

Trying to move the function call schema outside of promptfooconfig.yaml

**Comment by mldangelo** [comment]
Hi @albertlieyingadrian, great question!

We supported this, but there was a bug that prevented it from working properly for the first test case. I've just pushed a fix for this in 333e61958f. I've also updated the OpenAI function call example to demonstrate how to define them externally. This will be in the next release (by Monday at the latest).

Thanks for bringing this up! Please let us know if you run into any other issues.

**Comment by mldangelo** [comment]
We just released [0.88.0](https://github.com/promptfoo/promptfoo/releases/tag/0.88.0), which includes the fix for referencing function call schemas from external files. Thanks again @albertlieyingadrian for reporting this issue! Please let us know if you run into any other bugs.
