### ISSUE TITLE
How to specify `prompt.py` in `prompfooconfig.yaml`

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#167]
I have a Python file just like https://promptfoo.dev/docs/configuration/parameters#prompt-functions called `prompt.py`.

In `promptfooconfig.yaml`, I have `prompts: [prompt.py]`.

However, this seems to be actually passing the source code as the prompt, not running the Python file to print the prompt.

How can I get `prompt.py` to run, when specified as a `prompts` source?

**Comment by typpo** [comment]
That _should_ work 🤔  What version are you using?  `promptfoo --version`

**Comment by jamesbraza** [comment]
I am using the latest release, `0.24.0`

**Comment by jamesbraza** [comment]
Just to share what I am seeing, with this `prompt.py`:

```python
import json
import sys


def generate_prompt(context: dict) -> str:
    return "Hello"


if __name__ == "__main__":
    print(generate_prompt(json.loads(sys.argv[1])))
```

This output (table has source code, not the printed stdout):

<img width="556" alt="screenshot of printed eval" src="https://github.com/promptfoo/promptfoo/assets/8990777/ca3b7dd6-ac85-4302-864c-10a544c8ebcb">

**Comment by typpo** [comment]
Oh, I see what you're saying.  The actual prompt text will vary by test case, presumably, so the column header will just have the source code itself because there isn't necessarily a generic string to represent the entire column.

**Comment by jamesbraza** [comment]
Ah okay, gotchu.  Is there some way I can show the final message being passed to the LLM, to verify it's working as intended?

**Comment by maciejbrasewicz** [comment]
I also spent some time yesterday trying to solve this problem, but I couldn't. I need to use Python files instead of txt, so it's a problem for me :/

**Comment by typpo** [comment]
@jamesbraza The final prompt should be visible by clicking on the 🔍  icon on each cell.

@maciejbrasewicz Thanks for opening the other issue.  I'll investigate there 🤔

**Comment by jamesbraza** [comment]
Thanks @typpo, I made a docs PR to document that
