### ISSUE TITLE
Request: supporting semantic linefeeds or markdown as prompt input

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#168]
I have a few prompts that are really long (500+ chars).  Dealing with that in my IDE and `prompts.txt` (without soft wrapping enabled) is a pain.  If I were to split the long line up with a single newline:

```txt
A long
long line.
```

promptfoo preserves the newline when passing it to the model.  This is a sensible behavior.

I am hoping to use newlines in a [semantic linefeed](https://rhodesmill.org/brandon/2012/one-sentence-per-line/) sense.  That way I can have a multiline prompt in `prompts.txt`, but it's passed to the model as one line.  When there's two newlines in `prompts.txt`, it'd be interpreted as one newline when passed to the model.  This works well, because the inter-prompt delimiter is `---`.

There's two ways we can support this:
- Support semantic linefeeds in `prompts.txt` with an opt-in `promptfooconfig` parameter `use-semantic-linefeeds: true`
- Support Markdown (`.md`) as an input type, and pass the _rendered` Markdown to the model
    - Aside: this would enable support of more complex text structures, than just plain text

Thank you for your consideration!

**Comment by typpo** [comment]
I think this will be hard to implement, and a bit of a niche use case.  I also think most people would expect markdown to be passed directly to the LLM (as that is very common), rather than rendered beforehand.  So, I'm going to close this unless there is further interest.
