### ISSUE TITLE
Using PROMPTFOO_LIGHTWEIGHT_RESULTS doesn't save results .json file

### ISSUE THREAD

**Issue by lone-star** [promptfoo/promptfoo#1697]
**Describe the bug**
When `PROMPTFOO_LIGHTWEIGHT_RESULTS=1`, the results aren't written to the output.

**To Reproduce**

1. Run with PROMPTFOO_LIGHTWEIGHT_RESULTS=1
2. See that the output isn't written

In the new commit here: https://github.com/promptfoo/promptfoo/commit/ecfc650b03ace4fad2d7541ea6771cb2ea0edc5f#diff-7529f5d4cc084a155324df776df361b69da340c5e2d6c8da5376d9ee1eee9049R171

We are clearing the content of the config object, and below is where the `outputPath` is read.

**Comment by typpo** [comment]
Thanks for the report, we'll get a fix in

**Comment by typpo** [comment]
#1737 should fix

**Comment by mldangelo** [comment]
Hi @lone-star, We’ve shipped a fix for this issue. Can you try [0.90.0](https://github.com/promptfoo/promptfoo/releases/tag/0.90.0) and try again with `PROMPTFOO_LIGHTWEIGHT_RESULTS=1`? 

Let us know if you encounter any further issues or have additional feedback. Thanks for your help in improve promptfoo!
