### ISSUE TITLE
[Eval grouping] Is it possible organize the eval files into a folder instead of dumping them all in the root folder?

### ISSUE THREAD

**Issue by albertlieyingadrian** [promptfoo/promptfoo#1699]

**Comment by albertlieyingadrian** [comment]
@mldangelo Do you by chance know if this is possible?

**Comment by mldangelo** [comment]
@albertlieyingadrian do you mean promptfoo configs or output files? It should be possible - book time on my calendar and we can look at it together https://cal.com/michael-dangelo/30min or fix it together.

**Comment by albertlieyingadrian** [comment]
actually I figured it out. Will close this. Thanks!
