### ISSUE TITLE
Python error at promptfoo eval

### ISSUE THREAD

**Issue by BrenosmMaia** [promptfoo/promptfoo#1702]
**Describe the bug**
I successfully runned `promptfoo init` , however,  `promptfoo eval` gives the error

```
node:events:497
      throw er; // Unhandled 'error' event
      ^
      
Error: spawn python EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on PythonShell instance at:
    at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v20.17.0/lib/node_modules/promptfoo/node_modules/python-shell/index.js:180:18)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn python',
  path: 'python',
  spawnargs: [
    '/home/user/.nvm/versions/node/v20.17.0/lib/node_modules/promptfoo/dist/src/python/wrapper.py',
    '/my_code_path/evaluation/prompts.py',
    'prd_prompt',
    '/tmp/promptfoo-python-input-json-1726615914161-40caad32f06a3.json',
    '/tmp/promptfoo-python-output-json-1726615914161-a9d46bdb5ba16.json'
  ]
}
Node.js v20.17.0
```

**System information (please complete the following information):**

- node v20.17.0
- npm 10.8.2
- Ubuntu 22.04

- Promptfoo version: 0.89.0

**Comment by mldangelo** [comment]
Hi @BrenosmMaia, thanks for reporting this issue! We shipped updates to python executable discovery today so this is probably my fault. It looks like the error you're encountering (`spawn python EACCES`) is related to permissions or Python not being available in your system's `PATH`.

Could you please try the following:

1. **Check if Python is in your PATH**: Run `python --version` or `python3 --version` in your terminal to confirm that Python is installed and accessible.
   
2. **Set the Python path manually**: If Python is installed but not accessible, try setting the `PROMPTFOO_PYTHON` environment variable to the path of your Python installation. You can do this by running:

   ```bash
   export PROMPTFOO_PYTHON=/path/to/your/python
   ```

   Replace `/path/to/your/python` with the actual path to your Python executable. You can find this path by running `which python` or `which python3`.

Let me know if this resolves the issue, and feel free to share any additional details if the error persists.

**Comment by BrenosmMaia** [comment]
Hello @mldangelo, thanks for the answer.

I did the following, and it worked!

```
$ python3 --version
Python 3.10.12

$ which python3
/usr/bin/python3

$ export PROMPTFOO_PYTHON=/usr/bin/python3
```

**Comment by mldangelo** [comment]
Hi @BrenosmMaia, I'm glad to hear that setting the `PROMPTFOO_PYTHON` environment variable resolved the issue!  Since it looks like the problem has been addressed, I'll go ahead and close this issue. If you run into any more issues or have further questions, feel free to open a new one. Thanks again for your report and for helping improve promptfoo!
