### ISSUE TITLE
Add support for `bedrock:ai21.jamba-*:0` models

### ISSUE THREAD

**Issue by thomasgtaylor** [promptfoo/promptfoo#1751]
May we have support added for AI21 Jambda 1.5 models in the Bedrock provider? Looking to test these without needing to build a custom provider.

Specific model ids:

- `ai21.jamba-1-5-large-v1:0`
- `ai21.jamba-1-5-mini-v1:0`

Thank you!

**Comment by mldangelo** [comment]
Hi @thomasgtaylor, I just shipped support for AI21 Jamba 1.5 models in the Bedrock provider in [0.90.0](https://github.com/promptfoo/promptfoo/releases/tag/0.90.0).  Let me know if you encounter any issues or have more feedback. Appreciate your help in making the project better!

**Comment by thomasgtaylor** [comment]
This is awesome! Thank you Michael!
