### ISSUE TITLE
Configuration as TypeScript

### ISSUE THREAD

**Issue by moltar** [promptfoo/promptfoo#1760]
**Is your feature request related to a problem? Please describe.**

YAML is ... not great (politely speaking). 

**Describe the solution you'd like**

Because we already have types for the test file, wouldn't it be great to write the test files in TS directly?

**Describe alternatives you've considered**

Writing my own generator from TS -> YAML.

**Additional context**

Can use Liftoff to support _any_ config file type: https://www.npmjs.com/package/liftoff

Tools like gulp and plopjs use it

And many other projects: https://www.npmjs.com/browse/depended/liftoff

**Comment by mldangelo** [comment]
Hi @moltar, thanks for your suggestion! We actually support TypeScript configurations already. You can check out a basic example here: [TypeScript Config Example](https://github.com/promptfoo/promptfoo/tree/main/examples/ts-config). If you have any specific improvements or additional features in mind, I’d love to hear your thoughts. Let us know if you have any questions!

**Comment by moltar** [comment]
Perfect! Works great. Thank you!

Here's a [`tsx`](https://github.com/privatenumber/tsx) based example too:

```
NODE_OPTIONS="--import tsx" promptfoo eval -c src/promptfooconfig.ts              
```

**Comment by typpo** [comment]
Thanks for the link to liftoff, looks pretty cool
