### ISSUE TITLE
Provider prompts filter not used when running evaluate via Node package

### ISSUE THREAD

**Issue by baransu** [promptfoo/promptfoo#1785]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `promptfoo@0.90.1` for the project I'm working on.

I'm running Node package and everything is great except `provider.prompts` filter. I have different prompts for different providers, but when running `evaluate` from TS it's not picked up. Everything works correctly when running via CLI. I dug a little bit, and it looks like `providerPromptMap` is never constructed in the `evaluate` function exposed as a Node package.

Here is the diff that solved my problem (generated by `patch-package`):

```diff
diff --git a/node_modules/promptfoo/dist/src/index.js b/node_modules/promptfoo/dist/src/index.js
index 192c8b2..24ba099 100644
--- a/node_modules/promptfoo/dist/src/index.js
+++ b/node_modules/promptfoo/dist/src/index.js
@@ -66,7 +66,7 @@ async function evaluate(testSuite, options = {}) {
             if (typeof promptInput === 'function') {
                 return {
                     raw: promptInput.toString(),
-                    label: promptInput.toString(),
+                    label: promptInput?.name ?? promptInput.toString(),
                     function: promptInput,
                 };
             }
@@ -111,8 +111,14 @@ async function evaluate(testSuite, options = {}) {
     if (options.cache === false || (options.repeat && options.repeat > 1)) {
         cache.disableCache();
     }
+
+    const parsedProviderPromptMap = prompts_1.readProviderPromptMap(testSuite, constructedTestSuite.prompts);
+
     // Run the eval!
-    const ret = await (0, evaluator_1.evaluate)(constructedTestSuite, {
+    const ret = await (0, evaluator_1.evaluate)({
+        ...constructedTestSuite,
+        providerPromptMap: parsedProviderPromptMap
+    }, {
         eventSource: 'library',
         ...options,
     });
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by mldangelo** [comment]
Thank you @baransu! We'll get a fix out for this

**Comment by mldangelo** [comment]
Hi @baransu, thanks again for raising this issue and for your detailed investigation and patch! @vsauter implemented the fix, and it has been deployed. Please pull the latest version to get the update.

Feel free to reach out if you encounter any further issues.

**Comment by baransu** [comment]
Thank you!
