### ISSUE TITLE
Question: Is there a way to separate test runs depending on a given set?

### ISSUE THREAD

**Issue by Starday2009** [promptfoo/promptfoo#1786]
Question: Is there a way to separate test runs depending on a given set?
For example, I want to run a test set daily for one dataset, and once a week for 10 datasets. How can I separate these runs if everything needs to be stored in one file - promptfooconfig.yaml?

**Comment by sklein12** [comment]
@Starday2009 I would create two config files and then you can specify which one you want to run using `-c` eg:
`promtfoo eval -c weeklyconfig.yaml`
