### ISSUE TITLE
Does 'providers' support customized LLM Model service?

### ISSUE THREAD

**Issue by ooooona** [promptfoo/promptfoo#181]
Hi team,

I'm trying to use promptfoo to test my own LLM Model for prompts, but I failed to find the example/cases or userguide how to setup `promptfooconfig.yaml`. For example, my LLM Model service provide api like https://${host}:${port}/${api}, is it possible?

Thanks so much!

**Comment by jamesbraza** [comment]
For starters, what is your LLM service API, is it custom?  Does it match one of these providers: https://promptfoo.dev/docs/providers/?

https://promptfoo.dev/docs/providers/custom-api details how to make a custom provider.

From there, check `promptfoo init` to create the initial config: https://promptfoo.dev/docs/getting-started

**Comment by typpo** [comment]
Thanks @jamesbraza!  @ooooona the Custom APIs documentation is the way to go - feel free to follow up if anything is unclear.

**Comment by ooooona** [comment]
Thanks @jamesbraza and @typpo, I want to test prompt with my own finetune Code-Llama Model, which I wrapped with my python code, providing v2 inference api like: _http://localhost:8080/v2/models/{model_name}/infer_. 
It seems that (current providers)[https://promptfoo.dev/docs/providers/] do not match my case, and I have to use custom-api? And I need to implement call my v2 inference api, like _http://localhost:8080/v2/models/{model_name}/infer_, in `callApi: (prompt: string, context: { vars: Record<string, any> }) => Promise<ProviderResult>`?

**Comment by typpo** [comment]
That is correct.  You could either use a custom API module, or if you're willing to conform to a predefined format you can use a [webhook provider](https://promptfoo.dev/docs/providers/webhook), which sends an HTTP POST request `{prompt: string}` and expects `{output: string}` in return from your server.
