### ISSUE TITLE
transformVars for input vars in python won't work?

### ISSUE THREAD

**Issue by danpe** [promptfoo/promptfoo#1859]
**Describe the bug**
Unable to get my transform_vars python function to run proparly.

**To Reproduce**

**promptfooconfig.yaml:**
```
defaultTest:
  options:
    transformVars: file://transform_vars.py
```

**transform_vars.py:**
```
def get_transform_vars(vars, context):
    print(vars)
```

**Exception:**
```
Traceback (most recent call last):
  File "/.nvm/versions/node/v18.20.3/lib/node_modules/promptfoo/dist/src/python/wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.nvm/versions/node/v18.20.3/lib/node_modules/promptfoo/dist/src/python/wrapper.py", line 24, in call_method
    method_to_call = getattr(script_module, method_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'transform_vars' has no attribute 'get_transform'. Did you mean: 'get_transform_vars'?
```

- Promptfoo version: 0.92

**Comment by MrFlounder** [comment]
Hi @danpe 

By default it looks for `get_transform` method defined in your python file. If you want to use a different method name, then you can give the transform method name like this:
`transformVars: file://transform.py:transform`

**Comment by danpe** [comment]
@MrFlounder You are actually correct, just need to update the docs then :) 
This example is wrong: https://github.com/promptfoo/promptfoo/blob/207469a6a54b3a4123c2f8418d51affe9b04d40d/site/docs/configuration/guide.md?plain=1#L716

**Comment by mldangelo** [comment]
Thanks @danpe for bringing this to our attention. We've updated the documentation to correct the function name in the `transformVars` example in https://github.com/promptfoo/promptfoo/commit/6a9ed383a7ddf801aa8dbbc36af0ee8b237faa4a. 

Please don't hesitate to report any other issues you come across or suggest improvements. Every interaction helps make promptfoo better!
