### ISSUE TITLE
Docs request: including the `prompts.txt` in Scenarios

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#186]
Can we include the `prompts.txt` used in the example [Scenario](https://promptfoo.dev/docs/configuration/scenarios)?  It seems to be relevant in understanding how Scenarios work.

I can open a PR for this, if you share what the `prompts.txt` looked like

**Comment by typpo** [comment]
Here's the full example: https://github.com/promptfoo/promptfoo/tree/main/examples/multiple-translations-scenarios

**Comment by jamesbraza** [comment]
Thank you!  Opened https://github.com/promptfoo/promptfoo-docs/pull/15 for this, closing this issue out
