### ISSUE TITLE
Make the eval result table scrollable

### ISSUE THREAD

**Issue by rhdunn** [promptfoo/promptfoo#1882]
**Is your feature request related to a problem? Please describe.**
When there are a large number of results for multiple prompts, scrolling down past the header makes it difficult to tell which prompt a result belongs to.

When there are a number of different prompts being evaluated (7+) the resulting vars and results are squished.

**Describe the solution you'd like**
Don't specify fixed widths.

Make the top header sticky (`position: sticky`) to fix it when scrolling down the page.

Make the left header sticky to fix it when scrolling down the page.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by typpo** [comment]
Done in latest version!
