### ISSUE TITLE
"You must provide at least 1 prompt"

### ISSUE THREAD

**Issue by joelcarvalhopribss** [promptfoo/promptfoo#1895]
**Describe the bug**

I compile an evaluation successfully and try to run it again, but I always get the message “You must provide at least 1 prompt” .

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

1. Run `promptfoo eval` (works well)
2. Run `promptfoo eval`

- Promptfoo version: 0.93.1

**Comment by typpo** [comment]
Wondering if you have a standalone repro?  I am not seeing this on my end.

**Comment by joelcarvalhopribss** [comment]
Hello @typpo, no. I'm using a regular folder on my C: 

Check the following image pls:
![image](https://github.com/user-attachments/assets/46313ab0-ee87-4eef-ad52-563e8edbb184)

**Comment by mldangelo** [comment]
@joelcarvalhopribss where are you running `promptfoo eval` relative to your file? Can you try to specify the path to the config with `promptfoo eval -c path/to/config.yaml` and see if that works?

**Comment by typpo** [comment]
You are missing a `-c`:

```
promptfoo eval -c test.yaml
```
