### ISSUE TITLE
`transformVars` not persisted and `storeOutputAs` not stored

### ISSUE THREAD

**Issue by strentom** [promptfoo/promptfoo#1916]
**Describe the bug**
I need to persist information between tests for threaded conversation (modifying both input and output to and from a provider). I figured the only way to do it is to use both `transformVars` and `storeOutputAs`. However, none of them work. Below I include a short reproducer.

**To Reproduce**
Just eval this (with `--verbose` to see logs):
```
description: "Send 'Hi' twice and store LLM output in myVar variable. Print myVar on each pass. On second pass it should be non-empty. But it's empty."
providers: vertex:gemini-1.5-flash
defaultTest:
  options:
    transformVars: |
      console.log("MyVar: ", vars.myVar);
      console.log("LastOutput: ", vars.lastOutput);
      
      return {
        myVar: vars.lastOutput
      };
    storeOutputAs: lastOutput
prompts: '{{ message }}{{ _conversation | reject() }}' # when _conversation is not mentioned in prompt, the tests are independent and don't share conversation (even if --max-concurrency 1)
tests:
  - vars:
      message: Hi
  - vars:
      message: Hi
  - vars:
      message: Hi
```
I use `_conversation` parameter in prompt to enforce threaded conversation to persist state. It doesn't help. Btw, one must include this parameter in the prompt! If it is mentioned only in e.g., promptRubric and not prompt, the conversation state is not persisted and individual test cases are evaluated independently.

**Expected behavior**
There are two tests in the yaml. 
1. The first test should set `lastOutput` variable via `storeOutputAs`
2. The second test should set `myVar` variable to `lastOutput` via `transformVars`
3. The third test is just to show outputs of both `lastOutput` and `myVar`, where both should be set.

However, none of the variables is set. Both are empty in every test case

**Screenshots**
This is the output with `--verbose --no-cache`:
```
..
MyVar:  undefined
LastOutput:  undefined
MyVar:  undefined
LastOutput:  undefined
MyVar:  undefined
LastOutput:  undefined
Setting concurrency to 1 because the _conversation variable is used.
..
```

**System information:**

- Promptfoo version: 0.93.3

**Comment by mldangelo** [comment]
Hi @strentom, thank you for the detailed issue and for bringing this up! `transformVars` doesn’t persist between tests because it’s primarily designed for cases like referencing and loading large files (e.g., from S3). This behavior is intentional, but I realize it could be better documented, so I’ll work on adding more clarity in the docs.

I’ll take a closer look at the `storeOutputAs` behavior today. If you want to throw some time on my calendar: https://cal.com/michael-dangelo/15min we can talk about your use case and see if there's a better way to unblock you. Thanks for your patience and for being a part of the community!

**Comment by strentom** [comment]
Thank you very much, I didn't know that `transformVars` is ephemeral by design. I managed to implement the necessary behavior by storing a conversation state in a custom provider. That way, I avoided `transformVars` and don't need to `storeOutputAs` in `defaultTest`.
