### ISSUE TITLE
--watch triggers on change, but doesn't pull changes

### ISSUE THREAD

**Issue by sbichenko** [promptfoo/promptfoo#1918]
**Describe the bug**
When using --watch, changes to promptfooconfig.yaml correctly trigger a reload, but evals are run with the initial version of the promptfooconfig.yaml that was loaded.

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

1. promptfoo init
2. promptfoo eval --watch
3. Change promptfooconfig.yaml to include "Don't " as a prefix to each prompt (so it becomes "Don't Write a concise, funny tweet about {{topic}}"
4. Wait until eval finishes
5. Old prompts are used ("Write a concise, funny tweet about {{topic}}").

**Expected behavior**
New prompts are used ("Don't Write a concise, funny tweet about {{topic}}").

**System information (please complete the following information):**

- Promptfoo version: 0.93.3

**Comment by typpo** [comment]
Thanks for flagging!  #1929 fixes this bug, which was apparently introduced a couple weeks ago.  It will be included in the next release.

**Comment by sbichenko** [comment]
Awesome, thanks! Will it also watch linked Google Sheets for changes? It would be amazing if it did, but if not, maybe a warning is in order?
