### ISSUE TITLE
--watch should also trigger for changes in prompt paths

### ISSUE THREAD

**Issue by sbichenko** [promptfoo/promptfoo#1919]
**Is your feature request related to a problem? Please describe.**
I have a project with many large prompts. The prompts are stored in separate files in different subdirectories and are pointed to in the config. When I run promptfoo eval -w, it doesn't react to changes in the prompt files, only to changes in the config.

**Describe the solution you'd like**
-w should also watch all files linked to in config. 

**Describe alternatives you've considered**
I might write my own --w functionality and use promptfoo as a NodeJS module.

**Comment by typpo** [comment]
This behavior is fixed with #1929.  Thanks!

**Comment by sbichenko** [comment]
Awesome, thanks! Will it also watch linked Google Sheets for changes? It would be amazing if it did, but if not, maybe a warning is in order?

**Comment by typpo** [comment]
Fix is released!  Unfortunately we can't watch Google Sheets yet
