### ISSUE TITLE
Request: support Ollama `num_predict` and/or `options` to `/generate`

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#192]
I am using the `similar` assertion and Ollama `/generate` (provider) and LocalAI `/embeddings` (grader), and it's working. Now it's time to really dial in the test assertions.

My assertion prompt is short (20 words) but my Ollama generated response is massive (100+ words).  I believe this is impacting my `similar` score.

Ollama has a field for this [`num_predict`](https://github.com/jmorganca/ollama/blob/v0.0.21/api/types.go#L185) that corresponds with [`n-predict` from Llama.cpp](https://github.com/ggerganov/llama.cpp/tree/master/examples/main#number-of-tokens-to-predict).  I don't see it in the current [Ollama config options](https://github.com/promptfoo/promptfoo/blob/0.24.2/src/providers/ollama.ts#L7).

You can set it via `curl` with `options`:

```bash
curl http://localhost:11434/api/generate -X POST -H "Content-Type: application/json" -d '{
         "prompt": "some prompt",
         "model": "llama2",
         "options": {
             "num_predict": 42
         }
     }'
```

Is there any way we can either:
- Add `num_predict` support to Ollama config?
- Expose `options` for a given `/generate` request?

**Comment by typpo** [comment]
Closing this out - there's an example here https://github.com/promptfoo/promptfoo/blob/main/examples/ollama-comparison/promptfooconfig.yaml#L8-L9

**Comment by jamesbraza** [comment]
Oh awesome, I will starting using this capability tomorrow! Much appreciated
