### ISSUE TITLE
Issue with Creating a Test Scenario

### ISSUE THREAD

**Issue by tttbone8122** [promptfoo/promptfoo#193]
I tried to read through the documentation, but I'm not sure how to construct the following test scenario:

Let's assume I have a long document along with a question about the document. Using "prompt1.txt," I would like to ask the model to summarize the document and keep the most important information necessary to answer the question. Later, I want to test whether the response contains the information required for a correct answer to the question. 

Is it possible to set up such a flow using promptfoo to accomplish this?

**Comment by zhlmmc** [comment]
You may need to break the scenario into two tests. One for summarization and one for asking questions.

**Comment by tttbone8122** [comment]
Do you mean two separate test files or the entire tests? If so, how can it be done? I'm stuck on this.

**Comment by tttbone8122** [comment]
I mean, how can I get the model's response from Promptfoo and transfer that response to another test? The only thing that comes to mind is to transfer the response manually, but that would be somewhat pointless.

**Comment by zhlmmc** [comment]
> I mean, how can I get the model's response from Promptfoo and transfer that response to another test? The only thing that comes to mind is to transfer the response manually, but that would be somewhat pointless.

You can write a custom provider and do what ever logic inside.

**Comment by tttbone8122** [comment]
I'll try to do it somehow. What could the steps to accomplish this look like?
