### ISSUE TITLE
Allow referencing a particular sheet of a Google Sheet as evaluation source

### ISSUE THREAD

**Issue by sbichenko** [promptfoo/promptfoo#1930]
**Is your feature request related to a problem? Please describe.**
I need to test multiple prompts with different evaluations, where evaluations:prompts have a n:1 relationship. I want to keep all evaluations in a single Google Sheet for convenience of the end-users. At the moment, when I reference a particular sheet of a Google Sheet via URL, it still grabs the first sheet.

**Describe the solution you'd like**
In config, if I put in a reference to the "bird" sheet of the example Google Sheets file and then run `promptfoo eval`, it should run tests from that particular sheet.
```
tests: https://docs.google.com/spreadsheets/d/1xHVjPg8nGU96FV-KXIhtD7GfvUzyy6Y1WW4kX8aLK9s/edit?gid=1649698752#gid=1649698752
```

**Describe alternatives you've considered**
I'll use separate Google Sheets and keep another Google Sheet as the table of contents - but that's very brittle.

**Comment by typpo** [comment]
Added in #1942
