### ISSUE TITLE
Support AWS Bedrock access key in config file

### ISSUE THREAD

**Issue by zhlmmc** [promptfoo/promptfoo#1935]
I tried to set `aws_access_key_id` and `aws_secret_access_key` in promptfooconfig.yaml, but it does not work. Set env is ok. Not sure if set in config supported?

**Comment by mldangelo** [comment]
Hi @zhlmmc,

Support for AWS credentials in the config file has been added in [#1936](https://github.com/promptfoo/promptfoo/pull/1936). Please update to version [0.94.0](https://github.com/promptfoo/promptfoo/releases/tag/0.94.0), and it should now work as expected.

Let us know if you have any further issues!
