### ISSUE TITLE
__description is ignored when using Google Sheets

### ISSUE THREAD

**Issue by sbichenko** [promptfoo/promptfoo#1946]
**Describe the bug**
If a Google Sheets file contains a __description column, its content is ignored.

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

Use the following config:
```
# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: "Line break test"

prompts:
  - 'A short description of Adele'
  
providers:
  - "openai:gpt-4o"
  
tests: https://docs.google.com/spreadsheets/d/1--15puWzEGnhCcuuLG-NPsTyvS6RHCCcrzA5BJl8Lbs/edit?gid=0#gid=0
```

Run the eval and view it (either in browser or in CLI). Link to shareable results: https://app.promptfoo.dev/eval/f:d26ab224-2964-491b-94c1-e4f4b400b433/

There is no "Description" column in the table.

**Expected behavior**
A "Description" column in the table

**System information (please complete the following information):**

- Promptfoo version: 0.93.3

**Comment by typpo** [comment]
Should be fixed with #2000.  Thanks for flagging - found an underlying issue with all descriptions after the latest db migration
