### ISSUE TITLE
Question: is `---` in `prompts.txt` for one conversation many prompts, or many conversations one prompt?

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#197]
Please forgive me for a noobish question, but I am questioning my understanding of something.

Within `prompts.txt`, is `---` designed for:

- Delimiting within one conversation (one conversation, many prompts)
- Delimiting across conversations (many conversations of one prompt)

----

To reword, from https://promptfoo.dev/docs/configuration/parameters#prompt-files:

```txt
Translate the following text to French: "{{name}}: {{text}}"
---
Translate the following text to German: "{{name}}: {{text}}"
```

Is this like having a two chat conversation, or two separate one chat conversation?

**Comment by typpo** [comment]
It's split into multiple prompts.  It's as though you had two prompt files containing each line.

**Comment by jamesbraza** [comment]
Thank you!  Opened a docs PR to clarify this.
