### ISSUE TITLE
Request: `--output=file.txt` defaulting to non-CSV

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#200]
I discovered using `--output=file.txt` as being pretty non-readable, mainly cuz the CSV output isn't that friendly overall.

```txt
"{""raw"":""<redacted>{{ area }}<redacted>{{ area }}<redacted>"",""display"":""<redacted>{ area }}<redacted>{{ area }}<redacted>""}",area,expected,result
"[PASS] (0.65)  <redacted>",<redacted>,"<redacted>
",<redacted>

```

Thoughts on having `.txt` extension default to YAML formatting, as opposed to CSV formatting?

**Comment by typpo** [comment]
That's fair - not sure how many people use .txt outputs.  I've updated it accordingly in https://github.com/promptfoo/promptfoo/commit/cd9533f9daa5dc30317a8b1fd739fa589998f833

**Comment by jamesbraza** [comment]
Thanks again!
