### ISSUE TITLE
Error when using BASIC auth in PROMPTFOO_REMOTE_API_BASE_URL

### ISSUE THREAD

**Issue by tan-z-tan** [promptfoo/promptfoo#2012]
**Is your feature request related to a problem? Please describe.**
I'm using self-hosted Promptfoo with BASIC authentication on our API server. When setting PROMPTFOO_REMOTE_API_BASE_URL with BASIC auth credentials, I get this error:

```
promptfoo share


...
Request cannot be constructed from a URL that includes credentials: https://XXXXX/health  at node:internal/deps/undici/undici:13185:13 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

- Steps to reproduce:
  - Set `PROMPTFOO_REMOTE_API_BASE_URL` with BASIC auth like this:
  - https://username:password@example.com

Is it possible to use promptfoo share with a server that requires BASIC authentication? If not, what authentication method would you recommend?
Environment:

- Promptfoo Version: 0.94
- Self-hosted deployment

### Describe the solution you'd like
I would like to be able to use promptfoo share with a BASIC auth-protected API server. Either by:

- Supporting credentials in the URL
- Or providing an alternative way to specify BASIC auth credentials (perhaps as separate environment variables)

### Describe alternatives you've considered
Setting up a separate non-authenticated endpoint just for promptfoo (adds complexity)

**Comment by mldangelo** [comment]
@tan-z-tan We’ve released a fix for this. Please try the latest version and let us know if you’re still experiencing any issues. Feel free to comment or reopen the issue if you need further assistance.

**Comment by tan-z-tan** [comment]
@mldangelo Fixed. Thank you!
