### ISSUE TITLE
Request: adding logged messages to `--output file.xyz`

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#202]
It would be nice if `--output file.xyz` contained any logs made.  For example, they could be stored under a `logs` key.

This can also make it easier to report bugs, just provide an output file, and it will include debugging info.

Thanks in advance as always!

**Comment by typpo** [comment]
Going to close this as I recommend redirecting stdout and stderr to file, e.g.:
```
LOG_LEVEL=debug promptfoo eval > output.txt 2>&1
```
