### ISSUE TITLE
How can i use ollama to test  my prompts?

### ISSUE THREAD

**Issue by FableFatale** [promptfoo/promptfoo#2026]
I tried two methods with Ollama, but neither worked.

![image](https://github.com/user-attachments/assets/ceecfa50-18ca-4dd4-9bfd-906d230e7be3)
![image](https://github.com/user-attachments/assets/68524ab7-4a83-4e52-ab12-907736144a4c)

**Comment by FableFatale** [comment]
Error: OpenAI API key is not set. Set the OPENAI_API_KEY environment variable or add apiKey to the provider config.

**Comment by typpo** [comment]
Can you provide the full config?  I'm guessing you're using a model-graded assertion and you need to [override the provider](https://www.promptfoo.dev/docs/configuration/expected-outputs/model-graded/#overriding-the-llm-grader).

**Comment by FableFatale** [comment]
It works for me . Thanks

> Can you provide the full config? I'm guessing you're using a model-graded assertion and you need to [override the provider](https://www.promptfoo.dev/docs/configuration/expected-outputs/model-graded/#overriding-the-llm-grader).↳
