### ISSUE TITLE
Respect max text length table setting when rendering cells as Markdown

### ISSUE THREAD

**Issue by panozzaj** [promptfoo/promptfoo#2046]
**Is your feature request related to a problem? Please describe.**

We are giving some values as Markdown links to provide some handy links to our app. This could be like:

```
[123](http://localhost:3000/link/to/view/123)
```

However, when we do this, other table inputs do not respect the table "Max text length" value. We have some pretty big cells, so the browser tab gets bogged down and is somewhat unresponsive.

**Describe the solution you'd like**

I think we could use the truncated text as well here:

```tsx
// src/app/src/pages/eval/components/ResultsTable.tsx
400:                    {renderMarkdown ? (
401:                      <ReactMarkdown remarkPlugins={[remarkGfm]}>{value}</ReactMarkdown>  // << s/value/something else/
402-                    ) : (
403:                      <TruncatedText text={value} maxLength={maxTextLength} />
404-                    )}
405-                  </div>
```

**Describe alternatives you've considered**
N/A

**Additional context**

If you want me to take a crack at this, I can!

**Comment by mldangelo** [comment]
Hi @panozzaj, thanks for opening this issue and for the clear description! Your proposed solution sounds great, and we’d definitely welcome a PR on this. Feel free to go ahead, and if you have any questions or need guidance, don’t hesitate to reach out. Thanks again—looking forward to your contribution! 🚀

**Comment by mldangelo** [comment]
Thanks so much for your help in shipping this @panozzaj! Please feel free to reach out if you have any other feature requests, product ideas, or feedback.
