### ISSUE TITLE
Not clear how red teaming iterative provider is supposed to function

### ISSUE THREAD

**Issue by meandmycode** [promptfoo/promptfoo#2057]
Hello! I'm trying to use the redteam:iterative provider, I have a test case which uses a static system prompt (no variables for nunchuck to inject into) and as such the context vars are used to call a python target which then invokes the llm chain.

However, doing so doesn't seem to work as expected compared with other test types, specifically the `call_api` in my python evaluation gets a `None` context and so is never able to run the llm chain.

When looking into the source, I eventually found this line:

https://github.com/promptfoo/promptfoo/blob/b5ed0606bac81a0670dee73bef9f59917be0a9f1/src/redteam/providers/iterative.ts#L121

Here the underlying target is called, which is a wrapper around `callApi` as shown here:

https://github.com/promptfoo/promptfoo/blob/b5ed0606bac81a0670dee73bef9f59917be0a9f1/src/redteam/providers/shared.ts#L53-L75

However, it is clear here that context is never provided to the `callApi` which explains the issue.

Is it expected with iterative provider that context cannot be used? and that the only method is through prompt injection?

Thanks!

**Comment by typpo** [comment]
Thanks for flagging this!  #2090 should fix

**Comment by meandmycode** [comment]
> Thanks for flagging this! #2090 should fix

Ah amazing! Yes indeed it does, thanks a ton!
