### ISSUE TITLE
Support AWS Profiles and/or Session Tokens with AWS providers

### ISSUE THREAD

**Issue by rvernica** [promptfoo/promptfoo#2080]
**Is your feature request related to a problem? Please describe.**

Currently, the only AWS authentication supported is via access key and secret access key. More complex setups use SSO profiles or require a Session Token. Neither is supported by promptfoo.

**Describe the solution you'd like**

Support AWS Profiles and/or AWS Session Tokens for authentication.

**Describe alternatives you've considered**

Do not use promptfoo or use a [Custom Python](https://www.promptfoo.dev/docs/providers/python/) provider that does its own AWS authentication.

**Comment by typpo** [comment]
Released in 0.96.0!
