### ISSUE TITLE
persistent evaluation ids on export + import

### ISSUE THREAD

**Issue by IsaacGreenMachine** [promptfoo/promptfoo#2108]
**Is your feature request related to a problem? Please describe.**
I've been using a database to store promptfoo evals - love the JSON output for `promptfoo eval` with -o (and also `promptfoo export`)
I've run into an issue where the evaluation id changes on `promptfoo import`. (confirmed by the output of promptfoo import - `Eval with ID {} has been successfully imported`). Since I'm storing and using these in a database, I need the ids to stay the same even through imports and exports.

**Describe the solution you'd like**
I've done some digging and see that v2 of the import function had persistent evaluation ids - a flag (`promptfoo import {} --persistent`) or an environment variable to keep the ids persistent would be great.

**Describe alternatives you've considered**
for now, I'm changing the version of the json to "v2" instead of "v3" since that will keep the ids persistent.

Thanks!

**Comment by typpo** [comment]
Thanks for flagging!  #2112 should fix.

**Comment by typpo** [comment]
Released in 0.96.0!
