### ISSUE TITLE
Prompt template variable substitution issue

### ISSUE THREAD

**Issue by Stanley18520** [promptfoo/promptfoo#2110]
Summary
Prompt template variable substitution incorrectly inserts the entire context dictionary instead of the variable value.

## Current Behavior
The system inserts the entire context dictionary:
# {'vars': {'raw_text': 'Extract relevant quotes from the document and put it within citation tags.', '': ''}, 'provider': {'id': 'google:gemini-1.5-flash-002', 'label': ''}, 'config': {}}
## Expected Behavior
The system should insert only the raw text value:
# Extract relevant quotes from the document and put it within citation tags.
## Workaround
Using the full dictionary path in the template works as expected:
# {raw_text["vars"]["raw_text"]}

promptfoo version: 0.95.0

**Comment by typpo** [comment]
Can you provide a full working example of a config that doesn't work correctly?

**Comment by Stanley18520** [comment]
[Text-Improver.zip](https://github.com/user-attachments/files/17686163/Text-Improver.zip)

The configuration is included in the zip file. Only the personal information in the prompt has been removed, and everything else remains unchanged.

Promptfoo is an exceptional tool for prompt engineering. Thank you for your outstanding work.

**Comment by typpo** [comment]
This looks like expected behavior - the python prompt function takes a `context` dict that includes `vars`.  So I'd rename your argument to `context` and reference it like `context['vars']['raw_text']`.

https://www.promptfoo.dev/docs/configuration/parameters/#examples

Is there anyplace where you saw an example to the contrary?  We can update examples/docs accordingly.

**Comment by Stanley18520** [comment]
Thank you for your patience in answering my questions. Let's use the new method. I recall that in the previous version, test case variables were directly passed. On October 19th, when using promptfoo for prompt evaluation, it was like that. In November, I noticed it had changed to passing the context dictionary, possibly due to a version update.

**Comment by typpo** [comment]
Ah that's probably it. We made the change in order to make it consistent
with other functions. Sorry for the trouble!
