### ISSUE TITLE
assertion support .cjs file

### ISSUE THREAD

**Issue by zhlmmc** [promptfoo/promptfoo#212]
I have an environment that can't execute .js file but .cjs file. Is it reasonable to support .cjs or .mjs files?

**Comment by typpo** [comment]
Hi @zhlmmc, just to clarify, are you referring to `javascript`-type assertions that begin with `file://`?

**Comment by zhlmmc** [comment]
> Hi @zhlmmc, just to clarify, are you referring to `javascript`-type assertions that begin with `file://`?

yes

**Comment by zhlmmc** [comment]
> Hi @zhlmmc, just to clarify, are you referring to `javascript`-type assertions that begin with `file://`?
Yes,
![image](https://github.com/promptfoo/promptfoo/assets/1726527/4a5203e9-0535-4372-a298-41c70fb4dd56)

**Comment by typpo** [comment]
That should be easy to add, at least for the cjs case.  Opened PR #214 which will be in the next release
