### ISSUE TITLE
Broken Anthropic System Message for Amazon Bedrock

### ISSUE THREAD

**Issue by maximcherny** [promptfoo/promptfoo#2136]
**Describe the bug**

Similarly to #2123, the current message parsing logic does not extract the system message from the message list to be used as a separate parameter.

To reproduce, use the existing example from `examples/claude-vs-gpt-image/promptfooconfig.yaml` with the `bedrock:anthropic.claude-3-sonnet-20240229-v1:0` provider.

The associated API call returns the following error:

```
API call error: ValidationException: Malformed input request: #: subject must not be valid against schema {"required":["messages"]}#/messages/0/role: system is not a  valid enum value, please reformat your input and try again.
```

**System information (please complete the following information):**

- Promptfoo version: 0.96.1

**Comment by mldangelo** [comment]
Hi @maximcherny, thanks for catching this, and apologies for the disruption! I just issued a fix in release 0.96.2. Could you give it a try and let me know if it resolves the issue on your end? Feel free to reach out if you notice anything else or need further support.

**Comment by maximcherny** [comment]
Thanks so much @mldangelo and apologies for the delay. 

If I test with the latest HEAD at `05f324d6deb69581f93bab59e3a27231532f788e` and only this provider `bedrock:anthropic.claude-3-sonnet-20240229-v1:0` I am now getting the following error:

```
[FAIL] Error: OpenAI API key is not set. Set the OPENAI_API_KEY environment variable or add `apiKey` to the provider config.
```

```
npm run local -- --version
> promptfoo@0.97.0 local
> ts-node --cwdMode --transpileOnly src/main.ts --version

0.97.0
```

I am not sure why this config setting would be required for the provider I am using?

**Comment by maximcherny** [comment]
Correction - if I change the `defaultTest` provider for the `llm-rubric` assertion everything works as expected, as per the troubleshooting docs, thanks again for fixing this.
