### ISSUE TITLE
Why is docker version lagging behind git?

### ISSUE THREAD

**Issue by yelonek** [promptfoo/promptfoo#2144]
**Describe the bug**
I pulled docker file from main and it is 0.93.3 instead of latest - 0.96.2.

**To Reproduce**
Follow the documentation to pull docker image from the main branch.
https://www.promptfoo.dev/docs/usage/self-hosting/

**Expected behavior**
Container has the latest version of promptfoo running.

**System information (please complete the following information):**

- Promptfoo version: 0.93.3 & 0.96.2

**Comment by mldangelo** [comment]
Hi @yelonek, thanks for reaching out! Can you please try pulling the latest image again with the following commands?

```sh
docker pull ghcr.io/promptfoo/promptfoo:latest
docker run -it ghcr.io/promptfoo/promptfoo:latest promptfoo --version
```
When I run these, I get version 0.96.2. I'll update the docs to reflect latest over main. Please feel free to reach out with other comments / concerns / questions.

**Comment by yelonek** [comment]
Hi @mldangelo!
Thanks for such a quick reponse. Couple of seconds ago I deleted the old image and downloaded a fresh one. The response is `0.96.1`.

Which is still confusing, but good enough for me now. Thanks!

**Comment by mldangelo** [comment]
@yelonek A new Docker release should be available in about 20 minutes. You can follow the progress here: https://github.com/promptfoo/promptfoo/actions/runs/11975522898. I’m going to close this issue, but feel free to reopen it if you encounter any other issues or have suggestions for Docker features, improvements, tags, registries, etc.
