### ISSUE TITLE
Question : How to evaluate a single value in a Json Output ?

### ISSUE THREAD

**Issue by BlahBlah314** [promptfoo/promptfoo#216]
Hi !

It's been two weeks that I am using promptfoo for a project, trying to understand what's possible to do, and finally I'm stuck with this issue : I want an LLM to extract some information from a text and return them under a json format. I'm pretty happy with my prompt, but now I want to evaluate the result. So basically, I want to evaluate that some information are exactly the same and some are similar.

Example : we got this output from the LLM to evaluate:
{name : "Roger", age : "53", remark : "shy"}
what is expected:
{name : "Roger", age : "53", remark : "a bit shy"}

I want to evaluate that the values "name" and "age" match exactly what is expected, but I want to evaluate the "remark" similarly. The first one was obvious to me, I just compared it to a JSON schema with constants for name and age; but for remark, I don't want to enum all the possibilities, so how can I just test this value with the similarity?

Thank you for the answer !

**Comment by typpo** [comment]
Hi @BlahBlah314,

The way to do this is with a `postprocess` option: https://promptfoo.dev/docs/configuration/guide/#postprocessing.  

`postprocess` is a javascript snippet that acts on a test case.  For example:
```yaml
tests:
  - options:
      postprocess: JSON.parse(output).remark
    assert:
      - type: similarity
        value: shy
```

Let me know how this works for you!

**Comment by zhlmmc** [comment]
> Hi !
> 
> It's been two weeks that I am using promptfoo for a project, trying to understand what's possible to do, and finally I'm stuck with this issue : I want an LLM to extract some information from a text and return them under a json format. I'm pretty happy with my prompt, but now I want to evaluate the result. So basically, I want to evaluate that some information are exactly the same and some are similar.
> 
> Example : we got this output from the LLM to evaluate: {name : "Roger", age : "53", remark : "shy"} what is expected: {name : "Roger", age : "53", remark : "a bit shy"}
> 
> I want to evaluate that the values "name" and "age" match exactly what is expected, but I want to evaluate the "remark" similarly. The first one was obvious to me, I just compared it to a JSON schema with constants for name and age; but for remark, I don't want to enum all the possibilities, so how can I just test this value with the similarity?
> 
> Thank you for the answer !

I believe you need a javascript assertion https://www.promptfoo.dev/docs/configuration/expected-outputs#javascript which should parse the output json and validate different fields accordingly. The built-in assertions can't do the combinations.

**Comment by BlahBlah314** [comment]
Hi both of you !

Thank you for the quick answers! It worked very well with the postprocess parsing in my case. So again, thank you !

For further potential questions, I've joined the Discord community :)
