### ISSUE TITLE
apiVersion is interpreted as a timestamp

### ISSUE THREAD

**Issue by rvernica** [promptfoo/promptfoo#2174]
**Describe the bug**
In the config file I have:
```
  - id: azure:chat:gpt-4
    config:
      apiBaseUrl: "https://foo.bar"
      apiVersion: 2023-05-15
```
In `providers.ts` I added the line `console.log("config:", providerOptions);` and I get the following in the console:
```
config: {
  id: 'azure:chat:gpt-4',
  config: {
    apiBaseUrl: 'https://foo.bar',
    apiVersion: 2023-05-15T00:00:00.000Z,
    basePath: ''
  },
  env: undefined
} 
```
Notice the timestamp format of the `apiVersion` value.

When the REST endpoint gets called the URL is:
```
https://foo.bar/openai/deployments/gpt-4/chat/completions?api-version=Sun May 14 2023 20:00:00 GMT-0400 (Eastern Daylight Time)
```
Notice how the `apiVersion` is a human-friendly timestamp converted to the local time zone.

**To Reproduce**
See above.

**Expected behavior**
Produce a correct endpoint URL.

**Screenshots**
N/A

**System information (please complete the following information):**

- Promptfoo version: latest from [master](https://github.com/promptfoo/promptfoo/tree/17ad62ebe7f706bcf5dc2e78aa83db475f62a8f4)

**Additional context**
N/A

**Comment by typpo** [comment]
I wonder if this is some unintended magic from the yaml parser?

**Comment by rvernica** [comment]
YAML treats the value as a time stamp. Adding quotes around the value fixes the issue:
```
     apiVersion: "2023-05-15"
```
