### ISSUE TITLE
Is there a way to use a document as an input for an assertion ?

### ISSUE THREAD

**Issue by SysOverdrive** [promptfoo/promptfoo#2177]
- description: "Simple  Assertions"
  vars:
    input_document: my_document.pdf
assert :

.
.
.

And use that as the input prompt for the agent

**Comment by typpo** [comment]
Support for PDF vars is added in #2218 !

**Comment by mldangelo** [comment]
Hi @SysOverdrive! I’m closing out this issue. Please pull the latest version of Promptfoo to load PDFs. Feel free to reopen this issue or reach out if you have any other questions or product feedback. Thanks!

**Comment by SysOverdrive** [comment]
This is amazing guys ! Thank you <3
