### ISSUE TITLE
azure openai doesn't work with ollamazure (a emulator of Azure OpenAI)

### ISSUE THREAD

**Issue by AmineDjeghri** [promptfoo/promptfoo#2183]
**Describe the bug**

I am using [ollamazure](https://github.com/sinedied/ollamazure), which simulates the Azure OpenAI API (using Ollama). It works with all the tools I use except Promptfoo. When attempting to use it with Promptfoo, there is no readable error message except the following:

```
At least one evaluation failure occurred. This might be caused by the underlying call to the provider, or a test failure.
"id":"e5ea33f57a75d6ac88fa70e6a82943c08e0fa9811d161d67cb1da3c5ebf26746","provider":"azureopenai:chat:gpt-4o-mini","metrics":{"score":0,"testPassCount":0,"testFailCount":1,"assertPassCount":0,"assertFailCount":0,"totalLatencyMs":83238,"tokenUsage":{"total":0,"prompt":0,"completion":0,"cached":0,"numRequests":1},"namedScores":{},"namedScoresCount":{},"cost":0}}
```

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

.env file : 
```
# Ollamazure (Simulated Azure OpenAI with a local server)
OLLAMA_MODEL_NAME="phi3:3.8b-mini-4k-instruct-q4_K_M"
AZURE_OPENAI_DEPLOYMENT_NAME="gpt-4o-mini" # fake name
AZURE_OPENAI_API_KEY="123456" # fake api key
AZURE_OPENAI_ENDPOINT="http://localhost:4041" # real ollamazure endpoint
AZURE_OPENAI_API_VERSION="2024-10-01" # fake api version
AZURE_OPENAI_API_HOST="localhost:4041/"
```

run ollama, ollamazure and promptfoo 

promptfoo config : 
(second one is the model running directly in ollama, it works, first one is the simulated azureopenai that doesn't work
```
providers:
  - id: azureopenai:chat:gpt-4o-mini # env variables are in .env
  - id: ollama:chat:phi3:3.8b-mini-4k-instruct-q4_K_M # env variables are in .env
```

**Comment by AmineDjeghri** [comment]
maybe it has something to do with the https and http ?
For example, i noticed that promptfoo needs `AZURE_OPENAI_API_HOST` without the https
however the other libraries use an endpoint with https 

do you process the https / http?

**Comment by typpo** [comment]
Try using `AZURE_API_BASE_URL` to set the full URL instead of just the host - that way you can use http instead of https!

**Comment by AmineDjeghri** [comment]
what is the difference between these three URLs please ?
can you proved an example ? 

<img width="819" alt="image" src="https://github.com/user-attachments/assets/34c12001-9cfc-4630-b043-1844712df06b">

**Comment by typpo** [comment]
Should be

```yaml
providers:
  - id: azureopenai:chat:gpt-4o-mini 
    config:
      apiHost: xxxxxx.openai.azure.com/
```

**Comment by AmineDjeghri** [comment]
Thank you

is it normal that the azureopenai also works with this en var  in promptfoo ? 

`AZURE_OPENAI_API_KEY` instead of `AZURE_API_KEY`
I tried both of them and they work with AZURE
