### ISSUE TITLE
Similarity check via CSV not working

### ISSUE THREAD

**Issue by AZielinsky95** [promptfoo/promptfoo#220]
When running a similarity check via the CSV __expected column, I get the following error: 
 
```
[FAIL] Error: Invariant failed: Provider id() {
return `openai:${this.modelName}`;
} must implement callEmbeddingApi for similarity check
```

Using `openai:gpt-4`

I raised the same issue in this [ticket](https://github.com/promptfoo/promptfoo/issues/195#issuecomment-1736495303) which I thought I'd fixed, but I just got it to default to an equality check which would always fail.

Here is a simplified version of my CSV:

```
var1,var2,var3,__expected
Test1,Test2,Test3,similar(0.8):hello world
```

Running the same assertion in JS with the same data works fine.

**Comment by typpo** [comment]
Are you able to share your `providers` config?  Is it just `providers: openai:gpt-4`?

**Comment by AZielinsky95** [comment]
Yep that’s it

**Comment by AZielinsky95** [comment]
So I discovered it only throws this error if `defaultTest` includes an assertion that specifies another provider, like the following:

```Typescript
 defaultTest: [{
    type: "llm-rubric",
    value: "Are questions formatted as 3 numbered points on separate lines? Yes or No?",
    provider: "openai:gpt-3.5-turbo-0613",
  }]
```

If I don't specify a provider in the above assertion then everything works fine.

**Comment by typpo** [comment]
Hi @AZielinsky95,

Thanks for the report and for pinpointing the issue!  fb4b2437dee46ccf8e7ef83fdf8cfeb62abb9b7d should fix this issue by falling back to a model that supports embeddings.

This could also be resolved in config by setting `provider: openai:embedding:text-embedding-ada-002` on the assertion object.  But this is not possible in the CSV `__expected` format.
