### ISSUE TITLE
promptfoo redteam setup is obsolete

### ISSUE THREAD

**Issue by AmineDjeghri** [promptfoo/promptfoo#2207]
**Describe the bug**
If i am not mistaken, these pages need to be updated : 
- https://www.promptfoo.dev/docs/red-team/quickstart/
- https://www.promptfoo.dev/docs/usage/command-line/#promptfoo-redteam-setup

It says to use `promptfoo redteam setup` but it doesn't exist in the commands of promptfoo redteam.
The available commands are : 

```
Commands:
  init [options] [directory]       Initialize red teaming project
  eval [options]                   Evaluate prompts
  generate [options]               Generate adversarial test cases
  run [options]                    Run red teaming process (init, generate, and evaluate)
  poison [options] <documents...>  Generate poisoned documents for RAG testing
  report [options] [directory]     Start browser ui and open to report
  plugins [options]                List all available plugins
  help [command]                   display help for command
```

**Comment by mldangelo** [comment]
@AmineDjeghri Sorry about this. We updated the docs yesterday before issuing a new release. I just released [0.98.0](https://github.com/promptfoo/promptfoo/releases/tag/0.98.0), which includes the updated commands mentioned in the docs. Everything should now align as expected. Please let us know if you encounter any further issues!

**Comment by AmineDjeghri** [comment]
@mldangelo 

I think you should also update the docs of Azure OpenAI

The env variables can either be written like : `AZURE_KEYNAME` or `AZURE_OPENAI_KEYNAME`

https://github.com/promptfoo/promptfoo/blob/main/src/providers/azure.ts#L219

**Comment by mldangelo** [comment]
The AZURE_OPENAI ones are considered legacy which is why we removed them from the docs. Please use the AZURE_ instead.

**Comment by AmineDjeghri** [comment]
What do you mean by legacy ? The problem that I think of is the confusion for the projects that use other azure services. Having explicitly a variable named AZURE_OPENAI_API_KEY separates it from AZURE_AI_SEARCH_API_KEY for example.  
Are you planning to remove them?

**Comment by mldangelo** [comment]
Microsoft now supports a broader range of models, including non-OpenAI models like phi. To align with this shift and make the environment variable names more versatile, we removed “OPENAI” from the names. This change allows generic environment variables to be used seamlessly across different Azure services without being tied to a specific model provider. For example, AZURE_API_KEY now serves a broader purpose, while AZURE_OPENAI_API_KEY was more narrowly defined. While we have no immediate plans to remove the legacy AZURE_OPENAI_ variables and the legacy variables will continue to function for the foreseeable future (possibly years). As for other services, we don’t support AZURE_AI_SEARCH, but we’ll address it if and when we need to.
