### ISSUE TITLE
Link to google sheet not working

### ISSUE THREAD

**Issue by AZielinsky95** [promptfoo/promptfoo#221]
The sheet is visible to "anyone with the link", however, running the tests silently fails with no variables getting loaded.

I'm using the SDK with Typescript. Here is my test suite with the sheet from your examples. (Also not working for me)
```Typescript
return {
    description: "Test Prompt A",
    providers: "openai:gpt-4",
    prompts: [prompt],
    tests: "https://docs.google.com/spreadsheets/d/1eqFnv1vzkPvS7zG-mYsqNDwOzvSaiIAsKB3zKg9H18c/edit?usp=sharing",
    defaultTest: tests,
    outputPath: "./src/tests/latestResults.json"
} as EvaluateTestSuite
```

Works fine when I use a local CSV.

**Comment by typpo** [comment]
This should be fixed by #222, which will be included in the next release.
