### ISSUE TITLE
Error formatting and structure lost in the UI when using Custom Python Provider

### ISSUE THREAD

**Issue by rvernica** [promptfoo/promptfoo#2236]
**Describe the bug**
I have a custom Python provider. The provider reports errors as specified in the [documentation](https://www.promptfoo.dev/docs/providers/python/#python-script) The errors contain structure and indentation but this gets lost in the web UI.

Here is how the error appears in the terminal:
![image](https://github.com/user-attachments/assets/39448adf-db08-4a89-8a79-318b77fc8ac1)

Here is how the error appears in the web UI
![image](https://github.com/user-attachments/assets/eed2ea8e-ce63-434c-ac69-5433fb7ba795)

Notice how the newlines and indentation are lost.

**To Reproduce**
Write a custom Python provider that returns an error with structure and indentation.

**Expected behavior**
Preserve the formatting or provide a way to format the error message for the web UI.

**Screenshots**
See the description above.

**System information:**

- Promptfoo version: `0.97.0`

**Additional context**
N/A

**Comment by mldangelo** [comment]
@rvernica Thanks for reporting this issue! This has been fixed in version [0.100.6](https://github.com/promptfoo/promptfoo/releases/tag/0.100.6). Please upgrade to the latest version and let me know if you see any other. Thanks for helping us improve promptfoo! 🙌
