### ISSUE TITLE
Changin the target in redteam doesn't do anything

### ISSUE THREAD

**Issue by AmineDjeghri** [promptfoo/promptfoo#2245]
**Describe the bug**
In the redteam feature, changing the target doesn't seem to work. 
Maybe i'm missing something

In the yaml file : 
```
  - id: https
    label: 'travel-agent-agent'
    config:
      url: 'https://example.com/generate'
      method: 'POST'
      headers:
        'Content-Type': 'application/json'
      body:
        myPrompt: '{{prompt}}'
```
or 

`  - id: azureopenai:chat:gpt-4o-mini
`
result : 
```
Error in extraction: API error: 404 Not Found
{"error":{"message":"model \"gpt-4o-2024-05-13\" not found, try pulling it first","type":"api_error","param":null,"code":null}}
An unexpected error occurred: Failed to perform extraction: API error: 404 Not Found
{"error":{"message":"model \"gpt-4o-2024-05-13\" not found, try pulling it first","type":"api_error","param":null,"code":null}}

```

- Promptfoo version: 0.99

**Comment by AmineDjeghri** [comment]
after further investigation, having the following env variable set, causes the problem:

```
OPENAI_API_KEY="t"
```
commenting it from my .env file solves the problem. 

- maybe the plugins llm graders use gpt-4o-2024-05-13 with this key ?
- also, can we override the plugin llm grader ?

**Comment by typpo** [comment]
The attacker model is different from the target, and defaults to GPT-4o.

See here for info on how to change the attacker model:
https://www.promptfoo.dev/docs/red-team/configuration/#providers

Or, just unset OPENAI_API_KEY and it will use a remote provider.
