### ISSUE TITLE
Unable to utilize Azure OpenAI completion model

### ISSUE THREAD

**Issue by ishikagoel5628** [promptfoo/promptfoo#226]
I'm attempting to utilize the GPT-3.5-turbo API from Azure OpenAI, but I'm encountering the following error:

[FAIL(0.49)] API response error: TypeError: Cannot read properties of undefined (reading '0'): {"error":{"code":"BadRequest","message":"logprobs, best_of and echo parameters are not available on gpt-35-turbo model. Please remove the parameter and try again. For more details, see https://go.microsoft.com/fwlink/?linkid=2227346."}}

Is there a way I can handle this?

**Comment by typpo** [comment]
Hi @ishikagoel5628, would you be able to provide your config?  That will help me troubleshoot.  At a minimum, would need to see the `providers` block.

**Comment by ishikagoel5628** [comment]
prompts: [prompts.txt]
providers:
  - id: azureopenai:completion:gpt-35-turbo
    config:
      temperature: 0.0

**Comment by ishikagoel5628** [comment]
prompts: [prompts.txt]
providers:
  - id: azureopenai:completion:gpt-35-turbo
    config:
      temperature: 0.0

**Comment by typpo** [comment]
Ah, I see.  GPT 3.5 Turbo is a chat completion model.  You should specify `azureopenai:chat:gpt-35-turbo`
