### ISSUE TITLE
Allow multiple output formats simultaneously with `outputPath`.

### ISSUE THREAD

**Issue by Wehzie** [promptfoo/promptfoo#227]
Currently, `outputPath` in `promptfooconfig.yaml` supports only one argument of type string.
In addition, `outputPath` should support type `List[str]` to allow outputting multiple formats from a single run simultaneously.
Currently, supported extensions are `csv, txt, json, yaml, yml, html`.
An additional extension should be `viewer`.
Where `viewer` writes to the web or console viewer.
Meanwhile, `html` should produce an HTML file at the provided path.

**Comment by typpo** [comment]
Thanks for the PR!  Closing this out as #229 is in the latest release.
