### ISSUE TITLE
web view version not getting updated a lot of times

### ISSUE THREAD

**Issue by KlausMikhaelson** [promptfoo/promptfoo#230]
web view version not getting updated a lot of times and in order to that I have to again and again first run it in cli and then in web to see the updated version

**Comment by typpo** [comment]
Does refreshing the webpage work?  Instead of re-running `promptfoo view`.  Have you left the previous `promptfoo view` command running?

**Comment by typpo** [comment]
@KlausMikhaelson lmk if you have a repro for this!
