### ISSUE TITLE
promptfoo.evaluate() does not return config info

### ISSUE THREAD

**Issue by zhlmmc** [promptfoo/promptfoo#234]
I found a difference when call promptfoo using cli and using Node package.
The JSON returned in cli:
![image](https://github.com/promptfoo/promptfoo/assets/1726527/91d747ec-5965-4c5d-95d2-b3382b466349)

The JSON returned in Node package:
![image](https://github.com/promptfoo/promptfoo/assets/1726527/be0328ec-1769-45ed-9c12-e5f4540f18a3)

**Comment by typpo** [comment]
Curious what the intention is for this request.  If you're calling `promptfoo.evaluate`, don't you already have the full config?
