### ISSUE TITLE
Can we write our own custom plugins and strategies?

### ISSUE THREAD

**Issue by Doitnowman** [promptfoo/promptfoo#2341]
**Is your feature request related to a problem? Please describe.**
Although, the default plugins and strategies are great, we can include more (or sometimes custom use-cases may demand specific plugins/strategies).

**Describe the solution you'd like**
Promptfoo documentation to provide clear instructions on how to add custom/additional plugins and strategies.

**Describe alternatives you've considered**
Beginning to explore. Exploring what changes will be required if additional plugin type is created via a ts file. What other changes will be required to ensure the new plugin is picked up and integrates well with rest of promptfoo without any regression. Would appreciate some input from devs to point me in the right direction.

Thanks!

**Comment by mldangelo** [comment]
Hi @Doitnowman,

Yes, you can write your own custom plugins and strategies! See

- [Custom Plugins Documentation](https://www.promptfoo.dev/docs/red-team/plugins/custom/)
- [Custom Strategies Documentation](https://www.promptfoo.dev/docs/red-team/strategies/custom/)

If you have additional questions or encounter any challenges, we’d love for you to join our [Discord](https://discord.gg/gHPS9jjfbs).

**Comment by Doitnowman** [comment]
Thank you, @mldangelo !

Tried following the documentation you linked and get the following error.

Error: OpenAI API key is not set. Set the OPENAI_API_KEY environment variable or add `apiKey` to the provider config.

**Comment by mldangelo** [comment]
We've tuned the plugin prompts for gpt-4o so I recommend using that model, but you can override the provider in the redteam section of your promptfooconfig. For example

redteam:
  provider: any-promptfoo-provider (http, python, javascript, etc.)

You can check out [this section of the code](https://github.com/promptfoo/promptfoo/blob/main/src/redteam/providers/shared.ts#L14) to see how it works.

What are you thinking about using instead? Make sure it supports json mode / structured outputs. If you have more questions feel free to put time one our calendar.

**Comment by Doitnowman** [comment]
I used our own OPENAI API KEY and it worked. However, what I was trying to ask is thaty as per the docs, the default behavior should be that if the user doesn't provide a redteam provider and it's api key, then it should use promptfoo's api key to generate test prompts? See screenshot below. If this is still true, how come my redteam tests were failing? Thanks!
![image](https://github.com/user-attachments/assets/0fb182ed-cc55-455e-a8cd-74297f1d060f)
