### ISSUE TITLE
Issue in downloading promptfoo in docker

### ISSUE THREAD

**Issue by Sak5ra** [promptfoo/promptfoo#2359]
**Describe the bug**
When I deployed the promptfoo in a docker env, I received some errors: "npm ERR! notarget No matching version found for @mui/core-downloads-tracker@^6.2.0.".  I have traced this package, but the version in npm is 6.1.10.  I don't know what caused it. The previous few attempts were successful except today.

**To Reproduce**
![image](https://github.com/user-attachments/assets/3b4457d3-9c06-4d85-95e7-5eb8b32fa399)

**Expected behavior**
npm ERR! notarget No matching version found for @mui/core-downloads-tracker@^6.2.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Screenshots**

**System information:**

![image](https://github.com/user-attachments/assets/9cae7818-7eeb-43b5-9b55-f430186d6785)

- Promptfoo version:

**Additional context**

**Comment by mldangelo** [comment]
Strange. Thank you for reporting this. The version in our package-lock.json is 6.1.10 (see [here](https://github.com/promptfoo/promptfoo/blob/main/package-lock.json#L8568)). I’ll try to reproduce the issue.

Unrelated to your issue - consider updating the Node.js version in your Docker base image from 18 to 20 or 22. Node.js 22 is now LTS, and Node.js 18 is nearing its end of life ([reference](https://endoflife.date/nodejs)).

Please let us know if it starts working again.

**Comment by abhiabhijit** [comment]
Im getting the same issue while testing promptfoo in google collab
<img width="1424" alt="image" src="https://github.com/user-attachments/assets/f6c3a497-6161-4f7c-a15f-01dd73d41902">

**Comment by mldangelo** [comment]
They just published 6.2.0 9 minutes ago! https://www.npmjs.com/package/@mui/core-downloads-tracker/v/6.2.0 Can you please try again @abhiabhijit and @Sak5ra?

**Comment by Sak5ra** [comment]
> They just published version 6.2.0 nine minutes ago! See https://www.npmjs.com/package/@mui/core-downloads-tracker/v/6.2.0
> 
> @abhiabhijit and @Sak5ra, could you please try again? MUI has many subpackages, and it seems we caught npm in an intermediate state while they were rolling out the new version.

Thanks for your help. Deploy successfully.
