### ISSUE TITLE
disable _conversation when evaluate

### ISSUE THREAD

**Issue by zhlmmc** [promptfoo/promptfoo#236]
I found the test result contains a _conversation history in result data under "vars".
![image](https://github.com/promptfoo/promptfoo/assets/1726527/410e43ea-ba62-4cbe-ae67-ff6603646a88)

I know that this feature is added to support conversation scenarios but in my case it is not needed. How can I disable this? Thanks!

**Comment by typpo** [comment]
73ee2cab1ebd8cd53d0d557da9b40a4f16b79b24 adds support for `PROMPTFOO_DISABLE_CONVERSATION_VAR`
