### ISSUE TITLE
Redteam custom plugin (reading from yaml file) no longer working

### ISSUE THREAD

**Issue by Doitnowman** [promptfoo/promptfoo#2375]
**Describe the bug**
Redteam custom plugins which required custom plugin definition in a separate yaml file, no longer seems to work with [0.100.6, 0.99.1] - works with 0.96.1. Haven't tested on others but seems to have broken somewhere between 0.96.1 and 0.99.1

**To Reproduce**
Create any custom plugin as per steps in the docs - https://www.promptfoo.dev/docs/red-team/plugins/custom/
Relevant screenshot of the custom plugin definition example
![image](https://github.com/user-attachments/assets/18e67b21-4206-4b23-8f40-17786ce8feb8)

**Expected behavior**
Newer version should run custom defined plugins, unless this feature was removed as planned.

**Screenshots**
N/A but please see relevant parts of the stdout below:

`"message": "Expected string, received object"
                  }
                ],
                "name": "ZodError"
              }
            ],
            "path": [
              "plugins",
              0
            ],
            "message": "Invalid input"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "received": "file://REDACTED.yaml",
            "code": "invalid_enum_value",`

**System information:**

N/A

- Promptfoo version: 0.100.6, 0.99.1, possibly others

**Additional context**

**Comment by mldangelo** [comment]
Hi @Doitnowman, thanks for reporting this issue! The problem with custom plugins using a file:// protocol has been addressed in [0.101.2](https://github.com/promptfoo/promptfoo/releases/tag/0.101.2). Please update to this version, and your custom plugin should work as expected.

If the issue persists or you encounter anything else, feel free to reopen this issue or create a new one. Thanks for using Promptfoo!
