### ISSUE TITLE
Cosine similarity issue

### ISSUE THREAD

**Issue by AZielinsky95** [promptfoo/promptfoo#240]
No matter how un-similar the values are, I get high similarity scores. (consistently above 0.7)

Example: 

Output value: "Reach out by email to check in and ensure everything is going smoothly."

Comparison value: "Hi Mom"

Results:

<img width="1150" alt="Screenshot 2023-10-24 at 4 01 48 PM" src="https://github.com/promptfoo/promptfoo/assets/17748596/795c5b42-4a86-4055-b482-1d11c5b71f64">

**Comment by typpo** [comment]
I tried this manually with the following:

```
curl https://api.openai.com/v1/embeddings   -H "Content-Type: application/json"   -H "Authorization: Bearer $OPENAI_API_KEY"   -d '{
    "input": "Reach out by email to check in and ensure everything is going smoothly.",
    "model": "text-embedding-ada-002"
  }' -o s1.json

curl https://api.openai.com/v1/embeddings   -H "Content-Type: application/json"   -H "Authorization: Bearer $OPENAI_API_KEY"   -d '{
    "input": "Hi Mom",
    "model": "text-embedding-ada-002"
  }' -o s2.json
```

```py
import json
from math import sqrt

def dot_product(X, Y):
    return sum(x*y for x, y in zip(X, Y))

def magnitude(vector):
    return sqrt(sum(pow(element, 2) for element in vector))

def cosine_similarity(X, Y):
    return dot_product(X, Y) / (magnitude(X) * magnitude(Y))

def main():
    with open('s1.json') as f:
        s1 = json.load(f)['data'][0]['embedding']
    with open('s2.json') as f:
        s2 = json.load(f)['data'][0]['embedding']
    print(cosine_similarity(s1, s2))

if __name__ == '__main__':
    main()
```

And the cosine similarity is indeed 0.7699.  It appears to be working as intended!  You'll have to tune the [threshold](https://promptfoo.dev/docs/configuration/expected-outputs#similarity) value accordingly.

**Comment by AZielinsky95** [comment]
Interesting, thanks for verifying. Will need to look into other methods of checking similarity.
