### ISSUE TITLE
Cannot use JSON prompts containing {{ or ---

### ISSUE THREAD

**Issue by iamjackg** [promptfoo/promptfoo#241]
I'm trying to test two raw OpenAI prompts provided as JSON. Both prompts contain one system message and multiple user messages.

Some of the messages in the prompts contain double curly brackets, which trips up Nunjucks. I tried to find a way to not run templating at all, but couldn't find any, so I just hacked `renderPrompt` to skip the templating.

Next issue: some of the prompt messages contain the string `---`, which trips up the multi-prompt splitter. I moved the two prompts to two separate files, and that got me past the first parsing error, but it now fails when running `model-graded-closedqa`, since apparently there's some splitting happening somewhere in there too.

**Comment by typpo** [comment]
Hey @iamjackg, thanks for the report.  Definitely seems like something is going wrong with escaping.

promptfoo does double-escape the original prompt when including it: https://github.com/promptfoo/promptfoo/blob/main/src/matchers.ts#L311-L313 

So I would guess that the string may have _already_ escaped when it got there.  As a temporary workaround, you can remove the nested escaped string (or use single quotes).

**Comment by typpo** [comment]
Probable fix landed in #242
