### ISSUE TITLE
`-c some_config.yaml` flag overrides `outputPath`

### ISSUE THREAD

**Issue by Wehzie** [promptfoo/promptfoo#247]
Async JavaScript doesn't seem to work anymore when loading from file. This might be a regression, as async worked before.

To replicate
```
// this doesn't work and results in ERROR undefined
async function main(output, context) {
  console.log(`raw output:\n\n${output}\n\n`);
  return true;
}
module.exports = main;

// this works

function main(output, context) {
  console.log(`raw output:\n\n${output}\n\n`);
  return true;
}

module.exports = main;
```

Edit: I've traced the origin of the error to the following.
`async` works fine when the `promptfooconfig.yaml` is named exactly as such.
However when using `npx promptfoo@latest -c other_config.yaml` then `async` fails.

A second bug occurs.
Namely, when providing `-c some_config.yaml` then `outputPath` is no longer read from `some_config.yaml` and no output file is written. Providing `-o some_path.json` works, however. This bug does not occur when running `eval` with a default `promptfooconfig.yaml` which then doesn't require providing the `-c` flag.

**Comment by typpo** [comment]
#232 is not published, so it makes sense that `npx promptfoo@latest` is not correctly supporting async assertions.  I am able to use assertions locally on `main`, even with `-c other_config.yaml`.  I'll bump the version and publish today, hopefully it resolves your issue.

**Comment by Wehzie** [comment]
Well that's embarrassing, I had not been running the main branch indeed. Apologies for the mess.

Running from main branch, it does work again. The issue with `-c something.yaml` overriding the `outputPath` persists.
