### ISSUE TITLE
Should folders of the `outputPath` be created when they don't exist?

### ISSUE THREAD

**Issue by Wehzie** [promptfoo/promptfoo#248]
Currently, providing an `outputPath` like `output/run1` will fail to execute `eval` when `output/run1` doesn't exist. I propose that the path of directories should be created during `eval` execution.

What are your opinions on this?

**Comment by typpo** [comment]
Easy enough to do: bc6e07e4aa8e166331b9cd4e046d0deffc6f6fcf
