### ISSUE TITLE
Feature Request: UI Metrics include Token Usage/Latency Summary

### ISSUE THREAD

**Issue by JansonYeTao** [promptfoo/promptfoo#251]
HI Really like this cool project!! Wondering if we can add more informative Token Usage/Latency Summary as part of the UI. Currently, we can only see the token usage/ latency by hovering on the each row.
<img width="1768" alt="image" src="https://github.com/promptfoo/promptfoo/assets/93152173/cba17d51-83c1-452d-ad07-dedeb5abbe82">

Thank u

**Comment by typpo** [comment]
Hi @JansonYeTao,

What kind of additional metrics would you like to see?  Would it be helpful to have aggregate metrics for each column?

**Comment by typpo** [comment]
#258 adds latency and token usage to the prompt column header

![latency and token usage metrics](https://user-images.githubusercontent.com/310310/279482780-1a9df9b9-9ad9-410f-8824-864b2247126a.png)

**Comment by JansonYeTao** [comment]
Yes thats correct. Thanks for taking care of this
