### ISSUE TITLE
shareable output folder

### ISSUE THREAD

**Issue by FFawzy** [promptfoo/promptfoo#256]
_TLDR;_
is it possible to instruct somehow the `view` command to read the results from a different folder ?

--

I've configured the results to be saved on disk in a specific folder in my repository that will be committed so everyone in my team can have access to the test results.
But I also want them to be able to `view` the test results in the UI

so my question is it possible to instruct somehow the `view` command to read the results from a different folder ?

**Comment by typpo** [comment]
#257 adds support for the `PROMPTFOO_CONFIG_DIR` environment variable, which overrides the `~/.promptfoo` default.

It also adds a `promptfoo view [directory]` CLI param, which you can use to override the viewer directory.

Will be included in the next published release!
