### ISSUE TITLE
[Question] Generate prompt Dynamically by using the response from previous conversation.

### ISSUE THREAD

**Issue by JansonYeTao** [promptfoo/promptfoo#260]
Do we have such functionality to generate prompt dynamically to support conversation usecase? eg. populating fields of input payload by using the reply coming from previous timestamp.

user_request = ["i need help", "need help with my passport"]

For example, 

At timestamp=0, user_request="i need help", and history is an empty list, and input_payload will be:
```
{
    "query": "i need help",
    "history: [],
}
```
And then lets say, we send the input payload and get the result from LLM eg. response payload: `{"reply": "hello, what can i do for u"} ` I want to append the result into history field

then at timestamp=1, input payload will be

```
{
    "query": "need help with my passport",
    "history: [  {"reply": "hello, what can i do for u"}   ],
}
```

and we send it into LLM again

Currently, im trying something like below, but the history field is always an empty []. Also im new to nunjucks so not sure if it is supported. Thank u

```
{% set new_history = [] %}

{% if _conversation.length > 1 %}
  {% for completion in _conversation%}
    {% set new_history = new_history.push(completion.output) %}
  {% endfor %}
{% else %}

{% endif %}

{
  \"query\": \"{{ request }}\",
  \"history\": {{ new_history | dump }},
}

```

**Comment by typpo** [comment]
It's definitely a little tricky with nunjucks.  Here's how I would do it:

```nunjucks
{% set input %}
{
    "query": "{{ query }}",
    "history": [
      {% for completion in _conversation %}
        {"reply": "{{ completion.output }}"} {% if not loop.last %},{% endif %}
      {% endfor %}
    ]
}
{% endset %}

[{
  "role": "user",
  "content": {{ input | trim | dump }}
}]
```

Here's my config:
```yaml
prompts: [prompt.json]
providers: [openai:gpt-3.5-turbo-0613]
tests:
  - vars:
      query: how you doing
  - vars:
      query: need help with my passport
```

This has the effect of including the conversation history _within_ the prompt content, which I think is what you're going for.  Here's the prompt input for the second test case:

```json
[{
  "role": "user",
  "content": "{\n    \"query\": \"how you doing\",\n    \"history\": [\n      \n    ]\n}"
}]
```

Example output: https://app.promptfoo.dev/eval/f:feb78e53-8b15-45f7-b1ec-804813430dfa

**Comment by JansonYeTao** [comment]
WOW this works like a charm. Thank u so much @typpo
