### ISSUE TITLE
Update README with developer docs for Web API

### ISSUE THREAD

**Issue by chartsNgraphs** [promptfoo/promptfoo#264]
Can the readme be udpated to include developer documentation for how to run the web server? 
I was able to successfully run the evaluation commands locally, but 'npm run local view' *says* that the server is running on localhost15500, yet when opened in the browser every route returns 404.

**Comment by chartsNgraphs** [comment]
I am using WSL2 on Windows 11, and everything is going swimmingly but the UI.

**Comment by typpo** [comment]
Hi @chartsNgraphs,

As of 83065a9c214681bd0d4ea507c7a384539b9456b5, to develop the web UI locally, run:
```
npm run local:web
```

This hosts a web frontend at http://localhost:3000 that talks to the `promptfoo view` web server.  The :3000 endpoint has hot reloading and other benefits of Next.js's developer environment.  (You'll still need to run `promptfoo view` or equivalent to host the CLI's API endpoints)

Hope this helps!

**Comment by chartsNgraphs** [comment]
Thanks, this definitely helps. I'm able to get the web UI to load now. 

However, the /eval/ page doesn't show my local evals, which I would expect to see if this is meant to be the equivalent of Promptfoo View. 

What I'm looking to do is to replicate the Promptfoo View routine from my local repo. Is this possible? Or is the Web app here exclusively for database-backed deployments, not local exploration of evaluations?

**Comment by typpo** [comment]
Yes, the local web app supports offline exploration of your evaluations and can run without database-backed deployments.  I use this setup for development.

Can you try the following:
- Make sure that the `NEXT_PUBLIC_PROMPTFOO_BUILD_STANDALONE_SERVER` is NOT set
- Set dummy values for supabase keys, `NEXT_PUBLIC_SUPABASE_URL=http://` and `NEXT_PUBLIC_SUPABASE_ANON_KEY=abc`

**Comment by chartsNgraphs** [comment]
Thanks, I've given that a try and it has helped. 

with NEXT_PUBLIC_PROMPTFOO_BUILD_STANDALONE_SERVER not set, the default nextconfig value for output is "export" which results in a nextjs exception of "Middleware cannot be used with "output: export"" exception during server startup, but as far as I can tell the server is starting successfully. Appreciate the help! I might try to get the readme contribution section updated on a future PR after I dig through this and make sure I am well educated. 

Have been using the CLI for prompt testing for a while now and highly appreciative of the work and thought by all the contributors so far!
