### ISSUE TITLE
Anthropic Provider - 

### ISSUE THREAD

**Issue by Pipboyguy** [promptfoo/promptfoo#265]
After defining the **ANTHROPIC_API_KEY** in `promptconfig.yaml` as well as an environment variable, the system still defaults to openapi's key:
```[FAIL] API response error: TypeError: Cannot read properties of undefined (reading '0'): {"error":{"message":"Incorrect API key provided: sk-or-v1*************************************************************7034. You can find your API key at https://platform.openai.com/account/api-keys.","type":"invalid_request_error","param":null,"code":"invalid_api_key"}}```

I've set providers as anthropic:

```yaml
providers: [anthropic:completion:claude-instant-1-100k]
```

version: 0.26.1

**Comment by typpo** [comment]
Are you using a `similarity`, `llm-rubric`, or `model-graded-*` assertion type?  If so, you'll have to [set the provider](https://promptfoo.dev/docs/configuration/expected-outputs/similar/#overriding-the-provider) for these test cases as well.
