### ISSUE TITLE
Assertions with error information in the web UI.

### ISSUE THREAD

**Issue by Wehzie** [promptfoo/promptfoo#269]
Currently JavaScript assertions allow boolean and integer return types.

![image](https://github.com/promptfoo/promptfoo/assets/39304339/fdfcb829-b314-4c3d-9add-77d3e6dd9f90)

I propose that a string should be passable with an error message alongside a boolean or int type.
At least in the case "false" such a message should be choosable in the UI to be displayed.

One example use-case could be compiler-feedback when compiling model-generated code.

**Comment by typpo** [comment]
Hey @Wehzie, try returning an object with the following structure:

```typescript
interface GradingResult {
  pass: boolean;
  score: number;
  reason: string;
}
```

For example:
```js
{
  pass: false,
  score: 0,
  reason: 'Assertion failed...',
}
```

This is vaguely documented [here](https://promptfoo.dev/docs/configuration/expected-outputs/javascript#multiline-functions), but can definitely be improved.

**Comment by typpo** [comment]
Updated the docs!  Closing this one out
