### ISSUE TITLE
Unable to generate prompts from a python files - /bin/sh: python: command not found

### ISSUE THREAD

**Issue by gautam-goudar** [promptfoo/promptfoo#272]
Following the example here
https://github.com/promptfoo/promptfoo/tree/main/examples/custom-prompt-function

I have set up prompts in a file called python_prompts.py file.

However when I run the below command, I see the below error.   Is there any setup or virtual environment creation involved in order to run the python code?  I don't any information regarding the same in the example
```
$ promptfoo eval

---
Error: Command failed: python "/Users/[redacted]/Documents/my-learning/promptfoo/one/prompt_python.py" "{\"vars\":{\"topic\":\"the weather\",\"_conversation\":[]}}"
/bin/sh: python: command not found

    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at Object.promptFunction [as function] (/usr/local/lib/node_modules/promptfoo/dist/src/prompts.js:195:36)
    at renderPrompt (/usr/local/lib/node_modules/promptfoo/dist/src/evaluator.js:64:45)
    at Evaluator.runEval (/usr/local/lib/node_modules/promptfoo/dist/src/evaluator.js:136:38)
    at /usr/local/lib/node_modules/promptfoo/dist/src/evaluator.js:464:36
    at /usr/local/lib/node_modules/promptfoo/node_modules/async/dist/async.js:151:38
    at replenish (/usr/local/lib/node_modules/promptfoo/node_modules/async/dist/async.js:448:21)
    at /usr/local/lib/node_modules/promptfoo/node_modules/async/dist/async.js:453:13 {
```

**Comment by typpo** [comment]
The python prompt type assumes you have a `python` binary installed.  If
you're not already using python, I recommend using a javascript prompt
because you already have that runtime set up if you're using promptfoo :)

**Comment by typpo** [comment]
Ah I see.  You probably need to alias `python` to `python3` via symlink for
example.  Make sure `python` points to an executable and it should work.

**Comment by typpo** [comment]
With 0.26.5, promptfoo now supports the `PROMPTFOO_PYTHON` environment variable, which you can use to override executable name or path (`python3` in your case).
