### ISSUE TITLE
Model can inject arbitrary HTML into my results page

### ISSUE THREAD

**Issue by jameshfisher** [promptfoo/promptfoo#308]
[The results table seems to deliberately inject text as HTML ...?](https://github.com/promptfoo/promptfoo/blob/b24edb65be1bf7d0e8383ce1337d1d405633f6cc/src/web/nextui/src/app/eval/ResultsTable.tsx#L72-L89)

The model's output is arbitrary. I don't want the model to be able to inject random scripts into my results table. At best, this is annoying, and at worst, it's a security vuln.

IMO, input/output in the results page should be shown as plaintext.

**Comment by jameshfisher** [comment]
Introduced in https://github.com/promptfoo/promptfoo/pull/55 - but not sure why

**Comment by typpo** [comment]
Thanks for pointing this out.  #309 should fix

**Comment by jameshfisher** [comment]
Amazingly fast response! Thanks! ❤️

**Comment by typpo** [comment]
No problem!  This fix was included in 0.30.0
