### ISSUE TITLE
Performance as metric

### ISSUE THREAD

**Issue by surak** [promptfoo/promptfoo#312]
Hi,

I see that there is a `latencyMs` field on the yaml results file, but I see no obvious way to compare performance (be it tokens/s, time to answer, multiple queries and whatnot).

The use-case is to be able to understand if a number of inference servers is enough for the demand, or if one needs to scale up things. In fact, right now I don't even know how fast my servers run or how much load I can throw at them.

Do you think that makes sense for promptfoo? 

Thanks!

**Comment by typpo** [comment]
Hi @surak,

Timings are surfaced in the webview, although it is a bit subtle:

![llm latency benchmark](https://github.com/promptfoo/promptfoo/assets/310310/a992e38f-2453-4c4d-92a5-7e00224ec131)

I agree it'd help if latency were more of a first-class metric - displayed more prominently, able to be used in assertions, etc.  As well as additional metrics such as tokens/second.

**Comment by surak** [comment]
So, the code already measures and stores it somehow, that's already great!

Now it "just"* needs to be a metric for comparison just like the others!

* "just" is never so simple when you are the one writing the code for it. 

So do you think this would make sense to be added to promptfoo?

**Comment by typpo** [comment]
Yup, definitely.  I plan to follow up on this :)

**Comment by typpo** [comment]
Hi @surak,

Pull request #344 adds a `latency` assertion type.  You can use it to fail any test case that takes longer than a given amount of time.  For example:

```yaml
assert:
  - type: latency
    threshold: 4000  # anything slower than 4 seconds fails
```

Would this be useful to you?

**Comment by typpo** [comment]
Added in version 0.33.0 !
