### ISSUE TITLE
Web viewer cant load eval data

### ISSUE THREAD

**Issue by LeDuySon** [promptfoo/promptfoo#319]
Hi promptfoo team, thank you guys for great framework, really love that. Recently, I have ran an evaluation and try to view that using promptfoo view but the ui just show loading eval data for all the time (image below). Can you guys help me with this?
![image](https://github.com/promptfoo/promptfoo/assets/33374938/620de504-f5f8-4e74-bab0-38e668684b3f)

**Comment by typpo** [comment]
Double checking, are you running `promptfoo view` in the background?

**Comment by LeDuySon** [comment]
> Double checking, are you running `promptfoo view` in the background?

No, im running that command directly on my azure VM

**Comment by typpo** [comment]
Hi @LeDuySon, `promptfoo view` should support hosting on hostnames besides localhost now.  Please give it a try with the latest version

**Comment by LeDuySon** [comment]
hi @typpo , everything work fine now. Thank you so much!
