### ISSUE TITLE
[FAIL]: Thread run failed: requires_action. OpenAI Assistant function calling

### ISSUE THREAD

**Issue by luchenkob** [promptfoo/promptfoo#324]
When i tried to test function calling for openAi assistants api, when I got this error - `[FAIL]: Thread run failed: requires_action`.  I think the issue is code checks for run is completed before checking for the steps and the tool_calls in those steps.  Error occurs at this block mostly - https://github.com/promptfoo/promptfoo/blob/b352cae2e4f8080839cc41f599c18c9a6fc4fc69/src/providers/openai.ts#L454

<img width="1487" alt="Screenshot 2023-12-05 at 8 18 50 PM" src="https://github.com/promptfoo/promptfoo/assets/82715038/78d1bc65-176f-4515-bb52-4c7835ecff48">

**Comment by typpo** [comment]
Hi @luchenkob, 

Thanks for catching this.  I've made a change to not error on `requires_action`, but this does open the question of what should happen.  e.g. should the run stop there, should we auto-confirm the action, etc.  What are your thoughts?

**Comment by luchenkob** [comment]
Hi @typpo,

Require action is same as the tools_calls in the steps.

> if (toolCall.type === 'function') {
>             outputBlocks.push(
>               '[Call function ${toolCall.function.name} with arguments ${toolCall.function.arguments}]',
>             );
>             outputBlocks.push('[Function output: ${toolCall.function.output}]');
> }
> 

So we can send the output back same way as we do in steps and end the run.

But to have complete test suite, it will be necessary to be able to send back a response when a function is called. As I would like to check how the assistant will respond to different types of submit-output for same  function.

Maybe for this user can create a prompt that says, `This is output for xyz function- {{output}}`, and hopefully it will be close enough.

**Comment by typpo** [comment]
This PR https://github.com/promptfoo/promptfoo/pull/473 adds support and will be in the next published release.  Thanks @aloisklink!
