### ISSUE TITLE
Question: Can we have two promptfooconfig.yaml files for two separate cases?

### ISSUE THREAD

**Issue by anoura12** [promptfoo/promptfoo#329]
Currently, I'm trying to bring an automation pipeline to our existing code and I wanted to run test cases on each of our prompts. In this case, I have x number of prompts and each prompt has their own set of variables that I need to test them on. (No variable is common between any of the prompts) 

I'm not sure if promptfoo has this but I would like to run those test cases on each prompt without having to configure the `promptfooconfig.yaml` file again and again. Is it possible to have multiple yaml files and then run any one file that I like for eval? Is there some existing configuration that already does this?

Right now, correct me if I'm wrong, the `promptfooconfig.yaml` file can only allow me to use a prompt.txt file with a set of prompts that all use the same variables. However, in my case, each prompt uses their own set of variables.

**Comment by typpo** [comment]
Hi @anoura12,

If I'm understanding correctly, sounds like you can do this by specifying the config file you want to run:

```
promptfoo eval -c myconfig1.yaml
```

If desired, you can combine multiple configs:

```
promptfoo eval -c myconfig1.yaml myconfig2.yaml
```

**Comment by anoura12** [comment]
Yes, that's what I was looking for. 

Additionally, is it possible to define prompts, providers and tests through the command line?

**Comment by typpo** [comment]
Yep, the command lines args for [`promptfoo eval`](https://promptfoo.dev/docs/usage/command-line#promptfoo-eval) override the config settings.  So you should be able to set prompts, providers, and tests for each individual eval run.

Let me know if you have any more questions :)
