### ISSUE TITLE
Expose all assertions for jest integration

### ISSUE THREAD

**Issue by joshuali925** [promptfoo/promptfoo#334]
Thanks for the project. I've been working on integrating it with jest for testing my project. According to the [docs for jest integration](https://www.promptfoo.dev/docs/integrations/jest)

> For more information on supported checks, see [Expected Outputs documentation](https://www.promptfoo.dev/docs/configuration/expected-outputs/).

and these are the supported assertions: https://www.promptfoo.dev/docs/configuration/expected-outputs/#assertion-types

But when using with jest, i cannot find how to call some of them, for example the `rouge-n` assertion. Based on the code although there is `handleRougeScore` defined in `assertions.ts`, it is not exported. Only these are exposed

https://github.com/promptfoo/promptfoo/blob/91f43cc8c6a7f562dab5f8c48503e76efb687123/src/assertions.ts#L1045-L1056

Is it possible to use other assertions with jest integration? Or any concerns to export them?

Thanks

**Comment by typpo** [comment]
Hey @joshuali925, I agree it makes sense to export the other assertions. The rationale was more or less that other assertions are pretty straightforward to reproduce (e.g. `contains` or `equals`), but the model-based ones aren't.  You're right that maybe some useful ones slipped through and are not exported.

**Comment by joshuali925** [comment]
That makes sense, most of them are trivial to implement. For my case I'm actually planning to call python code to run `rouge` and some other metrics together, so it's ok if they are not supported. You can close this issue or leave it open to see if others have similar needs, thanks.
