### ISSUE TITLE
Using external python assertion on Mac faced  Bad escaped character when vars with double quote

### ISSUE THREAD

**Issue by kylekhchen** [promptfoo/promptfoo#337]
Having the Python code execution failed: Bad escaped character issue when trying:
https://www.promptfoo.dev/docs/configuration/expected-outputs/python/#external-py
and
https://www.promptfoo.dev/docs/providers/custom-script

**Files used:**

promptfooconfig.yaml
`prompts: 
  prompt_gpt4_parameters.txt: gpt4_parameters
providers:
  - openai:gpt-4-1106-preview:
      id: gpt4
      prompts: 
       - gpt4_parameters
tests: 
  - vars:
      input: |-
        You said "Hello World"
    assert:
      - type: python
        value: file://assert.py
`

assert.py

`import sys

print (sys.argv[2])`

Error:
Python code execution failed: Bad escaped character in JSON at position 698 (line 1 column 699)

**System Info**

Mac using chip M2 and OS is Senoma 14.2

**Command**
npx promptfoo@latest eval

**Comment by typpo** [comment]
Hey @kylekhchen, thanks for the report.  Fix underway here: https://github.com/promptfoo/promptfoo/pull/338

**Comment by typpo** [comment]
Resolved in version 0.33.0
