### ISSUE TITLE
Question: Is it possible to take an external LLM response(output) and promptfoo just runs the metrics on the output?

### ISSUE THREAD

**Issue by ananthanandanan** [promptfoo/promptfoo#341]
- So I am working on an application that employs LLM to generate a response. It takes in a sample.csv file and it generates a response for each of the examples. 

- Ideally what I would want is to use the application to generate these responses and export them as` response.csv`. And this response.csv will be taken up by promptfoo and does the metrics evaluation.
- Right now, promptfoo does both the tasks of generating the response as well as evaluating it. Is it possible to just use promptfoo for the evaluation metrics?

**Comment by typpo** [comment]
Hi @ananthanandanan, yes this is possible.  Two ways:
1. promptfoo can call an [external script](https://promptfoo.dev/docs/providers/custom-script/) that reads the CSV file and generates the response.  
2. If you're building in Javascript, you may prefer to implement a [custom API provider](https://promptfoo.dev/docs/providers/custom-api/) to call your application natively.

**Comment by ananthanandanan** [comment]
Thanks, @typpo . The first one definitely would work for my use-case. My app is a python, streamlit app, where the user can upload a CSV and get back a response and then is exported as response.csv. 

I was just going through the examples and found [this](https://github.com/promptfoo/promptfoo/blob/main/examples/langchain-python/langchain_example.py), so I will tweak my script to take the csv file as args and see how it goes.

**Comment by ananthanandanan** [comment]
I had one follow-up question, for the same application. Would it be possible to aggregate the scores of multiple runs? For eg
![image](https://github.com/promptfoo/promptfoo/assets/53400471/37104d99-f2fe-4221-b796-b3f05b14a619)

**Comment by typpo** [comment]
Not quite like that, but you can run multiple configs at the same time:

```
promptfoo eval -c config1.yaml config2.yaml config3.yaml
```

Which will aggregate the results all in one view.
