### ISSUE TITLE
Bedrock model identifier for Claude 2.1 is `anthropic.claude-v2:1`; Code splits : so it hits v2

### ISSUE THREAD

**Issue by naoro** [promptfoo/promptfoo#347]
![image](https://github.com/promptfoo/promptfoo/assets/3356134/3204fb2b-c3e8-4a73-ae12-dc49dc276067)

It looks that in code, it takes only the modelName without `:1`

This is the full provider name `bedrock:completion:anthropic.claude-v2:1`

![image](https://github.com/promptfoo/promptfoo/assets/3356134/d212e297-9210-4715-ba56-42b165cc5d39)

Thanks!

**Comment by typpo** [comment]
Thanks for the catch.  4469b693993934192fee2e84cc27c21e31267e5f solves this issue, and will be included in the next published release.

**Comment by typpo** [comment]
Should be fixed in 0.33.1.  Let me know if you encounter any issues
