### ISSUE TITLE
Clearly document that the tool sends telemetry, possibly with explicit opt in

### ISSUE THREAD

**Issue by sihil** [promptfoo/promptfoo#35]
First up, thanks for working on this - it's an interesting project.

It's usually a surprise to find that an app of this sort is collecting telemetry, particularly when it's not clearly documented as doing so.

At a minimum I'd suggest that a clear message is output whenever telemetry will be collected with instructions to disable telemetry, or disable the clear message (an explicit opt in).

**Comment by typpo** [comment]
A notice on the first run will be out in the next release: #39   And as noted earlier, there is also a docs page on telemetry :)  Thanks!
