### ISSUE TITLE
Specifying multiple __expected column would test only one of them

### ISSUE THREAD

**Issue by naoro** [promptfoo/promptfoo#363]
For example, If I want to test using both icontain & grade, it uses only one of the assertions.

It's also not clear how to specify multiple matches for "icontains-all" using csv

Thanks!

**Comment by typpo** [comment]
Hi @naoro,

The way to do this would be to use `__expected1`, `__expected2`, etc. as column names, with one assertion per column.  Let me know how that works for you.

**Comment by naoro** [comment]
Thanks @typpo , it works!
