### ISSUE TITLE
Question: What models actually support the perplexity metric?

### ISSUE THREAD

**Issue by anoura12** [promptfoo/promptfoo#370]
Recently discovered that the perplexity metric has been added into the test assertions which is great and I wanted to try it out however, when I run the perplexity metric on the azure gpt 4 model, I get an error stating that the provider doesn't support logProbs. I believe gpt-4 should return logProbs - gpt-35-turbo doesn't which expectedly triggered an error. I was just wondering if you know what models work with this metric.

**Comment by typpo** [comment]
I've tested this with the 1106 models via OpenAI as it is a recent addition to their API.  I'm not sure Azure supports logprobs - maybe with their 1106 model versions?  However, promptfoo's Azure provider does not support this yet.

**Comment by typpo** [comment]
#376 adds support for logprobs/perplexity for Azure OpenAI chat completions.   This doesn't guarantee it'll work for all Azure models, but it means it will work when logprobs are available (probably for the 1106+ version of GPTs)

**Comment by typpo** [comment]
A change published in 0.35.0 adds `perplexity` support for Azure OpenAI models, if the models themselves support `logprobs`
