### ISSUE TITLE
Is there a way to assign a prompt file to a provider

### ISSUE THREAD

**Issue by NathanKarthik1996** [promptfoo/promptfoo#371]
I have 2 prompts of different structures and 2 custom providers to handle the different structures. I need to compare the results of the 2 custom providers, so if I were to add both custom prompts in the following format, I would end with a 2x2 matrix of results.

prompts: [prompt1.json, prompt2.json]
providers: [customProvider1.js, customProvider2.js]
tests: vars.csv

Instead, would it be possible to assign the prompt via the providers? E.g.:

providers:
    - id : customProvider1.js
            config:
                   prompt: prompt1.json
  - id : customProvider2.js
            config:
                   prompt: prompt2.json

**Comment by typpo** [comment]
Yes, this is possible.  I've updated the documentation to describe this here: https://promptfoo.dev/docs/configuration/parameters#different-prompts-per-model
