### ISSUE TITLE
HTML Output rendering does not have all information

### ISSUE THREAD

**Issue by NathanKarthik1996** [promptfoo/promptfoo#373]
Hello,

When I rendering my results to HTML the title of columns say object Object (I am using the custom provider). Is there a way I can get the provider instead, maybe the file name that I use could be better instead. Moreover, there is no information about what assertion type was executed against the test case as well. It would be nice to add that information as well.

**Comment by typpo** [comment]
Thanks for the report.  This is fixed in 0.35.1
