### ISSUE TITLE
Error when calling gemini-pro

### ISSUE THREAD

**Issue by zhlmmc** [promptfoo/promptfoo#374]
I'm setting the config like this:
providers:
- vertex:gemini-pro:
      id: gemini-pro
      config:
        apiKey: 
        projectId: 
        temperature: 0

But the runtime report the following error:
 {"error":{"code":429,"message":"Quota exceeded for aiplatform.googleapis.com/online_prediction_requests_per_base_model with base model: gemini-pro. Please submit a quota increase request. https://cloud.google.com/vertex-ai/docs/quotas.","status":"RESOURCE_EXHAUSTED"}}

After search google, it seems to be calling the wrong endpoint:
https://www.googlecloudcommunity.com/gc/AI-ML/Gemini-Pro-Quota-Exceeded/m-p/693185

I'm wondering if anyone has successfully called gemini-pro using promptfoo? Thanks!

**Comment by typpo** [comment]
Can you make sure you're on the latest version?  `gemini-pro` uses an API that is different from the `bison` models, and support was added a few versions ago in 0.32.0.

I am able to use `gemini-pro` locally with this setup: https://github.com/promptfoo/promptfoo/tree/main/examples/google-vertex

**Comment by zhlmmc** [comment]
yes, you are right. I was using the old version.
