### ISSUE TITLE
Question: Is it possible to pass Pinecone embeddings as context in promptfoo's RAG eval?

### ISSUE THREAD

**Issue by anoura12** [promptfoo/promptfoo#400]
Hey there, my LLM application uses Pinecone as RAG context to generate outputs. I was wondering if there's anyway to pass Pinecone embeddings as context in promptfoo so that the score I get gives a more accurate representation of my app's performance as opposed to directly putting text from my documents.

**Comment by typpo** [comment]
Hello!  I believe we spoke on Discord so I'm pasting the answer here:

Right now you have 2 options:

1) Include the context directly.  In other words, choose some examples that reflect the data in pinecone

2) Use a dynamic variable that calls your code to fetch from pinecone.  For example
```yaml
tests:
  - vars:
      context: file://context_fetcher.py
```
