### ISSUE TITLE
Add option to turn off Nunjucks engine

### ISSUE THREAD

**Issue by nimrodolev** [promptfoo/promptfoo#404]
Could we add an option to turn off Nunjucks templating? It's been messing me up 🙃 

### Usecase
I have a prompt that accepts fragments of file content - these files may be markdown files, code files, etc. I'm not using any Nunjucks templating - I'm constructing my prompts using JS files.

My problem is that the Nunjucks templating is causing issues - it's detecting all sorts of things in the files, which it thinks are opening tags (for example a line that contains `{# .somevalue }`), but because those aren't tags, it ends up throwing an exception and crashing the run.  It would be great to just have a flag to turn the templating off completely, for when it's not needed.

The only workaround I've found so far has been to just manually `{% raw %}` and `{% endraw %}` tags to the beginning and end of my example inputs, but this if very inconvenient and feels pretty silly to have to do.

You can imagine that even if it wasn't throwing errors, I'd want to be able to process files that _do_ contain Jinja2 templates without Nunjucks trying to process the tables and messing everything up.

**SIDE NOTE**: what made this whole thing way worse is that when this templating exception is thrown, there is no simple way to know which test case is the one that's causing the issue - I had to manually run them one by one to find the offender. Might be nice if exceptions could have some info about the test case they happened in.

**Comment by typpo** [comment]
#405 adds an environment variable `PROMPTFOO_DISABLE_TEMPLATING` that should solve your immediate need :)

**Comment by typpo** [comment]
This is included in release 0.37.0
