### ISSUE TITLE
Export Tokens/sec to .json

### ISSUE THREAD

**Issue by Wehzie** [promptfoo/promptfoo#409]
When exporting to `.json` format, information about multiple metrics such as 1) token usage 2) latency 3) total passed asserts is stored. For example the total number of passed asserts for a provider are stored under the json path `["results"]["table"]["head"]["prompts"][index]["metrics"]["assertPassCount"]`.

I'd collect these results to assemble a report. For this purpose it would be convenient to have tokens per second also available from a `.json` results file. It appears that currently the tokens/sec information is only available via the promptfoo web view.

**Comment by typpo** [comment]
To calculate tok/sec, I recommend just doing `metrics.tokenUsage.total / metrics.totalLatencyMs * 1000`

**Comment by Wehzie** [comment]
Thanks! I had assumed latency was related to the time it takes for the server to respond with a connection, not till completion was finished. Given the `a.xyz ms` format and switching between "," and "." as decimal vs thousand separators had me confused.

**Comment by typpo** [comment]
No worries :)
