### ISSUE TITLE
custom scripts for embedding 

### ISSUE THREAD

**Issue by ReverseFelicity** [promptfoo/promptfoo#411]
Hi,
    Is there any sample to do custom script for embedding in **similar** assertion? Because all LLMs and Embedding models are deployed and served internally. It's easy to write script to call them and llm custom script is working. Just have no idea how to do it with embedding models

**Comment by typpo** [comment]
Happy to provide an example.  Are you writing the script as a Javascript `ApiProvider` class, or are you using `exec`?

**Comment by ReverseFelicity** [comment]
> Happy to provide an example. Are you writing the script as a Javascript `ApiProvider` class, or are you using `exec`?

Hi typpo, thanks for reply. I managed to do it with ApiProvider :).  
`prompts: [prompts.txt]
providers:
  - ./customLLMProvider.js:
      id: custom-llm-provider
      config:
        url: https://xxxxx
tests:
  - description: Another basic substring check
    assert:
      - type: icontains
        value: "u"
      - type: similar
        value: "Bonjour qui êtes-vous ?"
        threshold: 0.1
    options:
      provider:
        embedding:
          id: ./customEmbeddingProvider.js
          config:
            url: https://xxxxx`
