### ISSUE TITLE
OpenRouter - Mixtral

### ISSUE THREAD

**Issue by rnehrboss** [promptfoo/promptfoo#413]
Great project guys.   Wonder if you have anyt thoughts on this.  I override the openai:chat in the yaml and use openrouter.  works great, except that any model that is Mixtral8x7b doesnt work, other models work.  Here is the output:

<img width="626" alt="Screenshot_2" src="https://github.com/promptfoo/promptfoo/assets/32110611/abd9ff78-404e-41bf-b72f-793123afa27f">

**Comment by rnehrboss** [comment]
maybe it's more of an issue about how I specify multiple models in the yaml?
providers: 
_____________
  - id: openai:chat:nousresearch/nous-capybara-7b    # or any other chat model
    config:
        apiBaseUrl: 'https://openrouter.ai/api'
        apiKey: sk-or-xxxxxxxxxxxxxxxx
  - id: openai:chat:nousresearch/nous-capybara-34b    # or any other chat model
    config:
        apiBaseUrl: 'https://openrouter.ai/api'
        apiKey: sk-or-xxxxxxxxxxxxxxx

**Comment by typpo** [comment]
Thanks for the catch!  I think it's an issue where the Mixtral API isn't totally consistent with the OpenAI API, and doesn't return token usage information.

#413 _should_ fix this, but I'm not able to test against OpenRouter specifically until later today :)

**Comment by rnehrboss** [comment]
Strange.. using openrouter, capy34b works, but not capy7b:
  - id: openai:chat:nousresearch/nous-capybara-7b # or any other chat model
    config:
        apiBaseUrl: 'https://openrouter.ai/api'
        apiKey: sk-xxx

  - id: openai:chat:nousresearch/nous-capybara-34b # or any other chat model
    config:
        apiBaseUrl: 'https://openrouter.ai/api'
        apiKey: sk-xxx

![image](https://github.com/promptfoo/promptfoo/assets/32110611/12c44ae1-07a6-4856-b531-4ec4cd4d882c)

**Comment by typpo** [comment]
Cool, I think this fix will take care of it. Will land it tonight

**Comment by rnehrboss** [comment]
Thanks for quick work.  any way I can test it for you now?

**Comment by typpo** [comment]
You'd have to clone this repo and follow the build steps in the readme

**Comment by rnehrboss** [comment]
Hey there.  Can I do a new npm install to test the fix?

**Comment by typpo** [comment]
This fix is included in release 0.37.1
