### ISSUE TITLE
Question:  Can I assert and test a value?

### ISSUE THREAD

**Issue by rnehrboss** [promptfoo/promptfoo#417]
For example if my returned text from the LLM always contained text like "Score: 90%"  or "Score:10%" and I wanted to make pass based on score>50% or something.

Possible?

**Comment by typpo** [comment]
Yep, you can do this in one of two ways:

1. With the `javascript` or`python` assertion type.  Write some code that parses the number out and assert that it's greater than the threshold score.

2. If you are doing this for many assertions, the [`postprocess` property](https://promptfoo.dev/docs/configuration/guide/#postprocessing) may come in handy.  

  You'll still have to write a little Javascript to parse the number from `output`.  Here's a one liner that I use:

  ```yaml
  postprocess: 'parseFloat(/\d+(?:\.\d+)?/.exec(output)?.[0])'
  ```
