### ISSUE TITLE
Add link to docs on www.promptfoo.dev

### ISSUE THREAD

**Issue by aantn** [promptfoo/promptfoo#420]
Not a bug, but it took me a little longer to find the docs than I'd like to admit. I would expect a link at the top right corner of the page, next to the github repo link.

Thanks for the awesome project

**Comment by typpo** [comment]
Thanks for the suggestion, this is done in https://github.com/promptfoo/promptfoo/commit/925976062f2e6fddb45748b519dd522322fafdf1
