### ISSUE TITLE
Improve docs for OpenAI messages protocol

### ISSUE THREAD

**Issue by aantn** [promptfoo/promptfoo#421]
Hi, I *think* I have this figured out now, but I wanted to document a point of confusion for me when first reading the docs.

The [OpenAI integration docs](https://www.promptfoo.dev/docs/providers/openai/#formatting-chat-messages) imply that input for chat models should be in the `{ "role" : "system", "content": "foo"}` JSON format. Yet the [Getting Started](https://www.promptfoo.dev/docs/getting-started) guide gives prompts as plain text. I get the impression both options are available and plain text messages are automatically wrapped in the equivalent JSON.

Is this correct?

**Comment by typpo** [comment]
Yes, you are correct :)

**Comment by aantn** [comment]
Thanks, feel free to close.

**Comment by typpo** [comment]
38bfdc4 improves the documentation on this point.  I appreciate the docs feedback, keep it coming!

**Comment by aantn** [comment]
Will do, thanks.
