### ISSUE TITLE
Allow configuration of delimiter

### ISSUE THREAD

**Issue by wodow** [promptfoo/promptfoo#424]
I was using `---` in some existing prompts, and was surprised by promptfoo's behaviour until I found https://www.promptfoo.dev/docs/configuration/parameters/#multiple-prompts-in-a-single-file

**Comment by typpo** [comment]
Thanks for the suggestion, this definitely has tripped other people before too.  I hope to completely remove this functionality one day, but for now 0722c70 adds a `PROMPTFOO_PROMPT_SEPARATOR` environment variable which you can use to alter this behavior.

**Comment by wodow** [comment]
Wonderful!
