### ISSUE TITLE
Feature Request: Ability to render markdown in results

### ISSUE THREAD

**Issue by aantn** [promptfoo/promptfoo#427]
Just a nicety :)

**Comment by aantn** [comment]
Some API would also work. (E.g. specify JS that is used to render each cell or specify a JS transformer that can return HTML)

**Comment by typpo** [comment]
This is actually available as of 0.37.0 under `Table Settings`!

![image](https://github.com/promptfoo/promptfoo/assets/310310/7487631c-dc30-4ec7-94ec-3e2fb5960291)

Note that you'll have to increase the max text length for the full rendering, otherwise some markdown may get cut off.

**Comment by aantn** [comment]
Thanks, I had searched for "markdown" in the docs before opening the issue. Happy to contribute to the docs if you can share instructions for how to build and test them locally.
