### ISSUE TITLE
Feature Request: Ability to give specific runs a name

### ISSUE THREAD

**Issue by aantn** [promptfoo/promptfoo#429]
I run Promptfoo a *lot* as I experiment. I'd like to refer back to specific runs, without going through the whole list. I'd love the ability to give specific runs custom names and to favorite them.

**Comment by typpo** [comment]
Makes a lot of sense.  Right now you can add a `description` at the top of your config file:

```yaml
description: 'Simple test'
```

This will display in the dropdown, which makes it a little easier to search and find.
![image](https://github.com/promptfoo/promptfoo/assets/310310/01086af0-bffb-478a-89a8-b6135177da1d)

**Comment by aantn** [comment]
Thanks, will be using that as a workaround.
