### ISSUE TITLE
OpenAI Assistant Evalauation

### ISSUE THREAD

**Issue by JohannesGlock** [promptfoo/promptfoo#431]
Hello, 
we are a team of 4 Student and are looking for a way to eval our openai assistant. We are not getting behind it how to check if the assistant is using our external files  which we passed to him or if the bot is hallucinating. We would love to get some help with that. When we want to use context-faithfulness what do we  have to pass to the question var ? 

Greetings Joe

**Comment by typpo** [comment]
Hi @JohannesGlock, were you able to get what you needed?  There is a guide on evaluating OpenAI assistants: https://promptfoo.dev/docs/guides/evaluate-openai-assistants/ and you can also check out the RAG guide to learn how to use external files in the context: https://promptfoo.dev/docs/guides/evaluate-rag

**Comment by JohannesGlock** [comment]
Yes thanks a lot!! . But we are still on it because we are struggeling on how to include more context. There seems to be maximum words for context. As we want to get the context-faithfulness  😀
