### ISSUE TITLE
Question: OpenAI Assistant 

### ISSUE THREAD

**Issue by JohannesGlock** [promptfoo/promptfoo#434]
To evaluate our OpenAI Assistant we included our context into the yaml file. But there is very low capacity of word we can use. You can pass around 32000 word into the context. This is not enough to evalaute the Assistant which uses a document with let´s say 200.000 word. 

Is there any workaround to get bigger context windows ? 

Thank you!

**Comment by JohannesGlock** [comment]
<img width="825" alt="Bildschirmfoto 2024-01-31 um 18 45 06" src="https://github.com/promptfoo/promptfoo/assets/117032423/0590c937-447c-4a8d-b620-e8da0a53e688">

**Comment by typpo** [comment]
Hi Johannes, the context window is a property of the model, it's not set by promptfoo.  You will have to adjust the context size to fit with whichever model you're using.

**Comment by typpo** [comment]
Closing this out for now - let me know if you run into any issues on the promptfoo side!
