### ISSUE TITLE
Fix Request: "Show Failure only" adjustement

### ISSUE THREAD

**Issue by theodelobelle** [promptfoo/promptfoo#436]
Hello ! I know it wont the game changing feature, but more Quality of Life feature

Supose you have two prompt an you tick " Show Falure only"

| Prompt 1 | Prompt 2 |
|----------|----------|
|   ✅     |    ❌    |
|   ✅     |    ❌    |
|   ❌     |    ✅    |
|   ✅     |    ❌    |
|   ❌     |    ✅    |

- Then hide the column Prompt 1 
In the current state we have  :

| Prompt 2 |
|----------|
|    ❌    |
|    ❌    |
|    ✅    |
|    ❌    |
|    ✅    |

Instead of only  this : 
| Prompt 2 |
|----------|
|    ❌    |
|    ❌    |
|    ❌    |

thanks

**Comment by typpo** [comment]
Thanks for pointing this out!  This is fixed in af949db1f2a5125596a30816f97f0fcb29bc5ea7.  If a column is hidden, its failures won't be counted when deciding whether to display the row.
