### ISSUE TITLE
Documentation is missing.

### ISSUE THREAD

**Issue by santicomp2014** [promptfoo/promptfoo#441]

**Comment by typpo** [comment]
What are you trying to do that isn't documented?  https://promptfoo.dev/docs/intro

**Comment by santicomp2014** [comment]
![image](https://github.com/promptfoo/promptfoo/assets/9823189/b613fcde-1f45-4980-9daa-2935e63efc1a)

I think the antivirus blocked the page, I tested it out in another PC and it worked, go figure.

I wanted to read the Guide and references, I though the website was down, but It was my connection.

**Comment by typpo** [comment]
Ah ok. No problem!
