### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by santicomp2014** [promptfoo/promptfoo#442]
Hello, I was looking at this project thru a YouTube video that showcased it https://www.youtube.com/watch?v=KhINc5XwhKs&t=878s
I was about to test it out and looking for some more info I found the website down.

Could there be an issue with the domain https://promptfoo.dev/docs/intro ?

Thank you.
Excellent work by the way.

**Comment by typpo** [comment]
I think it might just be you?  The URL https://promptfoo.dev/docs/intro loads ok for me and on https://downforeveryoneorjustme.com/promptfoo.dev?proto=https

**Comment by typpo** [comment]
Resolved in #441
