### ISSUE TITLE
Do we have native support for cohere AI models?

### ISSUE THREAD

**Issue by gillsgills** [promptfoo/promptfoo#453]
Hi! First of all I am sorry for asking two questions in short term. I am quite new here.

I wonder if we have native support for cohere AI, another big name in the field? Or so far we need to write our local python scripts for the models from them via [this guideline](https://www.promptfoo.dev/docs/providers/custom-api)?

**Comment by typpo** [comment]
You're correct that there isn't native support for Cohere right now.  But, it shouldn't be too difficult to implement native support - this is something I can help with.

Are you interested in the `chat` endpoint specifically? https://docs.cohere.com/reference/chat

**Comment by typpo** [comment]
Native support for Cohere Chat API is available in 0.40.0!  See https://promptfoo.dev/docs/providers/cohere

**Comment by gillsgills** [comment]
@typpo So many thanks! I will give it a shot very promptly. If there is any other problem encountered, I will open separate issue.
