### ISSUE TITLE
Allow progress bar in debug/verbose mode

### ISSUE THREAD

**Issue by naoro** [promptfoo/promptfoo#458]
A progressbar is helpful even in debug mode.

I think that disconnecting the two will be helpful.

Ref: https://github.com/promptfoo/promptfoo/blob/2a8eb9349bb7d041ca22439a98820039ee7e1edf/src/main.ts#L544

**Comment by typpo** [comment]
The reason for this logic is that there cannot be CLI output while the progress bar is dynamically updating, otherwise it gets mangled/overwritten by the bar.

**Comment by naoro** [comment]
I think seeing the progress while seeing the debug values has higher value than hiding it:
When I debug, and something happens after 1000-2000 (like unresponsiveness, or empty results, etc' - the sort of things that debug exists for..)
I still want to know *when* it happens, and I still want to see - in the happy path - that I'm nearing the end of the processing.

**Comment by naoro** [comment]
In general, I think that debug/verbose mode should mostly just add information

**Comment by typpo** [comment]
#461 adds progress information in debug output :)
