### ISSUE TITLE
View server

### ISSUE THREAD

**Issue by matallanas** [promptfoo/promptfoo#462]
Hi, I was trying to create a self-hosted server with promptfoo so anyone can execute it. However, I was run some local eval from the ui and I am having a `500: Internal Server Error`. Any clue about what is happening inside? 
Thank you in advance

**Comment by typpo** [comment]
Any output on the server side?  Can you provide more information about the request that is returning the 500?

**Comment by matallanas** [comment]
The error that I am getting is that is not getting to fetch the api.
`TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: getaddrinfo ENOTFOUND auth
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
      at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'auth'
  }
}
- error {
  message: 'TypeError: fetch failed',
  details: 'TypeError: fetch failed\n' +
    '    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  hint: '',
  code: ''
}`

I tried to put all the variables that you indicated in for the supabase, also the api and app but still not reaching it. I also create the docker following the one provided in the repository. I checked the api and it seems is up but the view cannot reach it. Any tip to solve this?

**Comment by typpo** [comment]
The Dockerfile released in 0.42.0 contains updates that should resolve issues with self-hosting the share functionality described here: https://promptfoo.dev/docs/usage/sharing/#self-hosting.  Please let me know if not the case
