### ISSUE TITLE
Add bedrock:completion:anthropic.claude-v2.1

### ISSUE THREAD

**Issue by wuodar** [promptfoo/promptfoo#469]
As in title

**Comment by typpo** [comment]
I don't think I have access to this model yet - what is the current behavior when you try to run it with promptfoo?

**Comment by wuodar** [comment]
I think it should be added here: https://github.com/promptfoo/promptfoo/blob/bc83295b59c307b4764d14af6fd15ad2a78d8541/src/providers/bedrock.ts#L67

Currently I'm getting "TypeError: Cannot read properties of undefined (reading 'params') TypeError: Cannot read properties of undefined (reading 'params') at AwsBedrockCompletionProvider.callApi"

**Comment by wuodar** [comment]
But this'll be more complicatede - claude v2.1 supports system prompts (no "Human:" at the beggining of the prompt).

**Comment by typpo** [comment]
#470 solves the error at least - so you can use claude-2.1 without a system prompt.  

As for supporting system prompt, what do you think is the best way?  Some thoughts:
  - Completely remove the logic that prepends `Human:` and appends `Assistant:`.  This means that users will have to set custom prompts for Anthropic, but minimizes the amount of magic stuff that's happening
  - Support OpenAI-style `role`, `content` JSON objects
  - Some other approach?

**Comment by wuodar** [comment]
Adding `Human:` `Assistant:` is similar to langchain - we could try to map langchain solution to promptfoo codebase. From the other side, I agree that this "magic" isn't something I like in langchain. And we have functionality that adds prefix/suffix to the prompt in promptfoo if I remember correctly. So probably good documentation without "magic stuff" sounds reasonable.

**Comment by typpo** [comment]
Closing this out as this format is now legacy with Claude 3
