### ISSUE TITLE
Bedrock anthropic Claude v2 - `llm-rubric produced malformed response:`

### ISSUE THREAD

**Issue by wuodar** [promptfoo/promptfoo#471]
If I understand correctly, grader response for llm-rubric should be json? Fun fact that I'm getting this error with 2 of 3 prompts used for evaluation - claude was trained on XML data, so it might not follow guidelines

**Comment by typpo** [comment]
The Anthropic grader has been improved to use tools.  And Claude 3-3.5 is much better!  Let me know if this continues to be a problem.
