### ISSUE TITLE
error with `promptfoo view`

### ISSUE THREAD

**Issue by romaintoub** [promptfoo/promptfoo#488]
I am trying to run `promptfoo view` but I am getting the following error
<img width="969" alt="image" src="https://github.com/promptfoo/promptfoo/assets/64668750/fcecd59b-1f50-4d6c-8b51-cf9143462e68">

versions I am using:
- Node.js `v21.6.1` (tried with `v20.11.0`)
- promptfoo `0.42.0`

**Comment by typpo** [comment]
Can you check if you have another instance of `promptfoo view` running in the background?

Otherwise, you'll have to find what's running on port 15500.  Depending on your operating system, usually this can be done with some variation of the `netstat` command.

**Comment by romaintoub** [comment]
ah good catch! I had promptfoo view opened in one of my million tabs, thank you!
