### ISSUE TITLE
Do you know of any packages or frameworks similar to promptfoo?

### ISSUE THREAD

**Issue by Keiku** [promptfoo/promptfoo#49]
I was looking for something just like promptfoo. Do you know of any packages or frameworks similar to this? I would like to consider other comparisons.

**Comment by ryanpeach** [comment]
I also would like to know.

**Comment by typpo** [comment]
Unfortunately not really.  I built this because there wasn't anything else out there that did what I needed it to do.  OpenAI does have an [Evals](https://github.com/openai/evals) framework you can take a look at.  Its focus is on testing OpenAI models with heavier test cases, and some of the more advanced test cases require Python implementation.

**Comment by ryanpeach** [comment]
The main thing I need is this but in python with langchain compatibility. It might be worth cloning and converting.

**Comment by Keiku** [comment]
As far as I know, `QAEvalChain` in `langchain` module might be useful to me. I'm still looking to see if there are other alternatives.

**Comment by Keiku** [comment]
@typpo Thanks for the link reference.

**Comment by typpo** [comment]
For those of you working in Python, have a look at the end-to-end LLM chain testing documentation: https://www.promptfoo.dev/docs/configuration/testing-llm-chains#end-to-end-testing-for-llm-chains

Specifically, I've recently created an example that shows how to evaluate a Python LangChain implementation: https://github.com/promptfoo/promptfoo/tree/main/examples/langchain-python

The example compares raw GPT-4 with LangChain's LLM-Math plugin by using the `exec` provider to run the LangChain script:
```yaml
# ...
providers:
  - openai:chat:gpt-4-0613
  - exec:python langchain_example.py
# ...
```

The result is a side-by-side comparison of GPT-4 and LangChain doing math:

![langchain gpt-4 eval](https://www.promptfoo.dev/assets/images/langchain-eval-1c44c280e70607b6c1682aa03ee33074.png)

Hope this helps your use cases.  If not, interested in learning more.

Side note - `QAEvalChain` is similar in approach to the `llm-rubric` assertion type of promptfoo.  It can help evaluate whether a specific answer makes sense for a specific question.

**Comment by Keiku** [comment]
It looks like it was released recently.
[hegelai/prompttools: Open-source tools for prompt testing and experimentation ](https://github.com/hegelai/prompttools/tree/main)

**Comment by karrtikiyer** [comment]
@typpo : First of all congratulations on the great work in building this library. It would be great if we can have some way to directly compare and contrast `promptfoo` with `prompttools` and `evals by OpenAi`. This will make life easier for consumers to pick & choose best among these based on the usecase.
