### ISSUE TITLE
Cannot set environment variables in self-hosted share server

### ISSUE THREAD

**Issue by eyubloxer** [promptfoo/promptfoo#495]
**Issue**

I cannot seem to get the environment variables to be recognized when I build and run a self-hosted share server. Specifically, I am trying to use the store type: filesystem. 

**Steps to Reproduce:**

1. Build server container image 
2. `docker run -d -p 3000:3000 -e PROMPTFOO_SHARE_STORE_TYPE=filesystem -v $(pwd)/share-store:/app/share-store promptfoo-ui:latest node server.js`
3. `PROMPTFOO_REMOTE_API_BASE_URL=http://localhost:3000/api PROMPTFOO_REMOTE_APP_BASE_URL=http://localhost:3000 npx promptfoo share -y`

**Expected Behavior:**

The share file is written to the volume mounted: `$(pwd)/share-store`

**Actual Behavior:**

I'm able to view the share link, but the application isn't using the env `PROMPTFOO_SHARE_STORE_TYPE=filesystem` and defaults to type memory instead.

I would really appreciate any assistance on this!

**Comment by typpo** [comment]
Thanks for raising this issue.  Please give it a try with 0.43.1, which has the fix #498

**Comment by eyubloxer** [comment]
Thanks for the quick turnaround!  
Tested and confirm it works on my end too 👍🏽
