### ISSUE TITLE
Problem using is-valid-openai-tools-call assertion

### ISSUE THREAD

**Issue by dprentis** [promptfoo/promptfoo#499]
When using the `is-valid-openai-tools-call` assertion, if gpt returns plain text, there is no response object. It therefore not possible to determine the llms actual output.

Currently working around by using `is-json` + custom javascript assertions.

**Comment by typpo** [comment]
If I understand your issue correctly, #541 will fix this problem by allowing other assertions when GPT returns plaintext instead of a tools call.  Fix will be in the next release.

**Comment by typpo** [comment]
Released in 0.46.0
