### ISSUE TITLE
Failed to evaluate ollama model

### ISSUE THREAD

**Issue by longcw** [promptfoo/promptfoo#501]
When evaluate ollama model response failed with `{"error":"invalid options: basePath"}`
```
Calling Ollama API: {"model":"openchat:7b","messages":[{"role":"user","content":"Answer the question: What's your name?"}],"options":{"basePath":""}}
Calling Ollama API: {"model":"openchat:7b","messages":[{"role":"user","content":"Answer the question: Hello"}],"options":{"basePath":""}}
        Ollama generate API response: {"error":"invalid options: basePath"}
Eval #1 complete (1 of 2)
        Ollama generate API response: {"error":"invalid options: basePath"}
Eval #2 complete (2 of 2)
```

I have tried both 0.43.1 and installing from github, and also found this PR that tried to fix this issue: https://github.com/promptfoo/promptfoo/pull/480. But for some reason the problem is still there?

My config is like the following
```yaml
description: 'My first eval'

prompts:
  # - file://prompt1.json
  - "Answer the question: {{question}}"

providers:
  - ollama:chat:openchat:7b

tests:
  - vars:
      question: What's your name?
    assert:
      - type: equals
        value: Hello, How may I assist you today?
  
  - vars:
      question: Hello```

**Comment by typpo** [comment]
Can you share the output of `promptfoo --version`?

**Comment by longcw** [comment]
@typpo Yes sure.
```bash
$ promptfoo --version
(node:3222913) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
0.43.1
```

**Comment by typpo** [comment]
Ah I see the problem.  Thanks for flagging, will get a fix in

**Comment by typpo** [comment]
#506 should fix, although I have not yet had the chance to test locally yet.  The fix in #480 affected the text completion code path, not the chat completion path.

**Comment by longcw** [comment]
@typpo Thank you so much! How can I test it with the latest version? I have tried to uninstall promptfoo and reinstall it from github with `npm install github:promptfoo/promptfoo` but the problem is still there.

**Comment by longcw** [comment]
Update: the latest version 0.44.0 worked.

**Comment by palladius** [comment]
Same here. I have 

```
$ promptfoo --version
0.96.0
$ ollama --version
ollama version is 0.3.9
```

Error I get:
```
API call error: Error: Request failed after 4 retries: fetch failed. Output:
undefined
```

**Comment by typpo** [comment]
@palladius can you run with `--verbose` and share the debug output?
