### ISSUE TITLE
Feature Request: How to evaluate Azure Open AI Assistant

### ISSUE THREAD

**Issue by jagratimodi** [promptfoo/promptfoo#502]
Currently in config we can provide only Open AI assistant ID. 

It would be good if we can also provide Azure Open AI assistant ID and evaluate it,

Example - 

providers: 
- id: azureopenai:assistant:asst_fEhNN3MClMamLfKLkIaoIpgB
     config:
       apiHost: 'xxxxxxxx.openai.azure.com'

This does not work and gives below error -

>npx promptfoo@latest eval
C:\Users\Jagrati.Modi\AppData\Local\npm-cache\_npx\81bbc6515d992ace\node_modules\promptfoo\dist\src\providers.js:173
            throw new Error(`Unknown Azure OpenAI model type: ${modelType}. Use one of the following providers: azureopenai:chat:<model name>, azureopenai:completion:<model name>`);

**Comment by FJLopezGarcia** [comment]
Try with this

  - id: azureopenai:chat:csdep-gpt4
    config:
      apiHost: cs-oi-yyyyyy-testing.openai.azure.com
      apiKey: 984681cXXXXXXXc20d22YYdf2a7

**Comment by pboiii** [comment]
> Try with this
> 
> * id: azureopenai:chat:csdep-gpt4
>   config:
>   apiHost: cs-oi-yyyyyy-testing.openai.azure.com
>   apiKey: 984681cXXXXXXXc20d22YYdf2a7

Isn't this only for a model deployment, not an assistant?

**Comment by typpo** [comment]
#577 adds support for OpenAI assistants on Azure!

**Comment by typpo** [comment]
Published in [0.49.0](https://github.com/promptfoo/promptfoo/releases/tag/0.49.0)

https://promptfoo.dev/docs/providers/azure/#assistants
