### ISSUE TITLE
Could we get nunjucks and nunjucksFilters enabled for rubricPrompt?

### ISSUE THREAD

**Issue by manu3b1** [promptfoo/promptfoo#509]
I'm crafting a rubricPrompt but except variable expansion, no way to use any high level features of standard prompt, like nunjucks runtime and custom nunjucksFilters based on javascript.
By example, I would like to extract and post-process fields from a JSON output before analyzing them with a custom Model-graded metric.

**Comment by manu3b1** [comment]
Oops, looks like "options.transform" could help much.

**Comment by manu3b1** [comment]
Let' forget.

**Comment by typpo** [comment]
That's a good suggestion - I've opened a PR that updates the `context` part of the transform function to include information about the prompt: https://github.com/promptfoo/promptfoo/pull/512

**Comment by manu3b1** [comment]
Good idea! I will do all the stuff at transform level to generate a crafted output. Thx!

**Comment by manu3b1** [comment]
Works well, thank you @typpo !
