### ISSUE TITLE
Can not replicate consistants behavior of "promptfoo view" in self hosted app.

### ISSUE THREAD

**Issue by RayannBen** [promptfoo/promptfoo#510]
I tried to self host the app and noticed that with the default app memory option, the labels' modifications done in the ui did not remain, unless shared with the "Share" option which generates another link. 

Also, when an evaluation is sent to the local backend, it disappears when the app is stopped and run again, which is not the case when shutting down the server raised by the "promptfoo view" command.

I believed I had to provide memory to my app and tried to set the "PROMPTFOO_SHARE_STORE_TYPE" to "filesystem" and give a dedicated folder.

It does not seem to have changed much, even though once i run the docker image i get a log stating "Using Filesystem store" and in both cases (memory and filesystem storage),when I share an evaluation, I can see a line "Storing eval result with id f:caf6b..." written in my CLI. 

How can I add consistency to the evals I share to keep them when i shut down the app, and when they are modified in the UI so that I do not need to generate another link everytime ?

**Comment by typpo** [comment]
Filesystem storage type should solve this problem. Are you sure you are
mapping the docker volume to a persistent location on the host machine,
using the -v arg for docker run?
