### ISSUE TITLE
Persist changes on self-deployed UI without sharing a new link

### ISSUE THREAD

**Issue by NoAchache** [promptfoo/promptfoo#513]
Hello, I am trying to setup promptfoo for my organisation and hence using the self-deployed option.

I want to be able to alter the labels manually in the UI and persist the changes, without having to create a new link. Is it possible?

I am using the file-system store

**Comment by typpo** [comment]
#538 implements this.  Worth noting that this means _anyone_ with access can make changes.  User accounts/ACL/etc are future projects, but hope this helps in the meantime.
