### ISSUE TITLE
Huggingface Api key through config results in error call

### ISSUE THREAD

**Issue by llorenzinho** [promptfoo/promptfoo#515]
When using api key in configurations for an huggingface provider ([Tinyllama](https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0)), the call results in the following error:
`API call error: The following model_kwargs are not used by the model: ['apiKey'] (note: typos in the generate arguments will also show up in this list)`

I suppose that the api key should be removed from configurations when the package makes the api call and should be used only in headers.

**Comment by llorenzinho** [comment]
Thank you for your wor

**Comment by typpo** [comment]
Fix released in 0.44.0
