### ISSUE TITLE
assertion pass when it should'nt

### ISSUE THREAD

**Issue by mobidyc** [promptfoo/promptfoo#516]
As you can see in the screenshot, the answer should pass when the result contains 72, 
but gpt4 answers 73, which is not the expected value.
Maybe a mix between string and number but it's confusing.

![image](https://github.com/promptfoo/promptfoo/assets/1949589/9bf4cb43-2c0a-42e7-8384-7c7b23ddf28d)

**Comment by mobidyc** [comment]
damn yaml, I missed a tab and the assertion was seen as a variable...
sorry for the noise

**Comment by typpo** [comment]
yaml problems :(  it happens
