### ISSUE TITLE
HTTP 500 error upon clicking "Run Evaluation" on the UI

### ISSUE THREAD

**Issue by jkng10** [promptfoo/promptfoo#522]
Hi all,

when deploying promptfoo as docker container **without** Supabase, I get a HTTP 500 upon clicking "Run Evaluation" on the web UI.

![image](https://github.com/promptfoo/promptfoo/assets/158186135/423a8b6b-df84-4c10-87d2-ef86b20a7476)

I assume it's related to the Dockerfile and the configuration related to Supabase, as promptfoo tries to access the placeholder content which can be seen in the docker container log.

![image](https://github.com/promptfoo/promptfoo/assets/158186135/01fe2bf2-dc14-485f-99be-2cb91f6d3f3c)

How should the Dockerfile correctly look like when Supabase should not be used?

Thanks in advance!

**Comment by typpo** [comment]
Support for running evals in self-hosted webui is added in #540.  This will be in the next published release!

**Comment by typpo** [comment]
Released in 0.46.0

**Comment by jkng10** [comment]
Thanks a lot @typpo ! 👍
