### ISSUE TITLE
Huggingface providers does not need apiKey to get the response

### ISSUE THREAD

**Issue by llorenzinho** [promptfoo/promptfoo#525]
While using the node package, i'm able to run tests without setting the apiKey with some Hugginface providers:

- tinyllama
- openchat
- mistral
- bloom

I'm running the service in k8s and i'm sure that the `HF_API_TOKEN` env var is not set.
The same behaviour while running tests using the cli.

I suppose this is not an issue of the package itself. If so, please forgive me about this issue and just close it.

**Comment by typpo** [comment]
This is expected. Huggingface allows unauthenticated use of some of its
APIs. For reliability, I recommend always using an API key.
