### ISSUE TITLE
__expected column doesn't support blank cells

### ISSUE THREAD

**Issue by josephmermel** [promptfoo/promptfoo#53]
In the CSV test format, you cannot use the __expected column unless you have an assertion for every case. If some case has no assertion, the code adds an empty assertion which will fail the case.
Would be easy to fix by checking for truthy `value` before adding to asserts, in this code:
https://github.com/promptfoo/promptfoo/blob/792a5aa5a7b7cdf66513733fbd3fd07185e92413/src/util.ts#L350

**Comment by typpo** [comment]
Thanks!  This is fixed in [d398866](https://github.com/promptfoo/promptfoo/commit/d3988666d95528f36c85165509bf634d8848da83) and will be published in the next release.

**Comment by typpo** [comment]
This is fixed in version 0.17.0
