### ISSUE TITLE
can not load txt file in vars

### ISSUE THREAD

**Issue by zhlmmc** [promptfoo/promptfoo#534]
using promptfoo 0.45.1
  vars: 
    prompt: file://testcases/015_simple_mahjong_prompt.txt

will get error:
![image](https://github.com/promptfoo/promptfoo/assets/1726527/9119471c-f8b4-4165-9c2c-11c44729c68c)

it worked before.

**Comment by typpo** [comment]
Which Anthropic provider are you using?  I'm guessing this is related to #526.  Could you try specifying your provider as `anthropic:completion:modelname`?

**Comment by typpo** [comment]
Should be fixed in 0.46.0
