### ISSUE TITLE
Support Messages api in Bedrock for anthropic v3+

### ISSUE THREAD

**Issue by naoro** [promptfoo/promptfoo#543]
It's now supporting only messages API which is to be called like this:

```typescript
async function main() {
  const message = await client.messages.create({
    model: 'anthropic.claude-3-sonnet-20240229-v1:0',
    max_tokens: 256,
    messages=[{"role": "user", "content": "Hello, world"}]
  });
  console.log(message);
}
```

Looks like it's using same api as Anthropic provider which supports {{system_prompt}}: 
https://github.com/promptfoo/promptfoo/blob/main/site/docs/providers/anthropic.md#latest-api-messages

additional data:
https://docs.anthropic.com/claude/reference/claude-on-amazon-bedrock
https://community.aws/content/2dJmYpKlFNh6NOeC71GIZWZkfST/use?lang=en

**Comment by typpo** [comment]
Published in [0.49.0](https://github.com/promptfoo/promptfoo/releases/tag/0.49.0)!

**Comment by naoro** [comment]
I think there's a bug in split of model id using `:` , it doesn't send the last ":0" therefore it doesn't hit the correct endpoint.
it's in 
https://github.com/promptfoo/promptfoo/blob/94425e9a55e7dc1537d37b576b72bdf9af1e069a/src/providers.ts#L208
 I believe

**Comment by typpo** [comment]
I see what you mean.  As a temporary workaround, I think you can specify it like so:
```
bedrock:completion:anthropic.claude-3-haiku-20240307-v1:0
```
