### ISSUE TITLE
response error while using replicate's Private model

### ISSUE THREAD

**Issue by abrar-tericsoft** [promptfoo/promptfoo#546]
![crop](https://github.com/promptfoo/promptfoo/assets/159236680/6b9f9c1c-b4cd-486b-a341-81ed3bec7c7a)

here is the replicate's model link : https://replicate.com/abrar-tericsoft/mistral
what type of error is this?

**Comment by typpo** [comment]
The implementation expects a list of strings in `output` object, which is what most popular models return, but it looks like this endpoint is returning a string.

#547 adds support for string responses.

**Comment by abrar-tericsoft** [comment]
Thank you for support @typpo

**Comment by typpo** [comment]
Published in 0.47.0!
