### ISSUE TITLE
How to generate separate report or a breakdown report per test suite instead of just one single report for all test suites?

### ISSUE THREAD

**Issue by genandre** [promptfoo/promptfoo#559]
For example, for the following configuration, how do I generate the report such that I get separate stats for each test-suite instead of combined stats for all test-suites.

```
prompts: [prompt.json]

providers:
  - providers/my-provider.js:

tests:
  - tests/generation/test-suite1.yaml
  - tests/generation/test-suite2.yaml
```

**Comment by typpo** [comment]
Hmm, I would probably just run them as separate evals.  Is there a reason you want to run them all together, but keep the stats separate?

**Comment by typpo** [comment]
Closing this out for now, feel free to reopen with your thoughts on this!
