### ISSUE TITLE
Feature Request: Add max_tokens config to Azure OpenAI provider

### ISSUE THREAD

**Issue by carlost** [promptfoo/promptfoo#560]
You cannot configure max_tokens as a config option to Azure OpenAI providers. As of now the only way that I can set this is via the OPENAI_MAX_TOKEN env var.

options interface: https://github.com/promptfoo/promptfoo/blob/main/src/providers/azureopenai.ts#L14-L57

line in azure openai providers source where max_tokens is set to env or 1024: 
- AzureOpenAiCompletionProvider: https://github.com/promptfoo/promptfoo/blob/main/src/providers/azureopenai.ts#L241
- AzureOpenAiChatCompletionProvider: https://github.com/promptfoo/promptfoo/blob/main/src/providers/azureopenai.ts#L326

It would be pretty awesome to be able to control that via provider config options.

**Comment by typpo** [comment]
Nice catch.  #561 adds this param.  It'll be in the next release!

In the meanwhile, as a workaround, you can set
```yaml
config:
  passthrough:
    max_tokens: 2048
```
in the provider config.  `passthrough` will just blindly send whatever's in it to the API.

**Comment by carlost** [comment]
@typpo (first of all ... awesome username) thanks for the heads up on passthrough!

**Comment by typpo** [comment]
Released in [0.48.0](https://github.com/promptfoo/promptfoo/releases/tag/0.48.0)!
