### ISSUE TITLE
Mistral provider is hard-coded to https://api.mistral.ai/v1/chat/completions

### ISSUE THREAD

**Issue by jvert** [promptfoo/promptfoo#567]
There is no way for the Mistral provider to override the API URL. So you can't test against, for example, Mistral hosted on Azure. It would be ideal if this provider supported the `apiHost`, `apiBaseUrl`, and `apiKeyEnvar` configuration parameters like the OpenAI provider does.

If there's interest, I can work on a PR for this.

**Comment by typpo** [comment]
Would definitely merge a PR for this.  Feel free to take a stab at it!
