### ISSUE TITLE
Use promptfoo for output evaluation/visualisation but not inferencing?

### ISSUE THREAD

**Issue by magdalena-mladenova-veeva** [promptfoo/promptfoo#569]
Thank you for the fantastic tool! 

If I understand it correctly, promptfoo sends an API call to a model, then evaluates/visualises model outputs. Is it possible to de-couple the two steps & only employ it for evaluation, given model output?

**Comment by typpo** [comment]
Hi Magdalena,

You can try the standalone assertions feature: https://promptfoo.dev/docs/configuration/expected-outputs/#running-assertions-directly-on-outputs.  This lets you run outputs directly against a list of assertions and view the results.

Let me know if this fits what you're looking for!

**Comment by magdalena-mladenova-veeva** [comment]
This is great, thank you! 

In the above set-up, a list of outputs are provided & subsequently shown in separate rows in the resulting evaluation table. Would there by any way to specify metadata about each output (e.g. model/prompt it was created with) & show these side-by-side rather than on separate rows?

**Comment by typpo** [comment]
#581 implements this feature in a very basic way.  Right now it allows you to specify your output JSON like this:

```json
[
  {"output": "Hello world", "tags": ["foo", "bar"]},
  {"output": "Greetings, planet", "tags": ["baz", "abc"]},
  {"output": "Salutations, Earth", "tags": ["def", "ghi"]}
]
```

And the tags are shown in the web UI as a comma-separated list.

In the future this feature can certainly be improved, but hope it helps for now.  It will be included in the next published release.

**Comment by typpo** [comment]
Published in [0.49.0](https://github.com/promptfoo/promptfoo/releases/tag/0.49.0)!

**Comment by magdalena-mladenova-veeva** [comment]
Thank you so much!

**Comment by magdalena-mladenova-veeva** [comment]
Was missing the matrix view in this setting, and I just realised that one can use a custom script (e.g. following https://promptfoo.dev/docs/providers/python), where instead of calling their app API, they use the function to open up pre-existing model results. Just adding it here in case others might find it helpful as well :)
