### ISSUE TITLE
Feature Request: CLI command to retrieve results after manual labelling in csv file

### ISSUE THREAD

**Issue by NoAchache** [promptfoo/promptfoo#572]
Hello, would it be possible to add a CLI to download the results from an experiment in the web UI, ideally in a csv file (rather than manually fetching the json files). Ideally the columns would be:
- the prompt
- the variables
- the score
- the result (pass / fail)
- Whether the result is a manual label or not (this one is very important)

**Comment by typpo** [comment]
Yes, this should be fairly straightforward.  I can add this to https://github.com/promptfoo/promptfoo/pull/482

**Comment by typpo** [comment]
Change was released in [0.50.0](https://github.com/promptfoo/promptfoo/releases/tag/0.50.0)
