### ISSUE TITLE
Integration of Google VertexAI gcloud auth

### ISSUE THREAD

**Issue by romaintoub** [promptfoo/promptfoo#573]
Hi!

So far for VertexAI users, the `VERTEX_API_KEY` must be provided as described here: https://www.promptfoo.dev/docs/providers/vertex

However its not really following best practices for GCP users and hard to implement for CI/CD
Would there be a way to use the google client client to authenticate with gcp projects without providing any API key? I see there are some google cloud node.js libraries: https://github.com/googleapis/google-cloud-node but I am not sure what would be the best way to implement this

**Comment by typpo** [comment]
Thanks for the suggestion.  Based on my understanding, we'd need to switch over to a client library for vertex AI and/or REST authentication with application default credentials ([docs](https://cloud.google.com/vertex-ai/docs/workbench/reference/authentication#client-libraries)).  That probably means using [`google-auth-library`](https://github.com/googleapis/google-auth-library-nodejs)

**Comment by typpo** [comment]
#580 updates the provider to use Application Default Credentials

This means a machine that is properly configured with a service account, or logged into the gcloud CLI, should "just work"

Will be included in the next published release!

**Comment by romaintoub** [comment]
amazing, thanks a lot!

**Comment by typpo** [comment]
Published in [0.49.0](https://github.com/promptfoo/promptfoo/releases/tag/0.49.0)!
