### ISSUE TITLE
Save evals directly in self-hosted machine

### ISSUE THREAD

**Issue by NoAchache** [promptfoo/promptfoo#578]
How to save evals run locally in a self hosted machine?

The documentation only indicates how to use the self hosted machine with promptfoo share: https://www.promptfoo.dev/docs/usage/self-hosting

**Comment by typpo** [comment]
Evals are actually saved directly on the self-hosted machine already.  They are written to `/root/.promptfoo` on the docker image.  You can persist the volume by passing an argument like `-v /path/to/local_promptfoo:/root/.promptfoo` to `docker run`.

I've updated the documentation to explain this better in [2a57f4d](https://github.com/promptfoo/promptfoo/commit/2a57f4d45160f14194c33f359959d62e421a2f77).

Let me know if you have any other qs!

**Comment by NoAchache** [comment]
Hi, but what if promptfoo is deployed in another machine?

My team and myself want to be able to run the eval in their own machine and push the results to a machine which serves the promptfoo server.

Also for security reasons we cannot directly ssh to the other machine to manually copy the results and we can only reach predefined ports.
