### ISSUE TITLE
Save evals in self hosted machine when running it from another machine

### ISSUE THREAD

**Issue by NoAchache** [promptfoo/promptfoo#585]
[Continuation of past issue as I do not seem to be able to reopen it: promptfoo/promptfoo/issues/578]

My team and myself want to be able to run the eval in their own machine and push the results to a machine which serves the promptfoo server.

Also for security reasons we cannot directly ssh to the other machine to manually copy the results and we can only reach predefined ports.

**Comment by typpo** [comment]
I understand what you're saying.  Right now `promptfoo share` is the best way to do this.  Are you saying that you'd prefer something that automatically shares/pushes to the remote machine?

**Comment by NoAchache** [comment]
Actually I thought share was not working (it was a config error on the server). It is ok then thanks
