### ISSUE TITLE
Option for `contains: False` in assertions

### ISSUE THREAD

**Issue by Rusteam** [promptfoo/promptfoo#588]
Sometimes LLMs return a response in html/markdown format when not asked for it specifically. It will be helpful to ascertain that any markup formatting characters are not present in the response.

**Comment by typpo** [comment]
Perhaps you could do a [regex check](https://promptfoo.dev/docs/configuration/expected-outputs/deterministic/#regex) for lines starting with `#` or links of the form `[...](...)`?

**Comment by Rusteam** [comment]
Brilliant idea. I myself ended up using `llm-rubric` to check for absence of any formatting.

**Comment by typpo** [comment]
Excellent!  Let me know if you run into any other cases where it would be useful to add a new assertion type.
