### ISSUE TITLE
Promptfoo share link cannot render the json object correctly

### ISSUE THREAD

**Issue by jingconan** [promptfoo/promptfoo#59]
Thanks for building the useful tool. I found the following bug. 

- When I create a public link using `promptfood share`. The prompt is displayed as `object object` (https://share.getcloudapp.com/5zuONPnd) . 
- This works okay in the local server. 
- Please see this video for more details: https://app.visla.us/clip/1127803618527932417

**Comment by typpo** [comment]
Hi @jingconan,

Can you please hard refresh the shared page and try again?  This should be resolved now.  Builds were not happening automatically due to the repo switch from my personal account to `promptfoo` github org.

**Comment by jingconan** [comment]
Yep, just hard refreshed and it works now: https://share.getcloudapp.com/P8uXG7zL . Thank you very much Ian!
