### ISSUE TITLE
Is there a way to increase the concurrency of requests made to different models / API's?

### ISSUE THREAD

**Issue by zeldrinn** [promptfoo/promptfoo#60]
It would be great to be able to make many calls concurrently for the different prompts/models. Is this possible today? Making all the calls in serial makes many tests prohibitively time consuming.

Thanks!

**Comment by zeldrinn** [comment]
@typpo apologies if this is already supported, just let me know :)

**Comment by typpo** [comment]
This is supported through the `evaluateOptions.maxConcurrency` config, or `--max-concurrency` or `-j` on the command line! It defaults to `4` if not set.

For example:
```
promptfoo eval -j 8
```

**Comment by zeldrinn** [comment]
ah perfect! thanks @typpo.
