### ISSUE TITLE
defaultTest property gets deleted from .yaml file when it is edited through the web ui

### ISSUE THREAD

**Issue by remixer-dec** [promptfoo/promptfoo#625]
https://promptfoo.dev/docs/configuration/guide/#default-test-cases
when I try to add this property to the config file in the UI via the "edit yaml" button, it just disappears after clicking "save"

**Comment by typpo** [comment]
Thanks for catching, fixed in #629

**Comment by remixer-dec** [comment]
Thanks for a quick fix! I wanted to try multi-attempt evaluations, but seems like "evaluateOptions" also disappears from the config if it is edited in the UI  https://promptfoo.dev/docs/configuration/reference#config

**Comment by typpo** [comment]
added this one too :+1:

**Comment by typpo** [comment]
Change is released in [0.51.0](https://github.com/promptfoo/promptfoo/releases/tag/0.51.0)

**Comment by remixer-dec** [comment]
Hi, I checked out the updated version and these options are indeed in the UI, but have no effect and are ignored during the evalutation.

**Comment by big-camel** [comment]
> Hi, I checked out the updated version and these options are indeed in the UI, but have no effect and are ignored during the evalutation.

#829
