### ISSUE TITLE
How to leave `{{x}}` in prompt template when `x` is not a variable?

### ISSUE THREAD

**Issue by sangwoo-joh** [promptfoo/promptfoo#627]
For instance, if I have a prompt template like the following:

```
Please generate {{language}} for {{target}}
```

And I only have `language` in my tests.
I want the final prompt look like

```
Please generate French for {{target}}
```

but currently, it gives me

```
Please generate French for
```

How can I leave `{{x}}` like this?

**Comment by typpo** [comment]
In nunjucks templates, you can put a string literal inside of double curly braces.  For example, this will do what you want:
```
prompts:
  - "Please generate {{language}} for {{'{{target}}'}}"
```
