### ISSUE TITLE
Local Models on Promptfoo

### ISSUE THREAD

**Issue by abrar-tericsoft** [promptfoo/promptfoo#630]
how can we make use of promptfoo on local llm models on my machine?

**Comment by typpo** [comment]
It depends what you're using to run local models.  See instructions on [ollama](https://promptfoo.dev/docs/providers/ollama/) and [LocalAI](https://promptfoo.dev/docs/providers/localai), for example.

**Comment by typpo** [comment]
Closing this out.  Let me know if you have any other questions!
