### ISSUE TITLE
Type names and field names cannot be a keyword: 'pass'

### ISSUE THREAD

**Issue by sangwoo-joh** [promptfoo/promptfoo#642]
Thanks to #638, I can now execute Python asserts with huge inputs.
However, the `GradingResult` class in Python has the following error:

```
ValueError: Type names and field names cannot be a keyword: 'pass'
```

Maybe renaming to other names e.g., `has_passed` or `passed` would resolve this issue.
Thank you.

**Comment by typpo** [comment]
I think this is just a documentation error, the return type is really just a `Dict[str, Any]` with a `"pass"` key.  I'll update the docs

**Comment by sangwoo-joh** [comment]
@typpo thanks for the comment.
But I don't think it's just a documentation error.
I get this message from `npx promptfoo view` result columns:

```
Error: Python script execution failed: Error: ValueError: Type names and field names cannot be a keyword: 'pass'

Error: Python script execution failed: Error: ValueError: Type names and field names cannot be a keyword: 'pass'
  at runAssertion(.../node_modules/promptfoo/dist/src/assertions.js:184:27)
  at process.processTicksAndRejections(node:internal/process/task_queues:95:5)
  at async .../node_modules/promptfoo/dist/src/assertions.js:83:24
```

**Comment by typpo** [comment]
What does your script look like? You should make sure that you are not
creating a class with a "pass" attribute.

**Comment by sangwoo-joh** [comment]
@typpo Sorry, one of my scripts defined `GradeResult` class in it!! I've missed this.
After removing this declaration, I got the correct result.
Thank you so much!!
