### ISSUE TITLE
Show Result with Virtualization

### ISSUE THREAD

**Issue by sangwoo-joh** [promptfoo/promptfoo#643]
When I have 10k+ eval results, `npx promptfoo view --yes` show a page that renders too long.
I found that promptfoo is using mui, and there is [Data Grid Virtualization](https://mui.com/x/react-data-grid/virtualization/) feature in mui, so this could improve the result page in an order of magnitude.

**Comment by typpo** [comment]
#649 adds pagination, which should solve the immediate problem of pages too large to render

**Comment by sangwoo-joh** [comment]
@typpo thank you, that sounds wonderful!

**Comment by typpo** [comment]
Pagination released in [0.52.0](https://github.com/promptfoo/promptfoo/releases/tag/0.52.0)
