### ISSUE TITLE
Support Cloudflare Workers AI

### ISSUE THREAD

**Issue by CamdenClark** [promptfoo/promptfoo#647]
Leaving a ticket here for something I want to implement shortly: supporting cf workers AI.

They have beta support for uploading lora finetunes and could support very low latencies. So I think it's a great target to support in promptfoo.

**Comment by typpo** [comment]
Sounds good, the API looks nice and clean so hopefully not much of a lift!

**Comment by jacobdr** [comment]
@CamdenClark any interest in helping me test my branch?

**Comment by CamdenClark** [comment]
> @CamdenClark any interest in helping me test my branch?

Yeah I can this weekend!
