### ISSUE TITLE
Feature Request: Aggregate and/or Calculated Metrics

### ISSUE THREAD

**Issue by thomascleberg** [promptfoo/promptfoo#654]
It would be fantastic to be able to aggregate and/or apply logic over Metrics in a custom way. 

For example, if you had a requirement that context be both `relevant` and `faithful`, it would be nice to be able to implement `context-relevant`, `context-faithful` , (`context-relevant` > n AND `context-faithful` > m), `context-relevant` * `context-faithful` et cetera.

**Comment by typpo** [comment]
Thanks for the suggestion @thomascleberg.  Definitely interested in implementing this - will follow up once I open a PR

**Comment by typpo** [comment]
@thomascleberg WIP here: https://github.com/promptfoo/promptfoo/pull/670

**Comment by typpo** [comment]
This is now supported as of 0.53.0. Documentation here: https://promptfoo.dev/docs/configuration/expected-outputs/#creating-derived-metrics
