### ISSUE TITLE
Bug: search bar in `promptfoo view`

### ISSUE THREAD

**Issue by romaintoub** [promptfoo/promptfoo#659]
I've noticed a weird behaviour when you enter "**" in the search bar. The web page freezes and returns an error: `Application error: a client-side exception has occurred (see the browser console for more information).`

![image](https://github.com/promptfoo/promptfoo/assets/64668750/bdb7778c-d973-4333-bc86-bca7176f5b80)
>>

**Comment by typpo** [comment]
This is likely because the searchbar supports regex and `*` will match everything 🙃.  Probably a small fix

**Comment by romaintoub** [comment]
yea that's why I thought haha, thanks!

**Comment by typpo** [comment]
Fix released in [0.52.0](https://github.com/promptfoo/promptfoo/releases/tag/0.52.0)
