### ISSUE TITLE
Feature Request: Loading data for evaluate() from data loaded into memory

### ISSUE THREAD

**Issue by anthonyivn2** [promptfoo/promptfoo#665]
Hi team, 

I was reading through the docs and it seems like today promptfoo's `evaluate()` does not support the use of data that is already in memory (when running the node library). I have a use case where I would like to evaluate hundreds of `new` question answers on a daily basis through promptfoo, and I am not sure if that is something that is doable today.

**Comment by typpo** [comment]
Hi @anthonyivn2, can you clarify what you're looking for?  It seems you could do something like this and pass in the data you've already loaded separately:

```js
const results = await promptfoo.evaluate(
  {
    prompts: ["First prompt with {{question}} and {{answer}}', "..."],
    providers: ["openai:gpt-3.5-turbo"],
    tests: [
      {
        vars: {
          question: "...",
          answer: "...",
        },
      },
      {
        vars: {
          question: "...",
          answer: "...",
        },
      },
    ],
    writeLatestResults: true, // write results to disk so they can be viewed in web viewer
  },
  {
    maxConcurrency: 2,
  },
);
```

**Comment by anthonyivn2** [comment]
@typpo Ok so does evaluate() accepts inputs other than [TestSuiteConfiguration object](https://www.promptfoo.dev/docs/configuration/reference#testsuiteconfiguration) as specified in the [Node Package Usage doc](https://www.promptfoo.dev/docs/usage/node-package#usage)?

To confirm, `writeLatestResults: true` is different from sharing the data right?

**Comment by typpo** [comment]
Yes, looks like that type definition in the doc is a bit out of date. I'll
get it updated. Here is the actual type used in the code:
https://github.com/promptfoo/promptfoo/blob/0337f1343a3fb21df457a1ced7c76734dc32f16f/src/types.ts#L560

Also, I can confirm that writeLatestResults only writes locally.

Let me know if you have any other questions!

**Comment by anthonyivn2** [comment]
Ok this should work for my use case. I will close this issue, thank you for the response!
