### ISSUE TITLE
Is custom Python/Javascript assertion available through the evaluate() node module?

### ISSUE THREAD

**Issue by anthonyivn2** [promptfoo/promptfoo#673]
Related to the question related to PR #668. I would like to be able to define custom assertions in Python/Javascript and then use it with the `evaluate()` node module

**Comment by typpo** [comment]
Yes, both of these assertion types are supported via `promptfoo.evaluate`.  

In the case of `javascript` asserts, you can supply a function directly as the assertion `value`.  I notice an inconsistency in how functions are called between external js files/inline js functions vs functions directly provided via `evaluate`, which will be addressed in #674

**Comment by anthonyivn2** [comment]
Ok noted, thank you!
