### ISSUE TITLE
Cannot See Previous Evaluation History Intermittently

### ISSUE THREAD

**Issue by sangwoo-joh** [promptfoo/promptfoo#681]
I don't know why, but sometimes I cannot see my previous evaluation history intermittently.
Once it goes away, it takes a few more evals before it becomes visible again.
Not sure where should I look into...

**Comment by typpo** [comment]
@sangwoo-joh are you still seeing this problem?

**Comment by typpo** [comment]
We can reopen this if we get repro instructions!
