### ISSUE TITLE
Feature Request: Extend Comment options in UI

### ISSUE THREAD

**Issue by magdalena-mladenova-veeva** [promptfoo/promptfoo#708]
The matrix view in the UI allows the user to leave a comment on each model output, which is really helpful! 

For some tasks outputs can be rather long & it'd be very helpful if we could leave multiple comments linked to different lines of the output. 

Alternatively, even having a bigger box to leave a comment in would allow for easier editing/review.

Thank you!

**Comment by typpo** [comment]
Hi @magdalena-mladenova-veeva, https://github.com/promptfoo/promptfoo/pull/713 adds an improved comment view. It's still not specific to individual lines of output, but it's a bigger box for you to use.  Hope this helps

**Comment by magdalena-mladenova-veeva** [comment]
amazing, thank you so much!

**Comment by typpo** [comment]
This change is included in release [0.56.0](https://github.com/promptfoo/promptfoo/releases/tag/0.56.0)
