### ISSUE TITLE
support for different provider for llm-rubric and embeddings

### ISSUE THREAD

**Issue by pelikhan** [promptfoo/promptfoo#709]
We have separate deployments for each model. Would it be possible to have a "model-provider" and a "embedding-provider" separate in the defaultTest section?

**Comment by typpo** [comment]
Hi @pelikhan, this is already supported!  Have a look at the example here: https://promptfoo.dev/docs/configuration/expected-outputs/model-graded/#multiple-graders

**Comment by pelikhan** [comment]
Thanks, all green now.
