### ISSUE TITLE
OpenAI base URL environment variable: OPENAI_API_BASE_URL vs OPENAI_BASE_URL

### ISSUE THREAD

**Issue by efung** [promptfoo/promptfoo#716]
OpenAI's API clients support environment variables for specifying the base URL, typically used to connect to OpenAI's servers through a proxy server.

In both their Node API and their Python API, the name of the environment variable is `OPENAI_BASE_URL`:

- Node API [reference](https://github.com/openai/openai-node/blob/c6629c37fcbc5223c258169d49a30bbb668cb07d/src/index.ts#L29)
- Python API [reference](https://github.com/openai/openai-python/blob/e9724398d2bdd87ba41f199c3577303f1b80f2c7/src/openai/_client.py#L118)

Can promptfoo be updated to support the same variable? 

There's currently an `OPENAI_API_BASE_URL` added in #177, which may have been a typo? Or perhaps OpenAI added that variable later?

**Comment by typpo** [comment]
Agreed, let's add support for OPENAI_BASE_URL. I'll do this when I get a
moment or feel free to PR it yourself!
