### ISSUE TITLE
CLI --first-n only runs the first test case regardless of specified argument when using test CSV

### ISSUE THREAD

**Issue by efung** [promptfoo/promptfoo#732]
I'm using promptfoo 0.56 and testing with `/examples/simple-csv`

1. Clone repository
2. `npm i`
3. `cd examples/simple-csv`
4. `npx promptfoo eval`. Observe there are four output rows.
5. `npx promptfoo eval --first-n 3`. Observe that there is only one output row. I expected the first three.

**Comment by typpo** [comment]
My fault for only testing this on --n 1. Fix is in #734
