### ISSUE TITLE
Request: ability to exclude `Description` from `promptfoo view` and persist UI settings across refresh

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#736]
I would like to exclude the `Description` column from `promptfoo view`. Is this possible?

I guess if it's not yet implemented, a request could be to exclude columns like `Description` or keys in `vars` from `promptfoo view`'s table

**Comment by alexclaydon** [comment]
I'd second this - some way to make the web UI configuration persist between page refreshes and server restarts would be great!

**Comment by jamesbraza** [comment]
Oh you're right there per the `vars`. However, but you can't turn off the `Description` field

<img width="667" alt="screenshot of `promptfoo view`" src="https://github.com/promptfoo/promptfoo/assets/8990777/0d373f24-654a-4ad1-9dce-5a6f55a9021a">

See lower left corner of the above screenshot

Do you think you can make the `Description` toggle-able as well?

**Comment by typpo** [comment]
Fix coming in #1095!

**Comment by jamesbraza** [comment]
@typpo thanks for #1095! After pulling in v0.69.2 to try this out, I don't see where in the UI to toggle the description

**Comment by typpo** [comment]
hey james :) it appears in the `Columns` menu for evals that have Descriptions

<img width="858" alt="image" src="https://github.com/promptfoo/promptfoo/assets/310310/f7e918eb-2d0b-477a-bcaa-4221e5c7311f">

**Comment by jamesbraza** [comment]
Hm that is not an option in my run today: https://app.promptfoo.dev/eval/f:96a89d44-4ada-4577-9cd2-7bf8bc7f9433/

Maybe I failed to properly pull in the latest `promptfoo`

**Comment by jamesbraza** [comment]
I confirmed with 0.69.2 locally that what you're seeing (checkbox for description), I am not seeing that same checkbox. Note the web UI I am using was made by `--share`

<img width="432" alt="image" src="https://github.com/promptfoo/promptfoo/assets/8990777/efcbcd0a-79e0-45a1-822b-530217a71f68">
