### ISSUE TITLE
Request: support `--max-concurrency=auto`

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#737]
There is a `pytest` plugin for running tests concurrently using multiprocessing. That plugin supports automagically inferring the number of parallel processes to spawn: `pytest -n auto`.

I know `promptfoo` supports concurrency using `--max-concurrency` (defaulted as of `0.55.0` to 4).
- What type of concurrency does `promptfoo` use? Is it multiprocessing?
- Can we support `--max-concurrency=auto`, and do basic machine-tailored inference for an optimal amount of concurrency?

**Comment by typpo** [comment]
Evals are I/O bound with respect to the LLM APIs, so in practice it is not
desirable to set it based on your number of CPUs but instead your
network, rate limits, etc.  The concurrency uses node's event loop as
opposed to multiprocessing.

**Comment by jamesbraza** [comment]
Okay I see. So I guess it's not really feasible to auto-infer a concurrency count.

I will open a docs PR to at least add that the concurrency is managed via a single process event loop
