### ISSUE TITLE
Request: CLI arg to suppress exit code 100 in `promptfoo eval`

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#741]
I am using `promptfoo` to evaluate a benchmark, not a binary pass/fail outcome. The benchmark is quite hard, so it's basically guaranteed at least one test case will fail.

I can see `promptfoo eval` will return exit code 100 if there are 1+ test case failures. This is actually documented and makes sense ([docs link](https://www.promptfoo.dev/docs/usage/command-line/#promptfoo-eval)).

The request is it would be useful if there was a CLI flag for `promptfoo eval` that would allow test case failures. In other words, even if there's a test case failure, the exit code would be 0. Exit code 1 is used for all other failure modes still.

Possible naming ideas are `--allow-failed-cases` or `--exit-code-ignores-failures`. Thanks for your consideration 👍 

---

I am using `promptfoo==0.55.0`.

A workaround is manually suppressing the exit code 100 using `promptfoo eval || [ $? -eq 100 ]`.

**Comment by typpo** [comment]
#751 should solve this by allowing you to set `PROMPTFOO_FAILED_TEST_EXIT_CODE=0`
