### ISSUE TITLE
Multiple prompts in a single prompt file when using multiple prompt files

### ISSUE THREAD

**Issue by alexclaydon** [promptfoo/promptfoo#744]
In the documentation it says:

"If you have only one file, you can include multiple prompts in the file, separated by the separator `---`. If you have multiple files, each prompt should be in a separate file."

Multiple prompts in a single file is very convenient, and it's a shame to lose the ability to do this if you have more than one prompt file.  Removing this limitation would allow the use of multiple prompts and multiple prompt files together, meaning you could have, e.g., a `.txt` file containing your string-formatted prompts, and a `.json` file containing JSON-formatted message pairs.

**Comment by mldangelo** [comment]
Hi @alexclaydon! Thanks for the great suggestion. This works now! Please give it a try.

**Comment by alexclaydon** [comment]
Thank you very much!  We will certainly do so 🙏🏻
