### ISSUE TITLE
pass logger as callApi 

### ISSUE THREAD

**Issue by pelikhan** [promptfoo/promptfoo#746]
In order to have the custom provider fit into the existing logging infrastructure, add the `logger` object in the Api options call.

**Comment by typpo** [comment]
Great suggestion. I've also included some caching utils in #748, as that is a request I've seen elsewhere.

**Comment by typpo** [comment]
This change is included in [0.57.0](https://github.com/promptfoo/promptfoo/releases/tag/0.57.0), just published on npm
