### ISSUE TITLE
add evalId in generate OutputFile

### ISSUE THREAD

**Issue by pelikhan** [promptfoo/promptfoo#752]
If we could have the `evalId` of a run in the generated output file (OutputFile), it would be possible to get the VSCode test controller UI to reopen the promptfoo web ui on the evluation page using the `eval?evalId=...` route.

**Comment by pelikhan** [comment]
The context is that I have a testcontroller in visual studio code that provide a nice front end to the tests. If I can store the eventId for a run, I can open the web ui directly in vs code for a nice integrated experience.

**Comment by typpo** [comment]
Your PR is released in 0.62.0!

**Comment by pelikhan** [comment]
Great news. Thanks for pushing it through.
