### ISSUE TITLE
Shouldn't "gemini-1.5-pro-latest" be named "gemini-1.5-pro-preview-0409"?

### ISSUE THREAD

**Issue by StephanSchuster** [promptfoo/promptfoo#760]
I am new to this awesome tool, so I don't know if the above makes sense. But using "vertex:gemini-1.5-pro-latest" for me results in a an API error while using "vertex:gemini-1.5-pro-preview-0409" shows a (wrong?) warning but works. Please let me know if I am doing something wrong. Otherwise you probably want to rename the following code location:
https://github.com/promptfoo/promptfoo/blob/ac542d1801a819fd8ad267188848814c1ecc6a10/src/providers/vertex.ts#L157

![screenshot](https://github.com/promptfoo/promptfoo/assets/5207269/71415b43-31db-4677-880a-ce29a5b69572)

**Comment by typpo** [comment]
It looks like maybe Google updated or swapped the model strings (listed [here](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versioning#gemini-model-versions)).  I've added `gemini-1.5-pro-preview-0409`.  The warning is harmless and can be ignored.  Thanks for flagging this!
