### ISSUE TITLE
When writing JSON output of an eval, include the timestamp of the run

### ISSUE THREAD

**Issue by efung** [promptfoo/promptfoo#778]
In the SQLite database of promptfoo, I can see that evals have a `createdat` timestamp, and this is visible in the Web UI as well.

However, when running via the CLI using something like `npx promptfoo eval --output eval_output.json`, the JSON file does not contain a timestamp anywhere. 

It would be nice if a timestamp could be included somewhere in the output dictionary.

**Comment by typpo** [comment]
Done in #785 !

**Comment by typpo** [comment]
Released in 0.59.0
