### ISSUE TITLE
Prettify messages json strings for multi-prompt chat conversations

### ISSUE THREAD

**Issue by rhdunn** [promptfoo/promptfoo#783]
If I use a multi-prompt chat per the [chat conversations](https://www.promptfoo.dev/docs/providers/openai#chat-conversations) docs, the view html output is rendered as JSON.

It would be nice if there was a way to render the role/content JSON in an easier to view form as a Table View Settings option as the raw JSON can be hard to read, especially long prompts or prompts that include code or other markup/markdown.

**Comment by typpo** [comment]
I believe this is addressed by the introduction of the `label` field on prompts. Closing it out, lmk if you have any issues! https://promptfoo.dev/docs/configuration/parameters#different-prompts-per-model

**Comment by JakubMindNexus** [comment]
I'd like to add my 2 cents here. That's how JSON prompts are rendered in the UI. It's quite hard to read. 

In my case, prompts are generated by JS script, so it's impossible to read them easily in an other way. 

<img width="1219" alt="image" src="https://github.com/user-attachments/assets/d0a6f0db-b7f8-4bbb-9ff5-f8b181ff9040">
