### ISSUE TITLE
Feature Request: Also Pass `logProbs` to Python Assertions

### ISSUE THREAD

**Issue by thomascleberg** [promptfoo/promptfoo#788]
Currently, Python custom asserts only receive the output and the context from the provider. In order to provide full functionality, we also need to pass the `logprobs` object.

https://github.com/promptfoo/promptfoo/blob/7639fbe5bb40482be7faf4f9bbe1aed2a277d2fc/src/assertions.ts#L268

**Comment by typpo** [comment]
#790 adds `logProbs` to the `context` object passed to assertion functions :)

**Comment by typpo** [comment]
Released in 0.59.0!
