### ISSUE TITLE
In the html report (view/shared), instruction tokens and completion tokens should be shown separately.

### ISSUE THREAD

**Issue by harsh-writesonic** [promptfoo/promptfoo#793]
In the current implementation of the HTML report (view/shared), the instruction tokens and completion tokens are not differentiated. For better clarity and analysis, it is important to show instruction tokens and completion tokens separately in the report.

**Comment by typpo** [comment]
Shown in #794.

**Comment by harsh-writesonic** [comment]
Amazing. Thanks for the prompt resolution. This tool is amazing.

**Comment by typpo** [comment]
Released in 0.59.0!
