### ISSUE TITLE
Browser view seems to fail with very large TestSuites 

### ISSUE THREAD

**Issue by Skylertodd** [promptfoo/promptfoo#80]
It seems that when trying to render a large result set, 200+ tests with lots of data, the UI fails to display all of the information.

From first glance it looks like it might be possibly due to a limitation in the web socket delivery, but have not looked into it in detail.

**Comment by typpo** [comment]
How large is your `~/.promptfoo/output/latest.json` file and is there a version of the file you'd be able to share privately?  When you say "fails to display all of the information" can you elaborate a bit on what that failure looks like?

I've just tried it with a 470mb results file and it worked ok (albeit with a bit of a wait), so will likely need more debugging info to pinpoint an issue here.

**Comment by typpo** [comment]
Closing this!  Feel free to reopen with more repro details.
