### ISSUE TITLE
Mistral Instruct prompt erroneously considered as JSON

### ISSUE THREAD

**Issue by cedricablain** [promptfoo/promptfoo#824]
Trying to use promptfoo on mistral-instruct 7b.

Here is a basic non-working example taken from [mistral prompting guides ](https://www.promptingguide.ai/models/mistral-7b#chat-template-for-mistral-7b-instruct):
```
[INST] You are a helpful code assistant. Your task is to generate a valid JSON object based on the given information:
name: John
lastname: Smith
Just generate the JSON object without explanations:
[/INST]
```

When using this prompt directly inside the YAML configuration or inside a dedicated file `.txt`, we are welcomed with the following error :
`[FAIL] Error: Chat Completion : prompt is not a valid JSON string: SyntaxError: Unexpected token 'I', "[INST] You "... is not valid JSON`

As far as I understand, promptfoo wrongly consider this "text" block as a JSON because of the first `[`. 

Is there any way to get around this issue and force this prompt as "plain-text" even if it starts with a bracket ?

**Comment by typpo** [comment]
Thanks for reporting, this is indeed a bug. 

As a temporary workaround, you can set options.prefix and options.suffix to [INST] and [/INST] respectively. https://promptfoo.dev/docs/configuration/reference/#test-case. Then your text file can just contain the prompt text. 

To avoid repetition you can use the defaultTest property to apply this to all tests.

**Comment by typpo** [comment]
Actually, which provider are you using for mistral 7b instruct?  I think there is a deeper issue here where you're using a chat completion provider for a non-chat API.  This means it expects a JSON formatted string and the error is intended.

**Comment by cedricablain** [comment]
We're using a locally hosted Ollama inference server with [mistral:instruct model](https://ollama.com/library/mistral:instruct)

**Comment by typpo** [comment]
Perhaps you should be prefixing the provider with ollama:completion instead of ollama:chat

**Comment by typpo** [comment]
Let me know if that doesn't work!
