### ISSUE TITLE
promptfoo 0.60.0 --share not working

### ISSUE THREAD

**Issue by JiajunZhou-ws** [promptfoo/promptfoo#832]
I am upgrading to promptfoo 0.60.0 and run my test again with `--share` flag.

<img width="806" alt="image" src="https://github.com/promptfoo/promptfoo/assets/6728224/3f075f54-07d1-4889-90ad-407cc00b1259">
<img width="1920" alt="image" src="https://github.com/promptfoo/promptfoo/assets/6728224/25ea3995-81a7-4a0b-acbe-0ffd7eb65117">

It failed both in CI/CD and local. Looks like a bug.
Could you reproduce this on your side?

**Comment by typpo** [comment]
Thanks for the report.  This should be fixed now.  Could you please confirm on your side?

**Comment by JiajunZhou-ws** [comment]
@typpo Thanks!! It works!
