### ISSUE TITLE
Allow options to avoid using special characters

### ISSUE THREAD

**Issue by shuaiwangdd** [promptfoo/promptfoo#843]
Hi, I have a need to invoke a shell script to install and run ```promptfoo eval``` in Java code and host it in a K8s Ubuntu based container. The promptfoo commands are executed in a separate process and I wired the output to stdout and stderr. However, since promtpfoo can output lots of special characters, like progress  bar, green check mark, yellow triangle question mark, colorful bold fonts, somehow it is not printable in my java program. 

For instance, when I run ```prompt share```, nothing shows up as the url is in bold green and there is a green check mark.

I verified the LANG env var. to be UTF8, font setting and terminal emulator, all look good. 

Is there a way to avoid using special character but only output ASCII? 

FYI
node -v: **v20.6.1**
promptfoo --version: **0.57.1**

**Comment by typpo** [comment]
To disable terminal colors for printed outputs, set `FORCE_COLOR=0` (this is supported by the [chalk](https://github.com/chalk/chalk) library).  You will also have to disable the progress bar and table separately:

```
FORCE_COLOR=0 promptfoo eval --no-progress-bar --no-table
```

Hope this helps!

**Comment by shuaiwangdd** [comment]
Thanks for the prompt response, is there a way to disable the green check mark as well?

**Comment by typpo** [comment]
The green check is a single unicode character, I believe its coloration is just dependent on your how your OS or terminal renders those characters (for example, on my Ubuntu it is just a plain black and white checkmark)

**Comment by typpo** [comment]
Closing this out, let me know if you run into any issues!
