### ISSUE TITLE
How can I set threshold for avg. of test cases scores with csv?

### ISSUE THREAD

**Issue by sjsinju** [promptfoo/promptfoo#853]
I currently set test cases with csv using `__expected{num}` well. But I cannot set `threshold` for avg. score of `__expected{num}`'s results.
I want to get `PASS` if the avg. of the scores exceed the threshold I set.

example) If I set `0.5` for threshold

__expected1 : `1.0`
__expected2 : `1.0`
__expected3 : `1.0`
__expected4 : `0`

0.75 > 0.5 : `PASS`

Can you tell me how I set the threshold for tests cases with csv? 
If there is no way, Can you support this function such as `__threshold`?

Related : #606, #238

**Comment by typpo** [comment]
`__threshold` support added in #903!

**Comment by typpo** [comment]
Released in 0.63.0
