### ISSUE TITLE
output json filenames are not valid in windows 

### ISSUE THREAD

**Issue by liorn** [promptfoo/promptfoo#87]
When I run promptfoo eval in windows, it fails to write the output file because it contains a colon (e.g. eval-2023-07-23T18:11:14.744Z.json).

This used to work, maybe the output filename format recently changed?

Thanks!

**Comment by typpo** [comment]
Hi @liorn, you're right, the filename format changed with version `0.17.8`.  I've just committed a fix which will be released shortly in the next version.  Sorry about that.

In the meantime, you can use `0.17.7`, for example with `npx promptfoo@0.17.7 eval`

**Comment by typpo** [comment]
Fixed in release `0.17.9`
