### ISSUE TITLE
Compare providers based on latency

### ISSUE THREAD

**Issue by renzel** [promptfoo/promptfoo#891]
Great tool!
It would be great to have the time/latency for each test in the cli, so you could compare between the providers.

**Comment by typpo** [comment]
Can you clarify what you're looking for?  For uncached tests, latency is shown at the bottom of each cell.

Also worth noting you can use the `latency` assertion to fail tests that take too long!  [docs](https://promptfoo.dev/docs/configuration/expected-outputs/deterministic/#latency)

![image](https://github.com/promptfoo/promptfoo/assets/310310/7eb7641b-2a6c-4a88-85c6-977056393c0b)

**Comment by renzel** [comment]
<img width="1555" alt="Skjermbilde 2024-06-09 kl  21 50 34" src="https://github.com/promptfoo/promptfoo/assets/14833769/df578097-e0f7-4b79-9d39-002517540f79">
It doesnt seem to work for "exec" and not for all tests for openai:gpt-4o

**Comment by typpo** [comment]
A fix to show latency even when other information is not available has landed in 0.63.0 (bb335efbe9e8d6b23526c837402787a1cbba9969).  Thanks for flagging!
