### ISSUE TITLE
outputPath not implemented for NodeJS API

### ISSUE THREAD

**Issue by etburke** [promptfoo/promptfoo#91]
I see this in the documentation:

https://github.com/promptfoo/promptfoo/blob/a40a24237cdbfe54aa5038f53d92a1db000c4215/README.md?plain=1#L196

But it does not appear to be implemented here:

https://github.com/promptfoo/promptfoo/blob/a40a24237cdbfe54aa5038f53d92a1db000c4215/src/index.ts#L17-L33

Is this the case or did I miss something?

**Comment by typpo** [comment]
Hi @etburke, you're absolutely right.  I've addressed this in commit 6ad0853ff6fea0b8514a08d0426f3ddad55be526 which will be part of the next release.
