### ISSUE TITLE
bedrock:meta.llama3-70b-instruct-v1:0 - No output

### ISSUE THREAD

**Issue by underyx** [promptfoo/promptfoo#912]
Using this model on 0.63 returns all failures which only say 'No output'

**Comment by typpo** [comment]
Should be fixed in 0.63.1

**Comment by mldangelo** [comment]
Thanks for fixing this @fvdnabee. We deployed your change in [0.68.0](https://github.com/promptfoo/promptfoo/releases/tag/0.68.0)!
