### ISSUE TITLE
Retry only failed tests

### ISSUE THREAD

**Issue by dustinsoftware** [promptfoo/promptfoo#925]
Hi, great project!

Is there support for ignoring the cache and retrying only tests that didn't pass? Something like [playwright](https://playwright.dev/docs/test-retries#retries). If not, would you be open to me opening a PR to add support for it?

Thanks!

**Comment by typpo** [comment]
This is actually supported through the `--filter-failing` flag! Thanks to @mikkoh 
 https://promptfoo.dev/docs/usage/command-line/#promptfoo-eval

It takes a JSON output from a previous `eval` run, and only runs the tests that failed.   For example:
```sh
promptfoo eval -o output.json

# ...

promptfoo eval --filter-failing output.json
```

**Comment by AymericG** [comment]
I am getting the error 
<img width="324" alt="image" src="https://github.com/promptfoo/promptfoo/assets/446402/03dc8165-1d7b-4b2e-a488-d3f4d0025ff8">

**Comment by mrafnadeem-apimatic** [comment]
@typpo I did it exactly like this, but the tests are not running a second time.

```
promptfoo eval -o output.json
promptfoo eval --filter-failing output.json
```
