### ISSUE TITLE
[BUG] When using eval command there are diff between using config option and not using config option

### ISSUE THREAD

**Issue by suhwan-kang** [promptfoo/promptfoo#927]
I found that if i use eval command with config option, the prompts label is disappeared.

I try to analyze why it cause and found out that there is code problem.
In deail,
`main.ts ->` when using config option, it use `readconfigs` function which is using readConfig multiple time for reading config files and do post process for each config datas.
and when not using config option, it use `maybeReadConfig` function which is only using `readConfig` onetime.
The function `readConfigs`'s post processing has problem.
`util.ts ->` `readConfigs` has internal function `seenPrompts` process only prompt's id without process label.
It cause the problem that label gonna disappear when I use objects array that contain both id and label.
In result, result table miss the label option and display python code or raw prompt which did't render template variables.

Could you check it and give me a comment that whether it is intentional or not?

**Comment by typpo** [comment]
This is not intentional - seems to be a bug.  `seenPrompts` should take into account the label as well.  Thank you for catching and analyzing this bug!

**Comment by suhwan-kang** [comment]
It seems that Version 0.64.0 didn't have this bug patch.
Could you tell me when this fix is applied in release package?
I hope the bug patch is reflected in a released version.

**Comment by typpo** [comment]
Thanks @suhwan-kang, this will be included in the next release!

**Comment by typpo** [comment]
released in 0.65.2
