### ISSUE TITLE
Add support for `.yml` for the config file

### ISSUE THREAD

**Issue by ZanzyTHEbar** [promptfoo/promptfoo#978]
Small QOL improvement, right now the promptfoo cli does not find `promptfooconfig.yml` files, when `.yml` is a valid file descriptor according to the YAML specification.

**Comment by typpo** [comment]
Done in f948f26457099db762690f48373747ad9321cc9b.  Will be in the next release!

**Comment by typpo** [comment]
Released in 0.66.0
